import type { SectionDef } from './workspace-sections'

export const ESTUDO_DOUTRINARIO_SECTIONS: SectionDef[] = [
  {
    slug: 'edt_definicao',
    title: 'I. Definição',
    shortTitle: 'Definição',
    phase: 'preparar',
    module: 'inventio',
    group: 'edt_definicao_grp',
    groupLabel: 'I. Definição',
    order: 200,
    objective:
      'Estabelecer com precisão o nome da doutrina, suas definições resumida e expandida, e a questão central que o estudo se propõe a responder.',
    keyQuestions: [
      'Qual é o nome técnico e os nomes alternativos da doutrina?',
      'Como a doutrina pode ser definida em uma sentença e em um parágrafo?',
      'Qual é a questão central que a doutrina responde na teologia cristã?',
      'Que outras doutrinas são logicamente relacionadas a esta?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'nome_doutrina',
        title: 'Nome da doutrina',
        placeholder: 'Qual é o nome técnico da doutrina? Há sinônimos, nomes alternativos ou termos em outros idiomas (latim, grego) que o estudante precisa conhecer?',
        aiTrigger: 'Qual é o nome técnico desta doutrina? Liste sinônimos, termos latinos ou gregos relevantes e explique a etimologia ou origem histórica do termo principal.',
      },
      {
        id: 'definicao_resumida',
        title: 'Definição resumida',
        placeholder: 'Defina a doutrina em uma frase clara e precisa, adequada para ser memorizada. Deve capturar a essência sem ser simplista.',
        aiTrigger: 'Formule uma definição resumida e precisa desta doutrina em uma sentença que possa ser memorizada. Deve capturar a essência da doutrina sem simplificação excessiva.',
      },
      {
        id: 'definicao_expandida',
        title: 'Definição expandida',
        placeholder: 'Desenvolva a definição em um parágrafo que explique os elementos constitutivos da doutrina, suas distinções necessárias e seu alcance.',
        aiTrigger: 'Desenvolva uma definição expandida desta doutrina (1 parágrafo) explicando seus elementos constitutivos, distinções necessárias e alcance, segundo Berkhof ou Bavinck.',
      },
      {
        id: 'questao_central',
        title: 'Questão central',
        placeholder: 'Qual é a pergunta fundamental que esta doutrina responde? Formule a questão de modo que os debates históricos em torno dela façam sentido.',
        aiTrigger: 'Qual é a questão teológica central que esta doutrina responde? Formule a pergunta de modo que os debates históricos e contemporâneos em torno dela se tornem compreensíveis.',
      },
    ],
  },
  {
    slug: 'edt_fundamentacao_biblica',
    title: 'II. Fundamentação Bíblica',
    shortTitle: 'Fundamentação Bíblica',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_fundamentacao_grp',
    groupLabel: 'II. Fundamentação Bíblica',
    order: 201,
    objective:
      'Estabelecer a base bíblica da doutrina através das passagens principais, seu desenvolvimento no Antigo e Novo Testamentos e a progressão revelacional.',
    keyQuestions: [
      'Quais são as passagens bíblicas que fundamentam diretamente esta doutrina?',
      'Como o Antigo Testamento prepara ou antecipa esta doutrina?',
      'Como o Novo Testamento desenvolve ou cumpre o que o AT antecipava?',
      'Há progressão ou desenvolvimento desta doutrina ao longo do cânone?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'passagens_principais',
        title: 'Passagens principais',
        placeholder: 'Liste as passagens bíblicas primárias que fundamentam esta doutrina. Para cada passagem, indique como ela contribui para a fundamentação.',
        aiTrigger: 'Liste as 5 a 8 passagens bíblicas mais importantes para a fundamentação desta doutrina. Para cada uma, explique sua contribuição específica para o ensino doutrinal.',
      },
      {
        id: 'desenvolvimento_at',
        title: 'Desenvolvimento no AT',
        placeholder: 'Como o Antigo Testamento apresenta, prepara ou antecipa esta doutrina? Que textos, temas ou instituições veterotestamentárias estão relacionados?',
        aiTrigger: 'Como o Antigo Testamento apresenta, prepara ou antecipa esta doutrina? Identifique textos, temas, tipos ou instituições veterotestamentárias que contribuem para seu desenvolvimento.',
      },
      {
        id: 'desenvolvimento_nt',
        title: 'Desenvolvimento no NT',
        placeholder: 'Como o Novo Testamento desenvolve, clarifica ou cumpre o que o AT antecipava? Que autores neotestamentários contribuem mais para esta doutrina?',
        aiTrigger: 'Como o Novo Testamento desenvolve, clarifica ou cumpre esta doutrina? Quais autores neotestamentários (Paulo, João, Pedro, Hebreus) oferecem as contribuições mais significativas?',
      },
      {
        id: 'progressao_revelacional',
        title: 'Progressão revelacional',
        placeholder: 'Como esta doutrina se desenvolve ao longo da revelação progressiva? Há diferentes ênfases em diferentes períodos da história da redenção?',
        aiTrigger: 'Trace a progressão revelacional desta doutrina: como ela se desenvolve do AT para o NT e como atinge sua formulação mais completa na revelação apostólica? Use Vos ou Goldsworthy como referência.',
      },
    ],
  },
  {
    slug: 'edt_historia_doutrina',
    title: 'III. História da Doutrina',
    shortTitle: 'História',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_historia_grp',
    groupLabel: 'III. História',
    order: 202,
    objective:
      'Rastrear o desenvolvimento histórico da doutrina desde a igreja primitiva até a atualidade, identificando os pontos de clarificação e os momentos de crise.',
    keyQuestions: [
      'Como os Pais da Igreja e os apologistas entenderam esta doutrina?',
      'Como a teologia medieval desenvolveu ou distorceu este ensinamento?',
      'Qual foi a contribuição dos Reformadores para a formulação correta da doutrina?',
      'Como a doutrina se desenvolveu após a Reforma até o período contemporâneo?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'igreja_primitiva_patristica',
        title: 'Igreja Primitiva e Patrística',
        placeholder: 'Como os Pais da Igreja (Inácio, Irineu, Tertuliano, Agostinho, etc.) trataram esta doutrina? Que contribuições e que limitações marcaram o período?',
        aiTrigger: 'Como a doutrina foi entendida pelos Pais da Igreja nos séculos II ao V? Identifique os principais teólogos patrísticos que contribuíram para seu desenvolvimento e as limitações do período.',
      },
      {
        id: 'medieval',
        title: 'Período Medieval',
        placeholder: 'Como Anselmo, Tomás de Aquino e os escolásticos desenvolveram ou distorceram esta doutrina? Que debates medievais são relevantes?',
        aiTrigger: 'Como a teologia medieval tratou esta doutrina? Que contribuições positivas foram feitas por Anselmo, Tomás de Aquino ou outros? Que distorções ou omissões precisaram ser corrigidas?',
      },
      {
        id: 'reforma',
        title: 'Reforma',
        placeholder: 'Como Lutero, Calvino, Zuínglio e outros reformadores abordaram esta doutrina? Em que pontos a Reforma clarificou ou reformulou o ensinamento?',
        aiTrigger: 'Qual foi a contribuição dos Reformadores — Lutero, Calvino, Melanchton, Zuínglio — para a formulação desta doutrina? Em que pontos a Reforma representou uma recuperação ou clarificação bíblica?',
      },
      {
        id: 'pos_reforma_atualidade',
        title: 'Pós-Reforma e atualidade',
        placeholder: 'Como a teologia pós-Reforma (Puritan, Westminster, Princeton, século XX) e a teologia contemporânea desenvolveram esta doutrina?',
        aiTrigger: 'Como esta doutrina foi desenvolvida pela teologia pós-Reforma (puritanos, teólogos de Westminster, escola de Princeton) e pelos teólogos do século XX? Que debates contemporâneos são relevantes?',
      },
    ],
  },
  {
    slug: 'edt_formulacao_sistematica',
    title: 'IV. Formulação Sistemática',
    shortTitle: 'Formulação Sistemática',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_formulacao_grp',
    groupLabel: 'IV. Formulação Sistemática',
    order: 203,
    objective:
      'Apresentar a formulação sistemática da doutrina: definição técnica, relações com outras doutrinas, implicações teológicas e distinções necessárias.',
    keyQuestions: [
      'Qual é a formulação técnica e precisa da doutrina na teologia sistemática?',
      'Com quais outras doutrinas esta se relaciona logicamente?',
      'Que implicações teológicas necessárias derivam desta doutrina?',
      'Que distinções são essenciais para evitar mal-entendidos?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'definicao_tecnica',
        title: 'Definição técnica',
        placeholder: 'Apresente a formulação sistemática da doutrina com precisão técnica, usando a terminologia estabelecida pela tradição teológica reformada.',
        aiTrigger: 'Apresente a formulação técnica e precisa desta doutrina na teologia sistemática reformada, usando a terminologia de Berkhof, Bavinck ou Grudem.',
      },
      {
        id: 'relacoes_doutrinarias',
        title: 'Relações doutrinárias',
        placeholder: 'Com que outras doutrinas esta se conecta logicamente? Como a Trindade, a Cristologia, a Soteriologia, a Eclesiologia ou a Escatologia informam e são informadas por esta doutrina?',
        aiTrigger: 'Como esta doutrina se relaciona com outras doutrinas do sistema teológico? Mostre as conexões com: Trindade, Cristologia, Anthropologia, Soteriologia, Eclesiologia e Escatologia.',
      },
      {
        id: 'implicacoes_teologicas',
        title: 'Implicações teológicas',
        placeholder: 'Que implicações teológicas necessárias derivam desta doutrina? O que ela exige que sejamos ou creijamos sobre Deus, o homem e a salvação?',
        aiTrigger: 'Que implicações teológicas necessárias derivam desta doutrina? Explore o que ela implica sobre a natureza de Deus, a condição humana, a salvação e a vida cristã.',
      },
      {
        id: 'distincoes_necessarias',
        title: 'Distinções necessárias',
        placeholder: 'Que distinções técnicas são essenciais para compreender corretamente esta doutrina? O que ela não é, e que confusões comuns precisam ser desfeitas?',
        aiTrigger: 'Que distinções técnicas são necessárias para entender corretamente esta doutrina? Quais são as confusões mais comuns que precisam ser desfeitas? O que a doutrina não afirma?',
      },
    ],
  },
  {
    slug: 'edt_controversias',
    title: 'V. Controvérsias',
    shortTitle: 'Controvérsias',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_controversias_grp',
    groupLabel: 'V. Controvérsias',
    order: 204,
    objective:
      'Examinar os erros históricos, as heresias relacionadas, as visões concorrentes e apresentar as respostas reformadas a cada desafio.',
    keyQuestions: [
      'Que erros históricos foram cometidos em relação a esta doutrina?',
      'Que heresias foram condenadas pelos concílios da Igreja antiga?',
      'Quais são as visões teológicas concorrentes nos dias de hoje?',
      'Como a tradição reformada responde a esses erros com base na Escritura?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'erros_historicos',
        title: 'Erros históricos',
        placeholder: 'Quais foram os principais erros teológicos históricos relacionados a esta doutrina? Quem os ensinou e qual foi a resposta ortodoxa?',
        aiTrigger: 'Quais foram os principais erros teológicos históricos relacionados a esta doutrina? Identifique os ensinantes, a natureza do erro e a resposta da ortodoxia cristã.',
      },
      {
        id: 'heresias_relacionadas',
        title: 'Heresias relacionadas',
        placeholder: 'Que heresias formalmente condenadas pelos concílios ecumênicos ou pelos sínodos reformados afetam esta doutrina? Que conteúdo ensinavam e por que foram rejeitadas?',
        aiTrigger: 'Que heresias relacionadas a esta doutrina foram condenadas pela Igreja histórica? Explique o conteúdo de cada uma e os fundamentos bíblicos e teológicos de sua rejeição.',
      },
      {
        id: 'visoes_concorrentes',
        title: 'Visões concorrentes',
        placeholder: 'Quais são as posições teológicas concorrentes nos dias atuais? Como diferem da posição reformada e em que pontos há concordância parcial?',
        aiTrigger: 'Quais são as principais posições teológicas concorrentes sobre esta doutrina no período contemporâneo? Como diferem da posição reformada? Onde há concordância e onde há divergência fundamental?',
      },
      {
        id: 'respostas_reformadas',
        title: 'Respostas reformadas',
        placeholder: 'Como a tradição reformada responde aos erros e às visões concorrentes? Quais são os argumentos bíblicos e teológicos que sustentam a posição ortodoxa?',
        aiTrigger: 'Como a tradição reformada — usando Berkhof, Bavinck, Murray ou Sproul — responde aos principais erros e visões concorrentes sobre esta doutrina? Quais são os argumentos bíblicos decisivos?',
      },
    ],
  },
  {
    slug: 'edt_confissionalidade',
    title: 'VI. Confissionalidade',
    shortTitle: 'Confissionalidade',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_confissionalidade_grp',
    groupLabel: 'VI. Confissionalidade',
    order: 205,
    objective:
      'Apresentar como a doutrina está formulada nos símbolos de fé reformados — Confissão de Westminster, Catecismo Maior, Catecismo Menor e outros documentos confessionais.',
    keyQuestions: [
      'Como a Confissão de Westminster trata esta doutrina?',
      'Que perguntas do Catecismo Maior abordam este ensinamento?',
      'Como o Catecismo Menor formula esta doutrina de modo memorável?',
      'Outros símbolos de fé (Heidelberg, Belgic, Cânones de Dort) contribuem de modo único?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'confissao_westminster',
        title: 'Confissão de Westminster',
        placeholder: 'Que capítulos e artigos da Confissão de Westminster tratam diretamente desta doutrina? Transcreva e comente os trechos mais relevantes.',
        aiTrigger: 'Que capítulos e artigos da Confissão de Westminster (1647) tratam diretamente desta doutrina? Transcreva e explique os trechos mais relevantes.',
      },
      {
        id: 'catecismo_maior',
        title: 'Catecismo Maior',
        placeholder: 'Que perguntas e respostas do Catecismo Maior de Westminster abordam esta doutrina? Como o Catecismo a desenvolve além da Confissão?',
        aiTrigger: 'Que perguntas do Catecismo Maior de Westminster abordam esta doutrina? Transcreva as perguntas e respostas mais relevantes e explique sua contribuição.',
      },
      {
        id: 'catecismo_menor',
        title: 'Catecismo Menor',
        placeholder: 'Como o Catecismo Menor de Westminster formula esta doutrina? Que pergunta e resposta capturam a essência de modo memorável?',
        aiTrigger: 'Como o Catecismo Menor de Westminster aborda esta doutrina? Transcreva a pergunta e resposta mais relevante e explique por que essa formulação é pedagogicamente eficaz.',
      },
      {
        id: 'outros_simbolos',
        title: 'Outros símbolos',
        placeholder: 'Como outros símbolos reformados — Catecismo de Heidelberg, Confissão Belga, Cânones de Dort, Segunda Confissão Helvética — tratam esta doutrina?',
        aiTrigger: 'Como outros símbolos de fé reformados — Catecismo de Heidelberg, Confissão Belga ou Cânones de Dort — abordam esta doutrina? Que perspectiva única cada um oferece?',
      },
    ],
  },
  {
    slug: 'edt_aplicacoes',
    title: 'VII. Aplicações',
    shortTitle: 'Aplicações',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_aplicacoes_grp',
    groupLabel: 'VII. Aplicações',
    order: 206,
    objective:
      'Desenvolver as implicações práticas da doutrina para a vida da igreja, da família, da vida cristã individual e do ministério.',
    keyQuestions: [
      'Como esta doutrina deve moldar a vida e a prática da igreja local?',
      'Que implicações concretas ela tem para a criação dos filhos e a vida familiar?',
      'Como ela transforma a vida de oração, devoção e santificação pessoal?',
      'De que modo esta doutrina informa e motiva o ministério e o serviço cristão?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'aplicacao_eclesial',
        title: 'Aplicação eclesial',
        placeholder: 'Como esta doutrina deve moldar a pregação, a adoração, os sacramentos, a disciplina e a vida comunitária da igreja?',
        aiTrigger: 'Como esta doutrina deve moldar a vida da igreja local? Explore implicações para a pregação, a adoração, os sacramentos, a disciplina eclesiástica e a comunhão dos santos.',
      },
      {
        id: 'aplicacao_familiar',
        title: 'Aplicação familiar',
        placeholder: 'Que implicações esta doutrina tem para o casamento, a criação dos filhos, a ordem doméstica e o testemunho familiar?',
        aiTrigger: 'Que implicações práticas esta doutrina tem para a vida familiar: casamento, criação de filhos, educação cristã em casa e o testemunho da família diante do mundo?',
      },
      {
        id: 'vida_crista',
        title: 'Vida cristã',
        placeholder: 'Como esta doutrina transforma a vida de oração, a mortificação, a santificação, a esperança e a perseverança do cristão individual?',
        aiTrigger: 'Como esta doutrina transforma a vida cristã individual: a oração, a mortificação do pecado, a busca da santidade, a esperança escatológica e a perseverança na fé?',
      },
      {
        id: 'ministerio',
        title: 'Ministério',
        placeholder: 'Como esta doutrina informa e motiva o ministério da Palavra, do pastoreio, da evangelização e da diaconia?',
        aiTrigger: 'Como esta doutrina informa e motiva o ministério cristão: a pregação, o pastoreio, o aconselhamento, a evangelização e o serviço diaconal?',
      },
    ],
  },
  {
    slug: 'edt_bibliografia',
    title: 'VIII. Bibliografia',
    shortTitle: 'Bibliografia',
    phase: 'interpretar',
    module: 'inventio',
    group: 'edt_bibliografia_grp',
    groupLabel: 'VIII. Bibliografia',
    order: 207,
    objective:
      'Organizar a bibliografia para o estudo doutrinário, priorizando obras primárias, secundárias e artigos que aprofundam o tema de modo confiável.',
    keyQuestions: [
      'Quais são os livros de referência indispensáveis para este estudo doutrinário?',
      'Que artigos acadêmicos ou capítulos de obras coletivas oferecem perspectivas complementares?',
      'Que fontes primárias (Pais da Igreja, Confissões, Concílios) devem ser consultadas diretamente?',
      'Há recursos em português de qualidade para este tema?',
    ],
    relevantAuthors: ['Louis Berkhof', 'Herman Bavinck', 'Wayne Grudem', 'John Murray', 'R.C. Sproul', 'Michael Horton'],
    cards: [
      {
        id: 'livros_principais',
        title: 'Livros principais',
        placeholder: 'Liste os 5 a 10 livros mais importantes para este estudo, com dados bibliográficos completos e uma anotação sobre a contribuição de cada obra.',
        aiTrigger: 'Indique os 5 a 8 livros mais importantes para o estudo desta doutrina na tradição reformada. Inclua dados bibliográficos e uma linha sobre a contribuição específica de cada obra.',
      },
      {
        id: 'artigos',
        title: 'Artigos e capítulos',
        placeholder: 'Liste artigos de revistas teológicas, capítulos de obras coletivas ou ensaios que aprofundam aspectos específicos desta doutrina.',
        aiTrigger: 'Indique artigos de revistas teológicas ou capítulos de obras coletivas relevantes para o estudo desta doutrina. Inclua publicações como Westminster Theological Journal, Themelios ou similares.',
      },
      {
        id: 'fontes_primarias',
        title: 'Fontes primárias',
        placeholder: 'Liste as fontes primárias relevantes: textos patrísticos, documentos conciliares, confissões de fé, tratados dos Reformadores.',
        aiTrigger: 'Quais são as fontes primárias mais importantes para o estudo desta doutrina? Inclua textos patrísticos, documentos conciliares, confissões de fé e tratados dos Reformadores relevantes.',
      },
    ],
  },
]
