import type { SectionDef } from './workspace-sections'

export const ESTUDO_BIBLICO_SECTIONS: SectionDef[] = [
  {
    slug: 'eb_preparacao',
    title: 'I.1 Preparação',
    shortTitle: 'Preparação',
    phase: 'preparar',
    module: 'inventio',
    group: 'eb_preparar',
    groupLabel: 'I. Preparar',
    order: 100,
    objective:
      'Estabelecer o contexto pedagógico do estudo bíblico: quem são os alunos, qual o tempo disponível e como a oração fundamenta o ensino da Palavra.',
    keyQuestions: [
      'Para quem é este estudo — qual é o perfil, a faixa etária e o nível bíblico dos participantes?',
      'Quanto tempo tenho disponível para preparação e para a aula?',
      'Qual é a motivação espiritual por trás deste estudo — o que me levou a escolher este texto?',
      'Como a oração está moldando minha abordagem do texto e dos alunos?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'oracao',
        title: 'Oração',
        placeholder: 'Registre sua oração de dependência pelo estudo. Quem são as pessoas que receberão este ensino? Que necessidades espirituais específicas você traz diante de Deus?',
        aiTrigger: 'Como um professor de estudo bíblico deve começar sua preparação em oração? Que tipos de petições específicas deveria fazer por seus alunos e pelo texto que ensinará?',
      },
      {
        id: 'publico_alvo',
        title: 'Público-alvo',
        placeholder: 'Descreva quem participará: composição do grupo, nível de maturidade bíblica, contexto de vida (jovens, casais, adultos, misto), eventuais necessidades ou tensões no grupo.',
        aiTrigger: 'Como o perfil do público-alvo deve moldar a abordagem pedagógica de um estudo bíblico? Quais ajustes de linguagem, profundidade e aplicação são necessários para diferentes grupos?',
      },
      {
        id: 'faixa_etaria',
        title: 'Faixa etária',
        placeholder: 'Qual é a faixa etária predominante? Como a etapa de vida dos participantes influencia a seleção de ilustrações, aplicações e dinâmicas?',
        aiTrigger: 'Como adaptar um estudo bíblico para diferentes faixas etárias? Quais estratégias pedagógicas funcionam melhor para cada fase da vida?',
      },
      {
        id: 'tempo_disponivel',
        title: 'Tempo disponível',
        placeholder: 'Quanto tempo tem para a aula? Como esse tempo se divide entre abertura, estudo do texto, perguntas, aplicação e encerramento?',
        aiTrigger: 'Como planejar um estudo bíblico de 45, 60 ou 90 minutos? Sugira uma distribuição eficiente de tempo para cada parte do encontro.',
      },
    ],
  },
  {
    slug: 'eb_objetivos',
    title: 'I.2 Objetivos',
    shortTitle: 'Objetivos',
    phase: 'preparar',
    module: 'inventio',
    group: 'eb_preparar',
    groupLabel: 'I. Preparar',
    order: 101,
    objective:
      'Definir o que o professor espera que os alunos saibam, creiam e façam ao final do estudo, garantindo que o ensino tenha direção clara e avaliável.',
    keyQuestions: [
      'O que os alunos devem saber ao final — que verdade bíblica precisa ser compreendida?',
      'O que os alunos devem sentir ou valorizar diferentemente?',
      'O que os alunos devem ser capazes de fazer ou decidir a partir deste estudo?',
      'Como este estudo se conecta com o que foi ensinado antes e o que virá a seguir?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'objetivos_aula',
        title: 'Objetivos da aula',
        placeholder: 'Liste de 2 a 4 objetivos específicos de aprendizagem. Use verbos mensuráveis: o aluno será capaz de identificar, explicar, aplicar, distinguir...',
        aiTrigger: 'Com base neste texto bíblico, sugira 3 objetivos de aprendizagem claros e mensuráveis para um estudo bíblico de grupo. Use verbos cognitivos, afetivos e comportamentais.',
      },
      {
        id: 'resultados_esperados',
        title: 'Resultados esperados',
        placeholder: 'Que transformação concreta você espera nos participantes após este estudo? Seja específico: em que área da vida, com que tipo de mudança?',
        aiTrigger: 'Que resultados transformacionais são realistas esperar de um estudo bíblico sobre este texto? Como o professor pode avaliar se esses resultados estão sendo alcançados?',
      },
    ],
  },
  {
    slug: 'eb_texto_base',
    title: 'II.1 Texto-Base',
    shortTitle: 'Texto-Base',
    phase: 'preparar',
    module: 'inventio',
    group: 'eb_compreender',
    groupLabel: 'II. Compreender',
    order: 102,
    objective:
      'Fazer uma leitura atenta do texto, identificando sua estrutura narrativa ou argumentativa, os personagens principais e os lugares relevantes.',
    keyQuestions: [
      'Qual é a unidade literária que será estudada — onde começa e termina?',
      'Quais são as partes ou movimentos principais do texto?',
      'Quem são os personagens ou vozes presentes, e qual o papel de cada um?',
      'Que lugares ou cenários são mencionados e como contribuem para o significado?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'leitura_texto',
        title: 'Leitura do texto',
        placeholder: 'Leia o texto em pelo menos duas versões diferentes. O que chama a atenção imediatamente? Que perguntas surgem logo na primeira leitura?',
        aiTrigger: 'Faça uma leitura inicial desta passagem destacando: qual é o contexto imediato, qual o tom predominante, e que perguntas naturais surgem para um leitor atento.',
      },
      {
        id: 'estrutura',
        title: 'Estrutura',
        placeholder: 'Divida o texto em 2 a 4 partes principais com títulos descritivos. O que une cada parte? Como elas se relacionam entre si?',
        aiTrigger: 'Divida esta passagem em suas partes ou movimentos principais, atribuindo um título descritivo a cada seção. Explique como cada parte contribui para o todo.',
      },
      {
        id: 'personagens',
        title: 'Personagens',
        placeholder: 'Identifique os personagens ou vozes presentes. Qual o papel de cada um? Há desenvolvimento de personagem ao longo do texto?',
        aiTrigger: 'Identifique os personagens desta passagem e descreva o papel de cada um: protagonistas, coadjuvantes, vozes implícitas. Como cada personagem contribui para a mensagem do texto?',
      },
      {
        id: 'lugares',
        title: 'Lugares',
        placeholder: 'Que lugares são mencionados? Há significado geográfico, histórico ou simbólico nesses lugares que o aluno precisa conhecer para entender o texto?',
        aiTrigger: 'Que lugares são mencionados nesta passagem? Qual o significado histórico, geográfico ou simbólico desses locais para a interpretação correta do texto?',
      },
    ],
  },
  {
    slug: 'eb_temas_termos',
    title: 'II.2 Temas e Termos',
    shortTitle: 'Temas e Termos',
    phase: 'preparar',
    module: 'inventio',
    group: 'eb_compreender',
    groupLabel: 'II. Compreender',
    order: 103,
    objective:
      'Identificar os temas centrais do texto, explicar os termos-chave que precisam de esclarecimento e formular a grande ideia que unifica o estudo.',
    keyQuestions: [
      'Qual é o tema principal do texto — sobre o que ele está falando essencialmente?',
      'Que termos ou conceitos exigem explicação para serem compreendidos corretamente?',
      'Se o texto pudesse ser resumido em uma frase, qual seria?',
      'Como este tema se conecta com a mensagem geral do livro e com a revelação progressiva?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'temas_principais',
        title: 'Temas principais',
        placeholder: 'Quais são os 2 ou 3 temas centrais que o texto desenvolve? Como cada tema se manifesta concretamente no texto?',
        aiTrigger: 'Identifique os 2 ou 3 temas centrais desta passagem. Para cada tema, mostre como ele se manifesta no texto e qual sua relevância para o estudo de grupo.',
      },
      {
        id: 'termos_chave',
        title: 'Termos-chave',
        placeholder: 'Liste os termos teológicos ou culturais que precisam de explicação. Para cada um, escreva uma definição clara e acessível para o grupo.',
        aiTrigger: 'Quais termos desta passagem precisam de explicação para um leitor contemporâneo? Forneça definições claras e acessíveis para cada um, adequadas para um estudo de grupo.',
      },
      {
        id: 'grande_ideia',
        title: 'Grande Ideia',
        placeholder: 'Formule a grande ideia do texto em uma frase completa: sujeito (sobre o que o texto fala) + complemento (o que o texto afirma sobre esse sujeito).\n\nGrande Ideia:',
        aiTrigger: 'Formule a grande ideia desta passagem em uma sentença completa (sujeito + complemento) adequada para guiar um estudo bíblico de grupo. Deve ser clara, bíblica e aplicável.',
      },
    ],
  },
  {
    slug: 'eb_introducao',
    title: 'III.1 Introdução',
    shortTitle: 'Introdução',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'eb_ensinar',
    groupLabel: 'III. Ensinar',
    order: 104,
    objective:
      'Criar uma abertura que capture a atenção do grupo, crie expectativa para o texto e estabeleça a conexão entre a vida dos participantes e o tema que será estudado.',
    keyQuestions: [
      'Como capturar a atenção do grupo nos primeiros minutos?',
      'Que quebra-gelo ou atividade introdutória cria um ambiente de abertura?',
      'Que ponte posso construir entre a experiência dos participantes e o texto bíblico?',
      'Como apresentar o texto de modo a despertar curiosidade genuína?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'gancho',
        title: 'Gancho',
        placeholder: 'Como o estudo começa? Uma pergunta, situação, história ou problema que imediatamente desperta o interesse do grupo pelo tema do texto.',
        aiTrigger: 'Sugira um gancho de abertura para um estudo bíblico sobre esta passagem. Deve despertar curiosidade, criar necessidade e conectar a vida cotidiana com o tema do texto.',
      },
      {
        id: 'quebra_gelo',
        title: 'Quebra-gelo',
        placeholder: 'Que atividade ou pergunta leve cria um ambiente de participação antes de entrar no texto? Deve ser relacionada ao tema sem ser profunda demais.',
        aiTrigger: 'Sugira uma atividade ou pergunta de quebra-gelo relacionada ao tema desta passagem. Deve ser leve, inclusiva e preparar o grupo para entrar no texto.',
      },
      {
        id: 'conexao_vida',
        title: 'Conexão com a vida',
        placeholder: 'Que situação da vida real (trabalho, família, relacionamentos, desafios espirituais) cria uma ponte natural entre os participantes e o texto bíblico?',
        aiTrigger: 'Como estabelecer uma conexão entre a vida cotidiana dos participantes e o tema desta passagem? Sugira situações concretas que criem relevância antes de apresentar o texto.',
      },
    ],
  },
  {
    slug: 'eb_desenvolvimento',
    title: 'III.2 Desenvolvimento',
    shortTitle: 'Desenvolvimento',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'eb_ensinar',
    groupLabel: 'III. Ensinar',
    order: 105,
    objective:
      'Estruturar o desenvolvimento do estudo em pontos claros e progressivos que levem o grupo do texto à compreensão e, da compreensão, à aplicação.',
    keyQuestions: [
      'Quais são os 2 ou 3 pontos principais que o estudo deve desenvolver?',
      'Cada ponto está ancorado no texto — os participantes podem ver isso na Bíblia?',
      'Há progressão lógica entre os pontos — eles se constroem mutuamente?',
      'As transições entre os pontos são claras e naturais?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'ponto_1',
        title: 'Ponto 1',
        placeholder: 'Enunciado do ponto 1:\n\nReferência no texto:\n\nExplicação (o que o texto diz):\n\nIlustração ou exemplo:',
        aiTrigger: 'Desenvolva o primeiro ponto principal deste estudo bíblico. Inclua: enunciado claro, referência no texto, explicação do que o texto diz e uma ilustração ou exemplo para o grupo.',
      },
      {
        id: 'ponto_2',
        title: 'Ponto 2',
        placeholder: 'Enunciado do ponto 2:\n\nReferência no texto:\n\nExplicação (o que o texto diz):\n\nIlustração ou exemplo:',
        aiTrigger: 'Desenvolva o segundo ponto principal deste estudo bíblico. Deve progredir em relação ao ponto 1. Inclua: enunciado claro, referência no texto, explicação e ilustração.',
      },
      {
        id: 'ponto_3',
        title: 'Ponto 3',
        placeholder: 'Enunciado do ponto 3 (se o texto o sustentar):\n\nReferência no texto:\n\nExplicação:\n\nIlustração:',
        aiTrigger: 'Desenvolva o terceiro ponto deste estudo bíblico, se o texto o sustentar. Inclua enunciado, referência, explicação e ilustração. Se não houver terceiro ponto natural, indique isso.',
      },
      {
        id: 'transicoes',
        title: 'Transições',
        placeholder: 'Redija as transições entre os pontos. Uma boa transição resume o que foi visto e anuncia o que vem a seguir de modo natural.',
        aiTrigger: 'Redija as transições entre os pontos deste estudo bíblico. Cada transição deve resumir o ponto anterior e conduzir naturalmente para o próximo, mantendo a coerência do ensino.',
      },
    ],
  },
  {
    slug: 'eb_perguntas',
    title: 'III.3 Perguntas',
    shortTitle: 'Perguntas',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'eb_ensinar',
    groupLabel: 'III. Ensinar',
    order: 106,
    objective:
      'Elaborar perguntas intencionais nos três níveis do método inductivo — observação, interpretação e aplicação — para guiar o grupo à descoberta pessoal do texto.',
    keyQuestions: [
      'As perguntas de observação levam o grupo ao que o texto diz literalmente?',
      'As perguntas de interpretação guiam para o que o texto significa?',
      'As perguntas de aplicação conectam o texto à vida real de modo específico?',
      'Há equilíbrio entre perguntas que têm resposta objetiva e perguntas que provocam reflexão?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'perguntas_observacao',
        title: 'Perguntas de observação',
        placeholder: 'Liste 3 a 5 perguntas que levam o grupo a olhar cuidadosamente para o texto: O que? Quem? Quando? Onde? Estas perguntas têm respostas objetivas no texto.',
        aiTrigger: 'Elabore 4 perguntas de observação para esta passagem. Devem levar o grupo a descrever o que o texto diz literalmente, usando perguntas como: O que acontece? Quem faz o quê? Que palavras se repetem?',
      },
      {
        id: 'perguntas_interpretacao',
        title: 'Perguntas de interpretação',
        placeholder: 'Liste 3 a 5 perguntas que levam o grupo a descobrir o significado do texto: Por quê? O que isso significa? Como isso se relaciona com...?',
        aiTrigger: 'Elabore 4 perguntas de interpretação para esta passagem. Devem guiar o grupo a descobrir o significado, usando perguntas como: Por que o autor diz isso? O que esse termo significa? Como este versículo se relaciona com o anterior?',
      },
      {
        id: 'perguntas_aplicacao',
        title: 'Perguntas de aplicação',
        placeholder: 'Liste 3 a 5 perguntas que conectam o texto à vida real: O que isso significa para mim? O que preciso mudar? Como vivo isso?',
        aiTrigger: 'Elabore 4 perguntas de aplicação para esta passagem. Devem ser específicas e pessoais, conectando o texto à vida real: O que isso exige de você? Em que área da sua vida este texto fala diretamente?',
      },
    ],
  },
  {
    slug: 'eb_dinamicas',
    title: 'III.4 Dinâmicas',
    shortTitle: 'Dinâmicas',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'eb_ensinar',
    groupLabel: 'III. Ensinar',
    order: 107,
    objective:
      'Planejar exercícios práticos, momentos de discussão em grupo e uma síntese que consolide o aprendizado e promova a participação ativa.',
    keyQuestions: [
      'Que exercício ou atividade prátic ajuda os participantes a fixar a verdade do texto?',
      'Como estruturar a discussão em grupo de modo que todos participem e o professor não domine?',
      'Como sintetizar o estudo de modo memorável ao final?',
      'O tempo das dinâmicas está proporcionalmente alocado no plano da aula?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'exercicios',
        title: 'Exercícios',
        placeholder: 'Descreva uma ou duas atividades práticas: leitura em voz alta, completar lacunas, mapear o texto, sublinhar palavras-chave, etc.',
        aiTrigger: 'Sugira 2 exercícios práticos para este estudo bíblico que ajudem os participantes a se engajar ativamente com o texto. Devem ser simples, realizáveis no tempo disponível e conectados ao objetivo da aula.',
      },
      {
        id: 'discussao_grupo',
        title: 'Discussão em grupo',
        placeholder: 'Como estruturar a discussão? Grupos pequenos, duplas ou plenária? Que pergunta central orienta a discussão? Como trazer as respostas para o grupo maior?',
        aiTrigger: 'Como estruturar um momento de discussão em grupo sobre esta passagem? Sugira a formação dos grupos, a pergunta central da discussão e como retomar as contribuições na plenária.',
      },
      {
        id: 'sintese',
        title: 'Síntese',
        placeholder: 'Como encerrar o estudo de modo memorável? Uma frase, uma oração, um compromisso, uma imagem que resuma a grande ideia.',
        aiTrigger: 'Como encerrar este estudo bíblico de modo memorável? Sugira uma síntese criativa — uma frase, imagem, oração ou compromisso — que deixe a grande ideia gravada nos participantes.',
      },
    ],
  },
  {
    slug: 'eb_aplicacoes',
    title: 'IV. Aplicações',
    shortTitle: 'Aplicações',
    phase: 'comunicar',
    module: 'elocutio',
    group: 'eb_aplicar',
    groupLabel: 'IV. Aplicar',
    order: 108,
    objective:
      'Desenvolver aplicações concretas do texto nas quatro dimensões da vida cristã: individual, familiar, eclesiástica e missional.',
    keyQuestions: [
      'Como esta verdade transforma a vida pessoal e devoção individual?',
      'Que implicações práticas o texto tem para a vida familiar e conjugal?',
      'Como este ensino edifica a vida comunitária da igreja local?',
      'De que modo este texto impulsiona o testemunho e a missão?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'aplicacoes_individuais',
        title: 'Aplicações individuais',
        placeholder: 'Que mudança concreta este texto exige na vida pessoal, na devoção, nas atitudes ou nos pensamentos de cada participante?',
        aiTrigger: 'Desenvolva 2 a 3 aplicações individuais desta passagem. Devem ser específicas, pessoais e alcançáveis, cobrindo dimensões como devoção, atitudes, pensamentos ou decisões práticas.',
      },
      {
        id: 'aplicacoes_familiares',
        title: 'Aplicações familiares',
        placeholder: 'Como este texto fala para a vida conjugal, a criação dos filhos, os relacionamentos familiares ou a vida doméstica?',
        aiTrigger: 'Desenvolva 2 aplicações desta passagem para a vida familiar. Como este texto fala para casamentos, criação de filhos, relacionamentos entre irmãos ou a dinâmica da casa?',
      },
      {
        id: 'aplicacoes_eclesiasticas',
        title: 'Aplicações eclesiásticas',
        placeholder: 'Como este texto edifica a vida comunitária da igreja? O que exige da liderança, dos membros, da adoração ou do cuidado mútuo?',
        aiTrigger: 'Desenvolva 2 aplicações desta passagem para a vida da igreja local. Como este texto molda a comunidade, a liderança, a adoração, o cuidado pastoral ou a vida mútua?',
      },
      {
        id: 'aplicacoes_missionais',
        title: 'Aplicações missionais',
        placeholder: 'Como este texto impulsiona o testemunho, a evangelização, o serviço ao próximo ou o engajamento com o mundo?',
        aiTrigger: 'Desenvolva 2 aplicações missionais desta passagem. Como este texto motiva o testemunho, a evangelização, o serviço ao próximo ou o engajamento com a cultura e o mundo?',
      },
    ],
  },
  {
    slug: 'eb_material',
    title: 'V. Material',
    shortTitle: 'Material',
    phase: 'comunicar',
    module: 'memoria',
    group: 'eb_recursos',
    groupLabel: 'V. Recursos',
    order: 109,
    objective:
      'Preparar o material de suporte para o professor e para os alunos, garantindo que o ensino seja bem documentado e de fácil uso.',
    keyQuestions: [
      'Que material o professor precisa ter em mãos durante o estudo?',
      'Que material os alunos receberão para acompanhar e aprofundar o estudo?',
      'Há slides ou handout que apoiam visualmente o ensino sem substituir a Bíblia?',
      'O material está adequado ao nível de escolaridade e ao tempo do grupo?',
    ],
    relevantAuthors: ['Howard Hendricks', 'Robert Stein', 'Grant Osborne', 'Graeme Goldsworthy', 'John Stott'],
    cards: [
      {
        id: 'material_professor',
        title: 'Material do professor',
        placeholder: 'Esboço completo da aula com: objetivos, pontos, perguntas, transições e respostas esperadas. O que o professor precisa ter diante dos olhos na hora de ensinar.',
        aiTrigger: 'Produza um esboço completo de aula para o professor com base nesta passagem. Inclua: objetivos, pontos principais, perguntas para cada etapa, transições e observações sobre o tempo.',
      },
      {
        id: 'material_aluno',
        title: 'Material do aluno',
        placeholder: 'Folha de estudo para o aluno: texto bíblico, perguntas para reflexão, espaço para anotações e uma aplicação pessoal para a semana.',
        aiTrigger: 'Crie uma folha de estudo para os alunos com: texto bíblico da passagem, 4 perguntas de reflexão progressivas, espaço para anotações e uma aplicação prática para a semana.',
      },
      {
        id: 'slides_handout',
        title: 'Slides / Handout',
        placeholder: 'Estrutura dos slides ou handout visual: título, texto principal, pontos-chave, grande ideia, versículo para memorizar.',
        aiTrigger: 'Crie a estrutura de um handout visual para este estudo bíblico. Deve incluir: título, texto bíblico de referência, pontos principais, grande ideia do texto e versículo para memorizar.',
      },
    ],
  },
]
