import type { SectionDef } from './workspace-sections'

export const PESQUISA_TEOLOGICA_SECTIONS: SectionDef[] = [
  {
    slug: 'pt_tema',
    title: 'I. Tema e Problema',
    shortTitle: 'Tema e Problema',
    phase: 'preparar',
    module: 'inventio',
    group: 'pt_tema_grp',
    groupLabel: 'I. Tema e Problema',
    order: 300,
    objective:
      'Delimitar com precisão o tema da pesquisa, formular o problema investigativo, estabelecer os limites do trabalho e justificar sua relevância.',
    keyQuestions: [
      'Qual é o tema específico que esta pesquisa investiga?',
      'Qual é o problema ou lacuna que justifica esta pesquisa?',
      'Quais são os limites temporais, canônicos, temáticos ou históricos do trabalho?',
      'Por que esta pesquisa é relevante para a teologia, para a igreja ou para a academia?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'tema',
        title: 'Tema',
        placeholder: 'Enuncie o tema da pesquisa com precisão. Deve ser específico o suficiente para ser investigável em profundidade, sem ser tão restrito que careça de relevância.',
        aiTrigger: 'Ajude a formular o tema desta pesquisa teológica. O tema deve ser específico, investigável e relevante. Ofereça 3 alternativas de formulação com diferentes níveis de especificidade.',
      },
      {
        id: 'problema_pesquisa',
        title: 'Problema da pesquisa',
        placeholder: 'Qual é o problema, a lacuna ou a questão que esta pesquisa se propõe a investigar? Por que esse problema existe e por que ainda não foi resolvido satisfatoriamente?',
        aiTrigger: 'Ajude a formular o problema desta pesquisa teológica: qual é a lacuna no conhecimento existente, a tensão não resolvida ou a questão que justifica este trabalho?',
      },
      {
        id: 'delimitacao',
        title: 'Delimitação',
        placeholder: 'Quais são os limites desta pesquisa? Que aspectos do tema estão dentro e quais estão fora do escopo? Delimite pelo cânone, pelo período histórico ou pelo corpus estudado.',
        aiTrigger: 'Ajude a delimitar o escopo desta pesquisa teológica. Que aspectos estão dentro e fora do escopo? Como justificar as limitações escolhidas sem comprometer a relevância?',
      },
      {
        id: 'justificativa',
        title: 'Justificativa',
        placeholder: 'Por que esta pesquisa é necessária e relevante? Que contribuição ela oferece à teologia, à igreja ou à academia? Qual é o estado atual do debate que torna esta pesquisa oportuna?',
        aiTrigger: 'Ajude a formular a justificativa desta pesquisa teológica. Por que ela é necessária agora? Que contribuição oferece? Como se insere no debate acadêmico e na necessidade da igreja?',
      },
    ],
  },
  {
    slug: 'pt_hipotese',
    title: 'II. Hipótese',
    shortTitle: 'Hipótese',
    phase: 'preparar',
    module: 'inventio',
    group: 'pt_hipotese_grp',
    groupLabel: 'II. Hipótese',
    order: 301,
    objective:
      'Formular a questão principal de pesquisa, as hipóteses de trabalho e a metodologia que guiará a investigação.',
    keyQuestions: [
      'Qual é a questão principal que esta pesquisa busca responder?',
      'Que hipóteses de trabalho guiam a investigação?',
      'Que método — histórico-gramatical, teológico-bíblico, sistemático — será empregado?',
      'As hipóteses são verificáveis a partir das fontes disponíveis?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'questao_principal',
        title: 'Questão principal',
        placeholder: 'Formule a questão principal de pesquisa em uma frase. Deve ser investigável, específica e orientar toda a estrutura do trabalho.',
        aiTrigger: 'Ajude a formular a questão principal desta pesquisa teológica. Deve ser específica, investigável, e suficientemente abrangente para justificar um trabalho de fôlego.',
      },
      {
        id: 'hipoteses',
        title: 'Hipóteses',
        placeholder: 'Formule 2 a 3 hipóteses de trabalho. Cada hipótese é uma resposta provisória que a pesquisa testará com as evidências.',
        aiTrigger: 'Ajude a formular hipóteses de trabalho para esta pesquisa teológica. Cada hipótese deve ser uma resposta provisória à questão principal, verificável a partir das fontes.',
      },
      {
        id: 'metodologia',
        title: 'Metodologia',
        placeholder: 'Que abordagem metodológica será usada: histórico-gramatical, teológico-bíblica, sistemática, histórico-teológica, ou combinação? Como os dados serão coletados e analisados?',
        aiTrigger: 'Qual é a metodologia mais adequada para esta pesquisa teológica? Explique as abordagens disponíveis — histórico-gramatical, teológico-bíblica, sistemática — e justifique a escolha.',
      },
    ],
  },
  {
    slug: 'pt_revisao_bibliografica',
    title: 'III. Revisão Bibliográfica',
    shortTitle: 'Revisão Bibliográfica',
    phase: 'preparar',
    module: 'inventio',
    group: 'pt_revisao_grp',
    groupLabel: 'III. Revisão Bibliográfica',
    order: 302,
    objective:
      'Mapear o estado da arte da pesquisa sobre o tema, identificar os autores principais, as obras centrais e os debates acadêmicos relevantes.',
    keyQuestions: [
      'O que já foi pesquisado sobre este tema?',
      'Quais são os autores que mais contribuíram para este campo?',
      'Que obras são indispensáveis para compreender o estado atual do debate?',
      'Que lacunas ou debates em aberto justificam esta pesquisa?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'estado_da_arte',
        title: 'Estado da arte',
        placeholder: 'Descreva o estado atual da pesquisa sobre este tema: o que já foi feito, que consensos existem, que lacunas permanecem. Base para justificar a contribuição deste trabalho.',
        aiTrigger: 'Apresente o estado da arte da pesquisa sobre este tema teológico. Que trabalhos fundamentais já foram realizados? Que consensos emergiram? Que questões permanecem em aberto?',
      },
      {
        id: 'autores_principais',
        title: 'Autores principais',
        placeholder: 'Liste os pesquisadores que mais contribuíram para este campo. Para cada um: posição teológica, obras principais e contribuição específica ao debate.',
        aiTrigger: 'Quem são os principais pesquisadores neste campo teológico? Para cada autor, indique sua posição teológica, suas obras mais relevantes e sua contribuição específica ao debate.',
      },
      {
        id: 'obras_centrais',
        title: 'Obras centrais',
        placeholder: 'Liste as obras que são referência obrigatória para este tema. Para cada uma: dados bibliográficos, tese principal e por que é imprescindível.',
        aiTrigger: 'Quais são as obras mais importantes e indispensáveis para o estudo deste tema? Forneça dados bibliográficos e uma linha sobre a tese e relevância de cada obra.',
      },
      {
        id: 'debates_academicos',
        title: 'Debates acadêmicos',
        placeholder: 'Quais são os principais pontos de tensão ou debate no campo? Que questões permanecem controvertidas e como os principais autores se posicionam?',
        aiTrigger: 'Quais são os principais debates acadêmicos sobre este tema? Como os principais pesquisadores se posicionam? Quais são as questões mais controvertidas e por que permanecem em debate?',
      },
    ],
  },
  {
    slug: 'pt_exegese',
    title: 'IV. Exegese',
    shortTitle: 'Exegese',
    phase: 'preparar',
    module: 'inventio',
    group: 'pt_exegese_grp',
    groupLabel: 'IV. Exegese',
    order: 303,
    objective:
      'Realizar a análise exegética das passagens relevantes para a pesquisa, incluindo análise textual e morfossintática dos textos centrais.',
    keyQuestions: [
      'Quais são as passagens bíblicas mais relevantes para a questão da pesquisa?',
      'Como a análise textual apoia ou desafia as hipóteses de trabalho?',
      'Que dados morfossintáticos são decisivos para o argumento?',
      'Como as passagens analisadas se relacionam entre si no argumento bíblico?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'passagens_relevantes',
        title: 'Passagens relevantes',
        placeholder: 'Liste as passagens bíblicas que serão analisadas exegeticamente. Justifique a seleção: por que estas passagens são centrais para a questão da pesquisa?',
        aiTrigger: 'Quais são as passagens bíblicas mais relevantes para esta pesquisa teológica? Justifique a seleção de cada passagem e explique como ela contribui para a investigação.',
      },
      {
        id: 'analise_textual',
        title: 'Análise textual',
        placeholder: 'Analise cada passagem selecionada em seu contexto imediato: delimitação, estrutura, termos-chave e relação com o contexto mais amplo do livro.',
        aiTrigger: 'Realize a análise textual das passagens selecionadas: delimitação, estrutura, termos-chave e contribuição de cada passagem para a questão central da pesquisa.',
      },
      {
        id: 'analise_morfossintatica',
        title: 'Análise morfossintática',
        placeholder: 'Que dados gramaticais são decisivos para a interpretação? Analise os termos e construções que têm maior peso para o argumento da pesquisa.',
        aiTrigger: 'Identifique os dados morfossintáticos mais relevantes nas passagens selecionadas. Que construções gramaticais ou usos de termos são decisivos para o argumento desta pesquisa?',
      },
    ],
  },
  {
    slug: 'pt_teologia_biblica',
    title: 'V. Teologia Bíblica',
    shortTitle: 'Teologia Bíblica',
    phase: 'preparar',
    module: 'inventio',
    group: 'pt_tb_grp',
    groupLabel: 'V. Teologia Bíblica',
    order: 304,
    objective:
      'Situar o tema na história da redenção, examinar seu desenvolvimento canônico e identificar as conexões tipológicas relevantes.',
    keyQuestions: [
      'Como o tema se desenvolve ao longo do cânone bíblico?',
      'Que papel a história da redenção desempenha na compreensão do tema?',
      'Há tipos ou antecipações no AT que lançam luz sobre o desenvolvimento neotestamentário?',
      'Como a teologia bíblica de Vos ou Goldsworthy enquadra este tema?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'desenvolvimento_canonico',
        title: 'Desenvolvimento canônico',
        placeholder: 'Como o tema se desenvolve ao longo do cânone? Que textos, temas e instituições marcam os estágios do desenvolvimento revelacional?',
        aiTrigger: 'Trace o desenvolvimento canônico deste tema teológico: como ele aparece, se desenvolve e é clarificado ao longo do AT e do NT, segundo a teologia bíblica de Vos ou Goldsworthy.',
      },
      {
        id: 'historia_redencao',
        title: 'História da redenção',
        placeholder: 'Como a história da redenção (criação, queda, redenção, consumação) enquadra este tema? Em que ponto da história redentora o tema atinge sua maior clareza?',
        aiTrigger: 'Como a estrutura da história da redenção (criação, queda, redenção, consumação) enquadra e ilumina este tema? Em que ponto o tema atinge sua expressão mais plena?',
      },
      {
        id: 'tipologia',
        title: 'Tipologia',
        placeholder: 'Há tipos no AT que apontam ou prefiguram o tema em sua forma neotestamentária? Como o antítipo clarifica, aprofunda ou supera o tipo?',
        aiTrigger: 'Que tipos veterotestamentários são relevantes para este tema? Como cada tipo prefigura o antítipo neotestamentário? Use Beale, Vos ou Clowney como referência tipológica.',
      },
    ],
  },
  {
    slug: 'pt_teologia_sistematica',
    title: 'VI. Teologia Sistemática',
    shortTitle: 'Teologia Sistemática',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'pt_ts_grp',
    groupLabel: 'VI. Teologia Sistemática',
    order: 305,
    objective:
      'Articular a formulação doutrinária do tema, localizar nos loci clássicos da dogmática e desenvolver as implicações sistemáticas.',
    keyQuestions: [
      'Como o tema se formula doutrinariamente na teologia sistemática?',
      'Em que loci clássicos (Teologia Própria, Cristologia, Soteriologia, etc.) o tema se situa?',
      'Que implicações sistemáticas derivam das conclusões exegéticas e bíblico-teológicas?',
      'Como a formulação sistemática integra os dados exegéticos de modo coerente?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'formulacao_doutrinaria',
        title: 'Formulação doutrinária',
        placeholder: 'Como o tema é formulado na teologia sistemática? Apresente a proposição doutrinária que sintetiza as descobertas exegéticas e bíblico-teológicas.',
        aiTrigger: 'Formule a proposição doutrinária que sintetiza as descobertas desta pesquisa teológica. Use a linguagem da teologia sistemática reformada, integrando os dados exegéticos e bíblico-teológicos.',
      },
      {
        id: 'loci_classicos',
        title: 'Loci clássicos',
        placeholder: 'Em que loci da teologia sistemática o tema se localiza? Como ele se relaciona com a Teologia Própria, a Cristologia, a Pneumatologia, a Soteriologia ou a Eclesiologia?',
        aiTrigger: 'Em que loci clássicos da teologia sistemática este tema se situa? Como ele se relaciona com a Teologia Própria, a Cristologia, a Soteriologia ou outros loci? Cite Berkhof ou Bavinck.',
      },
      {
        id: 'implicacoes',
        title: 'Implicações sistemáticas',
        placeholder: 'Que implicações sistemáticas derivam das conclusões desta pesquisa? O que elas exigem que afirmemos ou neguemos em outros loci?',
        aiTrigger: 'Que implicações sistemáticas derivam das conclusões desta pesquisa? Como elas afetam outras doutrinas? O que a pesquisa exige que seja afirmado, negado ou matizado no sistema teológico?',
      },
    ],
  },
  {
    slug: 'pt_interacao_autores',
    title: 'VII. Interação com Autores',
    shortTitle: 'Interação com Autores',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'pt_interacao_grp',
    groupLabel: 'VII. Interação com Autores',
    order: 306,
    objective:
      'Dialogar criticamente com os principais autores do campo: identificar pontos de concordância, divergências fundamentadas e oferecer avaliação crítica.',
    keyQuestions: [
      'Em que pontos a pesquisa concorda com os autores principais?',
      'Onde há divergências e como elas são fundamentadas?',
      'Como avaliar criticamente as contribuições dos autores consultados?',
      'A interação é justa — os autores são apresentados em seus próprios termos?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'concordancias',
        title: 'Concordâncias',
        placeholder: 'Em que pontos esta pesquisa concorda com os autores principais? Identifique as contribuições positivas de cada autor que são incorporadas ao argumento.',
        aiTrigger: 'Identifique os pontos de concordância entre esta pesquisa e os autores principais do campo. Quais contribuições positivas de cada autor são incorporadas ao argumento da pesquisa?',
      },
      {
        id: 'divergencias',
        title: 'Divergências',
        placeholder: 'Onde esta pesquisa diverge dos autores consultados? Que argumentos exegéticos ou sistemáticos fundamentam as divergências?',
        aiTrigger: 'Onde esta pesquisa diverge dos autores consultados? Apresente as divergências com precisão e fundamente-as com argumentos exegéticos, bíblico-teológicos ou sistemáticos.',
      },
      {
        id: 'avaliacao_critica',
        title: 'Avaliação crítica',
        placeholder: 'Ofereça uma avaliação crítica equilibrada dos principais autores: que contribuições têm valor duradouro? Que limitações ou erros precisam ser sinalizados?',
        aiTrigger: 'Ofereça uma avaliação crítica equilibrada dos principais autores consultados. Quais contribuições têm valor duradouro? Que limitações, omissões ou erros precisam ser indicados com clareza?',
      },
    ],
  },
  {
    slug: 'pt_conclusoes',
    title: 'VIII. Conclusões',
    shortTitle: 'Conclusões',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'pt_conclusoes_grp',
    groupLabel: 'VIII. Conclusões',
    order: 307,
    objective:
      'Apresentar as respostas à questão principal de pesquisa, as implicações teológicas das conclusões e a contribuição original do trabalho.',
    keyQuestions: [
      'As hipóteses de trabalho foram confirmadas, refutadas ou modificadas?',
      'Qual é a resposta definitiva à questão principal da pesquisa?',
      'Que implicações teológicas derivam dessas conclusões?',
      'Qual é a contribuição original deste trabalho para o campo?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'respostas_questao',
        title: 'Respostas à questão',
        placeholder: 'Responda diretamente à questão principal de pesquisa. As hipóteses foram confirmadas, refutadas ou modificadas? Que evidências sustentam a resposta?',
        aiTrigger: 'Ajude a formular a resposta à questão principal desta pesquisa. As hipóteses foram confirmadas, refutadas ou modificadas pelas evidências? Articule a resposta de modo claro e fundamentado.',
      },
      {
        id: 'implicacoes_teologicas',
        title: 'Implicações teológicas',
        placeholder: 'Que implicações teológicas derivam das conclusões? O que elas exigem que a teologia sistemática afirme, negue ou revise?',
        aiTrigger: 'Que implicações teológicas derivam das conclusões desta pesquisa? Para quais loci da dogmática essas conclusões têm maior relevância? O que exigem que seja afirmado ou revisado?',
      },
      {
        id: 'contribuicao_original',
        title: 'Contribuição original',
        placeholder: 'Qual é a contribuição original e específica deste trabalho? O que ele acrescenta ao que já existe no campo? Que novas perspectivas, argumentos ou sínteses oferece?',
        aiTrigger: 'Qual é a contribuição original deste trabalho para o campo teológico? Que novas perspectivas, argumentos ou sínteses ele oferece que ainda não existiam na literatura disponível?',
      },
    ],
  },
  {
    slug: 'pt_referencias',
    title: 'IX. Referências',
    shortTitle: 'Referências',
    phase: 'comunicar',
    module: 'dispositio',
    group: 'pt_referencias_grp',
    groupLabel: 'IX. Referências',
    order: 308,
    objective:
      'Organizar as referências bibliográficas completas segundo as normas ABNT ou Chicago, separando fontes primárias e secundárias.',
    keyQuestions: [
      'As referências estão formatadas corretamente segundo as normas exigidas?',
      'As fontes primárias (Escritura, Pais da Igreja, Confissões) estão listadas separadamente?',
      'As fontes secundárias estão completas e verificáveis?',
      'Há consistência no sistema de citação usado ao longo do trabalho?',
    ],
    relevantAuthors: ['Geerhardus Vos', 'Herman Ridderbos', 'D.A. Carson', 'N.T. Wright', 'Michael Horton', 'Richard Bauckham'],
    cards: [
      {
        id: 'abnt_chicago',
        title: 'ABNT / Chicago',
        placeholder: 'Liste as referências completas no formato exigido (ABNT ou Chicago). Verifique a consistência: todos os itens citados no texto devem aparecer aqui.',
        aiTrigger: 'Formate as referências desta pesquisa segundo as normas ABNT ou Chicago. Inclua livros, artigos de periódico, capítulos de obra coletiva e fontes online com todos os dados necessários.',
      },
      {
        id: 'fontes_primarias',
        title: 'Fontes primárias',
        placeholder: 'Liste as fontes primárias consultadas: texto bíblico (edições críticas), Pais da Igreja, Confissões de Fé, Concílios, obras dos Reformadores.',
        aiTrigger: 'Liste as fontes primárias desta pesquisa: edições críticas do texto bíblico (BHS, NA28), textos patrísticos (Migne, NPNF), Confissões de Fé e obras dos Reformadores com dados bibliográficos completos.',
      },
      {
        id: 'fontes_secundarias',
        title: 'Fontes secundárias',
        placeholder: 'Liste as fontes secundárias (livros, artigos, teses, comentários) em ordem alfabética pelo sobrenome do autor, com dados bibliográficos completos.',
        aiTrigger: 'Organize as fontes secundárias desta pesquisa em ordem alfabética. Inclua monografias, artigos de periódico, comentários exegéticos e teses, com todos os dados bibliográficos necessários.',
      },
    ],
  },
]
