import type { SectionDef } from './workspace-sections'

function card(id: string, title: string, placeholder: string, aiTrigger: string) {
  return { id, title, placeholder, aiTrigger }
}

export const PREPARE_SECTIONS: SectionDef[] = [
  {
    slug: 'preparacao_espiritual',
    title: '1. Preparação Espiritual',
    shortTitle: 'Preparação Espiritual',
    phase: 'preparar',
    module: 'inventio',
    group: 'preparar_espiritual',
    groupLabel: 'Piedade, planejamento e oração',
    order: -40,
    objective:
      'Iniciar o estudo de modo reverente e pastoral, permitindo que o texto forme o coração do intérprete antes que ele comece a analisá-lo tecnicamente.',
    keyQuestions: [
      'Como este texto chama você à dependência e adoração?',
      'Por que você está estudando esta passagem agora?',
      'Que necessidade pastoral está diante de você e da congregação?',
      'Qual é o contexto de comunicação e o perfil do público?',
    ],
    relevantAuthors: ['João Calvino', 'John Owen', 'Martyn Lloyd-Jones', 'John Stott', 'Sinclair Ferguson'],
    cards: [
      card('preparar_oracao', 'Oração', 'Escreva uma oração honesta diante de Deus antes de estudar. Inclua: dependência de Deus, adoração, confissão, pedidos específicos, temor santo e disposição para ouvir a Palavra.', 'Conduza-me em uma oração pastoral e reverente antes de estudar esta passagem, sem tecnicismo, com foco em dependência, adoração, confissão e temor de Deus.'),
      card('preparar_objetivo_estudo', 'Objetivo do estudo', 'Por que você está estudando esta passagem agora? (Sermão / Aula / Devocional / Aconselhamento / Crescimento pessoal / Outro). Que fruto pastoral espera desse processo?', 'Ajude-me a formular um objetivo claro e pastoral para o estudo desta passagem, considerando a ocasião e o fruto esperado.'),
      card('preparar_ocasiiao_publico', 'Ocasião e público', 'Descreva o contexto de comunicação, o perfil dos ouvintes e o ambiente ministerial: série, culto, grupo, contexto, necessidade dominante.', 'Ajude-me a descrever a ocasião, o perfil do público e o ambiente ministerial relacionados a esta passagem.'),
    ],
  },
  {
    slug: 'preparar_leia_assimile',
    title: '2. Leia e Assimile a Ideia do Texto',
    shortTitle: 'Leia e Assimile',
    phase: 'preparar',
    module: 'inventio',
    group: 'preparar_assimilacao',
    groupLabel: 'Contato direto com a Escritura',
    order: -39,
    objective:
      'Absorver o texto antes da análise formal, por meio de leitura lenta, repetida, em voz alta e comparada, buscando ouvir a passagem como Escritura viva.',
    keyQuestions: [
      'O que mais chamou sua atenção na primeira leitura?',
      'Qual parece ser a ideia central antes de qualquer comentário técnico?',
      'Que repetições, tensões, emoções ou movimentos aparecem?',
      'O que o autor parece querer produzir no leitor ou ouvinte?',
    ],
    relevantAuthors: ['Eugene Peterson', 'John Stott', 'Gordon Fee', 'Douglas Stuart'],
    cards: [
      card('preparar_leitura_lenta', 'Leitura', 'Registre o que percebeu no primeiro contato com o texto. O que ficou mais evidente? Que palavras, emoções ou imagens chamaram atenção?', 'Guie-me em uma leitura lenta e reverente desta passagem, priorizando observação simples antes de qualquer análise técnica.'),
      card('preparar_comparacao_traducoes', 'Comparação', 'Compare traduções em português e registre diferenças que chamam atenção, sem ainda resolver tecnicamente todos os detalhes.', 'Ajude-me a comparar traduções desta passagem em nível inicial, observando diferenças relevantes sem aprofundar gramática ainda.'),
      card('preparar_ideia_inicial', 'Ideia Central', 'Escreva, em linguagem provisória, qual parece ser a ideia central da passagem neste primeiro contato.', 'Ajude-me a formular uma ideia central inicial e provisória para esta passagem, sem fechar a exegese cedo demais.'),
      card('preparar_tensoes_repeticoes', 'Tensões', 'Liste tensões, contrastes, palavras repetidas, emoções dominantes e movimentos aparentes do texto.', 'Faça perguntas de observação inicial sobre tensões, repetições, emoções e movimentos desta passagem.'),
    ],
  },
  {
    slug: 'preparar_primeiras_impressoes',
    title: '3. Primeiras Impressões',
    shortTitle: 'Primeiras Impressões',
    phase: 'preparar',
    module: 'inventio',
    group: 'preparar_impressoes',
    groupLabel: 'Notas rápidas e perguntas',
    order: -38,
    objective:
      'Criar um espaço livre para registrar observações, perguntas, dificuldades, conexões e marcações antes da pesquisa acadêmica.',
    keyQuestions: [
      'Que perguntas você ainda não consegue responder?',
      'Que conexão inicial parece importante, mas precisa ser testada?',
      'Que dificuldade textual, pastoral ou espiritual apareceu?',
      'Que marcações ou destaques merecem voltar depois?',
    ],
    relevantAuthors: ['Haddon Robinson', 'John Stott', 'Bryan Chapell'],
    cards: [
      card('preparar_observacoes_livres', 'Observações livres', 'Anote impressões, detalhes, surpresas, dúvidas e percepções iniciais sem censurar ou organizar demais.', 'Ajude-me a transformar minhas primeiras observações em perguntas úteis para a próxima etapa de estudo.'),
      card('preparar_perguntas_dificuldades', 'Perguntas e dificuldades', 'Liste perguntas abertas, dificuldades interpretativas, termos obscuros e pontos que exigirão pesquisa posterior.', 'Organize minhas dúvidas iniciais em categorias: texto, contexto, teologia, aplicação e comunicação.'),
      card('preparar_conexoes_iniciais', 'Conexões iniciais', 'Registre conexões com outros textos bíblicos, temas teológicos, experiências pastorais ou necessidades da igreja.', 'Sugira conexões iniciais e cuidadosas entre esta passagem, temas bíblicos e necessidades pastorais.'),
      card('preparar_marcacoes', 'Marcações e destaques', 'Registre palavras, frases, movimentos ou imagens que você destacaria no texto durante a imersão.', 'Ajude-me a identificar marcações iniciais no texto: repetições, contrastes, imagens, mudanças de cena e ênfases.'),
      card('preparar_modo_imersao', 'Modo Imersão', 'Use este espaço como tela limpa: copie o texto bíblico, escreva notas rápidas, destaques e marcações sem comentários acadêmicos.', 'Conduza um modo imersão nesta passagem: apenas observação, contemplação, perguntas e marcações iniciais.'),
    ],
  },
  {
    slug: 'preparar_visao_geral',
    title: '4. Visão Geral da Passagem',
    shortTitle: 'Visão Geral',
    phase: 'preparar',
    module: 'inventio',
    group: 'preparar_visao_geral',
    groupLabel: 'Assimilação macro',
    order: -37,
    objective:
      'Perceber a passagem em sua totalidade antes da microanálise, identificando tema provável, movimento, estrutura, personagens, clímax e fluxo.',
    keyQuestions: [
      'Qual é o tema provável da passagem?',
      'Que estrutura você percebe antes de consultar comentários?',
      'Qual é o movimento narrativo ou fluxo argumentativo?',
      'Onde parece estar o clímax ou centro de gravidade do texto?',
    ],
    relevantAuthors: ['Grant Osborne', 'Gordon Fee', 'Douglas Stuart', 'Sidney Greidanus'],
    cards: [
      card('preparar_tema_provavel', 'Tema provável', 'Nomeie o tema provável da passagem em uma frase simples e provisória.', 'Ajude-me a formular um tema provável para esta passagem, mantendo caráter provisório e observacional.'),
      card('preparar_grande_ideia_inicial', 'Grande ideia inicial', 'Escreva uma primeira hipótese da grande ideia do texto, antes da exegese formal.', 'Ajude-me a formular uma grande ideia inicial da passagem, deixando claro o que ainda precisa ser confirmado.'),
      card('preparar_estrutura_percebida', 'Estrutura percebida', 'Esboce as partes da passagem como você as percebe neste momento inicial.', 'Ajude-me a perceber uma estrutura inicial da passagem com base em movimentos visíveis do texto.'),
      card('preparar_personagens', 'Personagens', 'Liste personagens, vozes, grupos, agentes ou participantes relevantes no texto.', 'Ajude-me a observar personagens, vozes e agentes da passagem sem antecipar conclusões técnicas.'),
      card('preparar_movimento_narrativo', 'Movimento narrativo', 'Para narrativas, descreva cenas, tensão, virada, clímax e resolução percebidos.', 'Ajude-me a observar o movimento narrativo desta passagem em nível macro.'),
      card('preparar_fluxo_argumentativo', 'Fluxo argumentativo', 'Para discursos ou epístolas, descreva como o pensamento parece progredir.', 'Ajude-me a observar o fluxo argumentativo desta passagem sem entrar ainda em análise sintática pesada.'),
      card('preparar_climax', 'Clímax', 'Indique onde o texto parece atingir seu ponto de maior peso ou virada.', 'Ajude-me a identificar o possível clímax desta passagem a partir de observações iniciais.'),
      card('preparar_palavras_repetidas', 'Palavras repetidas', 'Liste palavras, expressões, imagens ou ideias recorrentes.', 'Ajude-me a observar palavras repetidas e temas recorrentes na passagem.'),
    ],
  },
  {
    slug: 'investigar_visao_geral',
    title: 'Visão Geral Investigativa',
    shortTitle: 'Visão Geral',
    phase: 'interpretar',
    module: 'inventio',
    group: 'investigar_visao_geral',
    groupLabel: 'Compreensão refinada após investigação',
    order: -20,
    objective:
      'Registrar a compreensão refinada após a investigação textual, contextual e teológica — corrigindo hipóteses iniciais e aprofundando a leitura da passagem.',
    keyQuestions: [
      'O que mudou na sua compreensão após a investigação?',
      'Que hipóteses iniciais foram confirmadas ou corrigidas?',
      'Qual é agora a estrutura percebida com mais clareza?',
      'Como a investigação alterou sua leitura do clímax ou tema central?',
    ],
    relevantAuthors: ['Grant Osborne', 'Gordon Fee', 'Douglas Stuart', 'D.A. Carson'],
    cards: [
      card('preparar_tema_provavel', 'Tema refinado', 'Atualize o tema da passagem com base na investigação realizada.', 'Ajude-me a formular o tema da passagem após a investigação exegética.'),
      card('preparar_grande_ideia_inicial', 'Grande ideia refinada', 'Atualize a grande ideia do texto com o que a investigação confirmou ou corrigiu.', 'Ajude-me a formular a grande ideia após a investigação, integrando os achados exegéticos.'),
      card('preparar_estrutura_percebida', 'Estrutura refinada', 'Revise o esboço da passagem com base nos estudos contextual, textual e teológico.', 'Ajude-me a revisar a estrutura da passagem com base na investigação.'),
      card('preparar_personagens', 'Personagens', 'Atualize e complete a lista de personagens com novos dados da investigação.', 'Ajude-me a aprofundar a observação dos personagens após o estudo exegético.'),
      card('preparar_movimento_narrativo', 'Movimento narrativo refinado', 'Revise o movimento narrativo com base no que a investigação revelou.', 'Ajude-me a refinar o movimento narrativo da passagem após a análise textual.'),
      card('preparar_fluxo_argumentativo', 'Fluxo argumentativo refinado', 'Revise o fluxo argumentativo com base nos estudos de sintaxe e estrutura.', 'Ajude-me a refinar o fluxo argumentativo após o estudo textual.'),
      card('preparar_climax', 'Clímax confirmado', 'Confirme ou revise o clímax da passagem à luz da investigação.', 'Ajude-me a confirmar o clímax da passagem após a investigação exegética.'),
      card('preparar_palavras_repetidas', 'Termos e repetições', 'Complemente com novos achados lexicais e estruturais.', 'Ajude-me a registrar os principais achados lexicais e estruturais da investigação.'),
    ],
  },
  {
    slug: 'pregar_visao_geral',
    title: 'Visão Geral Homilética',
    shortTitle: 'Visão Geral',
    phase: 'comunicar',
    module: 'inventio',
    group: 'pregar_visao_geral',
    groupLabel: 'Síntese final para comunicação',
    order: 5,
    objective:
      'Consolidar a compreensão final do texto voltada para a comunicação — sintetizando a exegese em uma visão clara que orienta o sermão, estudo ou comentário.',
    keyQuestions: [
      'Qual é a mensagem central que você quer comunicar?',
      'Como a estrutura do texto sustenta essa mensagem?',
      'Que elementos da exegese são essenciais para a comunicação fiel?',
      'Como este texto aponta para Cristo e transforma os ouvintes?',
    ],
    relevantAuthors: ['Haddon Robinson', 'Bryan Chapell', 'Sidney Greidanus', 'Timothy Keller'],
    cards: [
      card('preparar_tema_provavel', 'Tema da comunicação', 'Formule o tema central da sua comunicação — a ideia que organizará o sermão ou estudo.', 'Ajude-me a formular o tema central para a comunicação com base em toda a investigação.'),
      card('preparar_grande_ideia_inicial', 'Grande ideia homilética', 'Escreva a grande ideia do texto voltada para a pregação: sujeito + complemento.', 'Ajude-me a formular a grande ideia homilética — sujeito e complemento — para a comunicação.'),
      card('preparar_estrutura_percebida', 'Estrutura da comunicação', 'Esboce como a estrutura do texto se traduz nos movimentos da sua comunicação.', 'Ajude-me a transformar a estrutura exegética em estrutura comunicativa.'),
      card('preparar_personagens', 'Pontos de identificação', 'Identifique personagens, situações ou conflitos que o ouvinte reconhece em sua própria vida.', 'Ajude-me a identificar pontos de identificação entre o texto e a vida dos ouvintes.'),
      card('preparar_movimento_narrativo', 'Movimento da mensagem', 'Descreva como sua comunicação se moverá do início ao fim.', 'Ajude-me a planejar o movimento da mensagem do início ao clímax.'),
      card('preparar_fluxo_argumentativo', 'Fluxo do argumento', 'Descreva como o argumento central se desenvolverá na comunicação.', 'Ajude-me a desenvolver o fluxo argumentativo da mensagem.'),
      card('preparar_climax', 'Clímax da comunicação', 'Identifique o momento de maior peso ou virada da sua comunicação.', 'Ajude-me a identificar o clímax da comunicação e como chegá-lo com força.'),
      card('preparar_palavras_repetidas', 'Termos e imagens centrais', 'Liste as palavras, imagens e termos que estruturarão a comunicação.', 'Ajude-me a selecionar os termos e imagens centrais para a comunicação fiel do texto.'),
    ],
  },
]
