import type { SectionDef } from './workspace-sections'

function card(id: string, title: string, placeholder: string, aiTrigger: string) {
  return { id, title, placeholder, aiTrigger }
}

type SectionSpec = {
  slug: string
  title: string
  shortTitle?: string
  phase: SectionDef['phase']
  module: SectionDef['module']
  group: string
  groupLabel: string
  order: number
  objective: string
  cards: Array<{ id: string; title: string; placeholder?: string }>
}

function section(spec: SectionSpec): SectionDef {
  return {
    slug: spec.slug,
    title: spec.title,
    shortTitle: spec.shortTitle ?? spec.title,
    phase: spec.phase,
    module: spec.module,
    group: spec.group,
    groupLabel: spec.groupLabel,
    order: spec.order,
    objective: spec.objective,
    keyQuestions: [
      `O que precisa ficar claro em "${spec.shortTitle ?? spec.title}"?`,
      'Que conteúdo já existe no projeto e deve orientar esta etapa?',
      'Qual é a próxima decisão prática para avançar este projeto?',
    ],
    relevantAuthors: ['Howard Hendricks', 'John Stott', 'D. A. Carson', 'Tim Keller'],
    cards: spec.cards.map(item => card(
      item.id,
      item.title,
      item.placeholder ?? `Desenvolva ${item.title.toLowerCase()} para este projeto.`,
      `Gere conteúdo contextualizado para "${item.title}" dentro de "${spec.title}", respeitando a natureza deste projeto e o que já foi preenchido no Lampas.`
    )),
  }
}

function buildSections(base: number, specs: Omit<SectionSpec, 'order'>[]): SectionDef[] {
  return specs.map((spec, index) => section({ ...spec, order: base + index }))
}

export const PRODUCTION_SECTIONS: SectionDef[] = [
  ...buildSections(900, [
    {
      slug: 'aula_preparar',
      title: 'I. Preparar',
      phase: 'preparar',
      module: 'inventio',
      group: 'aula_preparar_grp',
      groupLabel: 'I. Preparar',
      objective: 'Definir finalidade, público, tempo e base bíblica ou temática da aula.',
      cards: [
        { id: 'objetivo_aula', title: 'Objetivo da aula' },
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'tempo_disponivel', title: 'Tempo disponível' },
        { id: 'conhecimento_previo', title: 'Conhecimento prévio dos alunos' },
        { id: 'texto_tema_base', title: 'Texto ou tema base' },
      ],
    },
    {
      slug: 'aula_compreender',
      title: 'II. Compreender',
      phase: 'interpretar',
      module: 'inventio',
      group: 'aula_compreender_grp',
      groupLabel: 'II. Compreender',
      objective: 'Organizar o conteúdo central, conceitos, dificuldades e relação com a Escritura.',
      cards: [
        { id: 'conteudo_central', title: 'Conteúdo central' },
        { id: 'conceitos_principais', title: 'Conceitos principais' },
        { id: 'pontos_dificuldade', title: 'Pontos de dificuldade' },
        { id: 'termos_importantes', title: 'Termos importantes' },
        { id: 'relacao_escritura', title: 'Relação com a Escritura' },
      ],
    },
    {
      slug: 'aula_ensinar',
      title: 'III. Ensinar',
      phase: 'comunicar',
      module: 'dispositio',
      group: 'aula_ensinar_grp',
      groupLabel: 'III. Ensinar',
      objective: 'Desenvolver a condução didática da aula, perguntas, atividades e aplicações pedagógicas.',
      cards: [
        { id: 'introducao_didatica', title: 'Introdução didática' },
        { id: 'desenvolvimento_aula', title: 'Desenvolvimento da aula' },
        { id: 'explicacoes_principais', title: 'Explicações principais' },
        { id: 'perguntas_interacao', title: 'Perguntas para interação' },
        { id: 'dinamicas_atividades', title: 'Dinâmicas ou atividades' },
        { id: 'aplicacoes_pedagogicas', title: 'Aplicações pedagógicas' },
      ],
    },
    {
      slug: 'aula_material',
      title: 'IV. Material',
      phase: 'comunicar',
      module: 'memoria',
      group: 'aula_material_grp',
      groupLabel: 'IV. Material',
      objective: 'Preparar roteiro, material do aluno, slides e atividades complementares.',
      cards: [
        { id: 'roteiro_professor', title: 'Roteiro do professor' },
        { id: 'material_aluno', title: 'Material do aluno' },
        { id: 'slides_handout', title: 'Slides ou handout' },
        { id: 'tarefa_complementar', title: 'Tarefa ou atividade complementar' },
      ],
    },
  ]),

  ...buildSections(930, [
    {
      slug: 'artigo_planejar',
      title: 'I. Planejar',
      phase: 'preparar',
      module: 'inventio',
      group: 'artigo_planejar_grp',
      groupLabel: 'I. Planejar',
      objective: 'Definir tema, problema, tese, público e objetivo do artigo.',
      cards: [
        { id: 'tema', title: 'Tema' },
        { id: 'problema', title: 'Problema' },
        { id: 'tese', title: 'Tese' },
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'objetivo_artigo', title: 'Objetivo do artigo' },
      ],
    },
    {
      slug: 'artigo_pesquisar',
      title: 'II. Pesquisar',
      phase: 'interpretar',
      module: 'inventio',
      group: 'artigo_pesquisar_grp',
      groupLabel: 'II. Pesquisar',
      objective: 'Reunir fontes bíblicas, teológicas, históricas, citações e objeções.',
      cards: [
        { id: 'fontes_biblicas', title: 'Fontes bíblicas' },
        { id: 'fontes_teologicas', title: 'Fontes teológicas' },
        { id: 'fontes_historicas', title: 'Fontes históricas' },
        { id: 'citacoes_importantes', title: 'Citações importantes' },
        { id: 'objecoes_relevantes', title: 'Objeções relevantes' },
      ],
    },
    {
      slug: 'artigo_argumentar',
      title: 'III. Argumentar',
      phase: 'comunicar',
      module: 'dispositio',
      group: 'artigo_argumentar_grp',
      groupLabel: 'III. Argumentar',
      objective: 'Construir introdução, argumentos, contra-argumentos e respostas.',
      cards: [
        { id: 'introducao', title: 'Introdução' },
        { id: 'desenvolvimento_tese', title: 'Desenvolvimento da tese' },
        { id: 'argumento_1', title: 'Argumento 1' },
        { id: 'argumento_2', title: 'Argumento 2' },
        { id: 'argumento_3', title: 'Argumento 3' },
        { id: 'contra_argumentos', title: 'Contra-argumentos' },
        { id: 'resposta_contra_argumentos', title: 'Resposta aos contra-argumentos' },
      ],
    },
    {
      slug: 'artigo_redigir',
      title: 'IV. Redigir',
      phase: 'comunicar',
      module: 'elocutio',
      group: 'artigo_redigir_grp',
      groupLabel: 'IV. Redigir',
      objective: 'Produzir título, subtítulo, introdução final, corpo, conclusão e chamada final.',
      cards: [
        { id: 'titulo', title: 'Título' },
        { id: 'subtitulo', title: 'Subtítulo' },
        { id: 'introducao_final', title: 'Introdução final' },
        { id: 'corpo_artigo', title: 'Corpo do artigo' },
        { id: 'conclusao', title: 'Conclusão' },
        { id: 'chamada_final', title: 'Chamada final' },
      ],
    },
    {
      slug: 'artigo_revisar',
      title: 'V. Revisar',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'artigo_revisar_grp',
      groupLabel: 'V. Revisar',
      objective: 'Revisar clareza, coerência, fidelidade bíblica, força argumentativa e tom.',
      cards: [
        { id: 'clareza', title: 'Clareza' },
        { id: 'coerencia', title: 'Coerência' },
        { id: 'fidelidade_biblica', title: 'Fidelidade bíblica' },
        { id: 'forca_argumentativa', title: 'Força argumentativa' },
        { id: 'tom', title: 'Tom pastoral ou acadêmico' },
      ],
    },
  ]),

  ...buildSections(970, [
    {
      slug: 'ebook_conceber',
      title: 'I. Conceber',
      phase: 'preparar',
      module: 'inventio',
      group: 'ebook_conceber_grp',
      groupLabel: 'I. Conceber',
      objective: 'Definir tema, público, promessa central, objetivo e problema resolvido pelo e-book.',
      cards: [
        { id: 'tema', title: 'Tema do e-book' },
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'promessa_central', title: 'Promessa central' },
        { id: 'objetivo_material', title: 'Objetivo do material' },
        { id: 'problema_resolvido', title: 'Problema que o e-book resolve' },
      ],
    },
    {
      slug: 'ebook_estruturar',
      title: 'II. Estruturar',
      phase: 'interpretar',
      module: 'dispositio',
      group: 'ebook_estruturar_grp',
      groupLabel: 'II. Estruturar',
      objective: 'Organizar título, sumário, capítulos, progressão lógica e conclusão.',
      cards: [
        { id: 'titulo', title: 'Título' },
        { id: 'subtitulo', title: 'Subtítulo' },
        { id: 'sumario', title: 'Sumário' },
        { id: 'capitulos', title: 'Capítulos' },
        { id: 'progressao_logica', title: 'Progressão lógica' },
        { id: 'conclusao', title: 'Conclusão' },
      ],
    },
    {
      slug: 'ebook_escrever',
      title: 'III. Escrever',
      phase: 'comunicar',
      module: 'elocutio',
      group: 'ebook_escrever_grp',
      groupLabel: 'III. Escrever',
      objective: 'Redigir introdução, capítulos, conclusão e chamadas práticas.',
      cards: [
        { id: 'introducao', title: 'Introdução' },
        { id: 'capitulo_1', title: 'Capítulo 1' },
        { id: 'capitulo_2', title: 'Capítulo 2' },
        { id: 'capitulo_3', title: 'Capítulo 3' },
        { id: 'capitulos_adicionais', title: 'Capítulos adicionais' },
        { id: 'conclusao', title: 'Conclusão' },
        { id: 'chamadas_praticas', title: 'Chamadas práticas' },
      ],
    },
    {
      slug: 'ebook_enriquecer',
      title: 'IV. Enriquecer',
      phase: 'comunicar',
      module: 'memoria',
      group: 'ebook_enriquecer_grp',
      groupLabel: 'IV. Enriquecer',
      objective: 'Adicionar citações, quadros, perguntas, exercícios e recursos extras.',
      cards: [
        { id: 'citacoes', title: 'Citações' },
        { id: 'quadros_explicativos', title: 'Quadros explicativos' },
        { id: 'perguntas_reflexao', title: 'Perguntas de reflexão' },
        { id: 'exercicios', title: 'Exercícios' },
        { id: 'recursos_extras', title: 'Recursos extras' },
      ],
    },
    {
      slug: 'ebook_publicar',
      title: 'V. Publicar',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'ebook_publicar_grp',
      groupLabel: 'V. Publicar',
      objective: 'Preparar apresentação, descrição, capa, formato de exportação e versão final.',
      cards: [
        { id: 'texto_apresentacao', title: 'Texto de apresentação' },
        { id: 'descricao_comercial', title: 'Descrição comercial' },
        { id: 'capa', title: 'Capa' },
        { id: 'formato_exportacao', title: 'Formato de exportação' },
        { id: 'versao_final', title: 'Versão final' },
      ],
    },
  ]),

  ...buildSections(1020, [
    {
      slug: 'livro_conceito',
      title: 'I. Conceito',
      phase: 'preparar',
      module: 'inventio',
      group: 'livro_conceito_grp',
      groupLabel: 'I. Conceito',
      objective: 'Definir tema central, problema, tese, público-alvo e contribuição específica do livro.',
      cards: [
        { id: 'tema_central', title: 'Tema central' },
        { id: 'problema_principal', title: 'Problema principal' },
        { id: 'tese_livro', title: 'Tese do livro' },
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'justificativa_obra', title: 'Justificativa da obra' },
        { id: 'contribuicao_especifica', title: 'Contribuição específica' },
      ],
    },
    {
      slug: 'livro_arquitetura',
      title: 'II. Arquitetura',
      phase: 'interpretar',
      module: 'dispositio',
      group: 'livro_arquitetura_grp',
      groupLabel: 'II. Arquitetura',
      objective: 'Organizar título, subtítulo, sumário macro, partes, capítulos e progressão argumentativa.',
      cards: [
        { id: 'titulo', title: 'Título' },
        { id: 'subtitulo', title: 'Subtítulo' },
        { id: 'sumario_macro', title: 'Sumário macro' },
        { id: 'partes_livro', title: 'Partes do livro' },
        { id: 'capitulos', title: 'Capítulos' },
        { id: 'progressao_argumentativa', title: 'Progressão argumentativa' },
        { id: 'conclusao_geral', title: 'Conclusão geral' },
      ],
    },
    {
      slug: 'livro_desenvolvimento',
      title: 'III. Desenvolvimento',
      phase: 'comunicar',
      module: 'elocutio',
      group: 'livro_desenvolvimento_grp',
      groupLabel: 'III. Desenvolvimento',
      objective: 'Redigir introdução, partes, capítulos, transições e conclusões parciais.',
      cards: [
        { id: 'introducao_geral', title: 'Introdução geral' },
        { id: 'parte_1', title: 'Parte 1' },
        { id: 'parte_2', title: 'Parte 2' },
        { id: 'parte_3', title: 'Parte 3' },
        { id: 'capitulos', title: 'Capítulos' },
        { id: 'transicoes_capitulos', title: 'Transições entre capítulos' },
        { id: 'conclusoes_parciais', title: 'Conclusões parciais' },
      ],
    },
    {
      slug: 'livro_pesquisa',
      title: 'IV. Pesquisa',
      phase: 'comunicar',
      module: 'memoria',
      group: 'livro_pesquisa_grp',
      groupLabel: 'IV. Pesquisa',
      objective: 'Catalogar referências bíblicas, teológicas, históricas, autores, citações e notas.',
      cards: [
        { id: 'referencias_biblicas', title: 'Referências bíblicas' },
        { id: 'referencias_teologicas', title: 'Referências teológicas' },
        { id: 'referencias_historicas', title: 'Referências históricas' },
        { id: 'autores_fundamentais', title: 'Autores fundamentais' },
        { id: 'citacoes', title: 'Citações' },
        { id: 'notas', title: 'Notas' },
      ],
    },
    {
      slug: 'livro_revisao',
      title: 'V. Revisão',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'livro_revisao_grp',
      groupLabel: 'V. Revisão',
      objective: 'Revisar tese, capítulos, argumento, estilo, teologia e versão final.',
      cards: [
        { id: 'coerencia_tese', title: 'Coerência da tese' },
        { id: 'clareza_capitulos', title: 'Clareza dos capítulos' },
        { id: 'unidade_argumento', title: 'Unidade do argumento' },
        { id: 'estilo', title: 'Estilo' },
        { id: 'revisao_teologica', title: 'Revisão teológica' },
        { id: 'revisao_final', title: 'Revisão final' },
      ],
    },
    {
      slug: 'livro_publicacao',
      title: 'VI. Publicação',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'livro_publicacao_grp',
      groupLabel: 'VI. Publicação',
      objective: 'Preparar sinopse, contracapa, apresentação, prefácio, capa e exportação.',
      cards: [
        { id: 'sinopse', title: 'Sinopse' },
        { id: 'contracapa', title: 'Texto de contracapa' },
        { id: 'apresentacao', title: 'Apresentação' },
        { id: 'prefacio', title: 'Prefácio' },
        { id: 'capa', title: 'Capa' },
        { id: 'exportacao', title: 'Exportação' },
      ],
    },
  ]),

  ...buildSections(1080, [
    {
      slug: 'palestra_preparar',
      title: 'I. Preparar',
      phase: 'preparar',
      module: 'inventio',
      group: 'palestra_preparar_grp',
      groupLabel: 'I. Preparar',
      objective: 'Definir evento, público, tempo, objetivo e tese da palestra.',
      cards: [
        { id: 'evento_contexto', title: 'Evento e contexto' },
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'tempo_disponivel', title: 'Tempo disponível' },
        { id: 'objetivo_palestra', title: 'Objetivo da palestra' },
        { id: 'tese_central', title: 'Tese central' },
      ],
    },
    {
      slug: 'palestra_construir',
      title: 'II. Construir',
      phase: 'interpretar',
      module: 'dispositio',
      group: 'palestra_construir_grp',
      groupLabel: 'II. Construir',
      objective: 'Estruturar abertura, desenvolvimento, movimentos e fechamento da palestra.',
      cards: [
        { id: 'abertura', title: 'Abertura' },
        { id: 'ponto_1', title: 'Ponto 1' },
        { id: 'ponto_2', title: 'Ponto 2' },
        { id: 'ponto_3', title: 'Ponto 3' },
        { id: 'transicoes', title: 'Transições' },
        { id: 'fechamento', title: 'Fechamento' },
      ],
    },
    {
      slug: 'palestra_comunicar',
      title: 'III. Comunicar',
      phase: 'comunicar',
      module: 'elocutio',
      group: 'palestra_comunicar_grp',
      groupLabel: 'III. Comunicar',
      objective: 'Ajustar linguagem, histórias, exemplos, aplicações e ritmo oral.',
      cards: [
        { id: 'linguagem', title: 'Linguagem' },
        { id: 'historias', title: 'Histórias' },
        { id: 'exemplos', title: 'Exemplos' },
        { id: 'aplicacoes', title: 'Aplicações' },
        { id: 'ritmo_oral', title: 'Ritmo oral' },
      ],
    },
    {
      slug: 'palestra_apoiar',
      title: 'IV. Apoiar',
      phase: 'comunicar',
      module: 'memoria',
      group: 'palestra_apoiar_grp',
      groupLabel: 'IV. Apoiar',
      objective: 'Preparar slides, handout, perguntas e recursos de apoio.',
      cards: [
        { id: 'slides', title: 'Slides' },
        { id: 'handout', title: 'Handout' },
        { id: 'perguntas', title: 'Perguntas' },
        { id: 'recursos_apoio', title: 'Recursos de apoio' },
      ],
    },
    {
      slug: 'palestra_ensaiar',
      title: 'V. Ensaiar',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'palestra_ensaiar_grp',
      groupLabel: 'V. Ensaiar',
      objective: 'Revisar tempo, ênfase, conclusão e pontos de memória para apresentação.',
      cards: [
        { id: 'controle_tempo', title: 'Controle de tempo' },
        { id: 'enfases', title: 'Ênfases' },
        { id: 'conclusao_oral', title: 'Conclusão oral' },
        { id: 'pontos_memoria', title: 'Pontos de memória' },
      ],
    },
  ]),

  ...buildSections(1130, [
    {
      slug: 'curso_planejar',
      title: 'I. Planejar',
      phase: 'preparar',
      module: 'inventio',
      group: 'curso_planejar_grp',
      groupLabel: 'I. Planejar',
      objective: 'Definir público, objetivos, carga horária, pré-requisitos e resultados esperados.',
      cards: [
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'objetivos_aprendizagem', title: 'Objetivos de aprendizagem' },
        { id: 'carga_horaria', title: 'Carga horária' },
        { id: 'pre_requisitos', title: 'Pré-requisitos' },
        { id: 'resultados_esperados', title: 'Resultados esperados' },
      ],
    },
    {
      slug: 'curso_estruturar',
      title: 'II. Estruturar',
      phase: 'interpretar',
      module: 'dispositio',
      group: 'curso_estruturar_grp',
      groupLabel: 'II. Estruturar',
      objective: 'Organizar módulos, aulas, trilha de aprendizagem, avaliações e progressão didática.',
      cards: [
        { id: 'modulos', title: 'Módulos' },
        { id: 'aulas', title: 'Aulas' },
        { id: 'trilha_aprendizagem', title: 'Trilha de aprendizagem' },
        { id: 'avaliacoes', title: 'Avaliações' },
        { id: 'progressao_didatica', title: 'Progressão didática' },
      ],
    },
    {
      slug: 'curso_produzir_aulas',
      title: 'III. Produzir Aulas',
      phase: 'comunicar',
      module: 'elocutio',
      group: 'curso_produzir_aulas_grp',
      groupLabel: 'III. Produzir Aulas',
      objective: 'Criar roteiros, conteúdos, exemplos, atividades e aplicação de cada aula.',
      cards: [
        { id: 'roteiros_aulas', title: 'Roteiros das aulas' },
        { id: 'conteudos_centrais', title: 'Conteúdos centrais' },
        { id: 'exemplos', title: 'Exemplos' },
        { id: 'atividades', title: 'Atividades' },
        { id: 'aplicacao_aula', title: 'Aplicação de cada aula' },
      ],
    },
    {
      slug: 'curso_materiais',
      title: 'IV. Materiais',
      phase: 'comunicar',
      module: 'memoria',
      group: 'curso_materiais_grp',
      groupLabel: 'IV. Materiais',
      objective: 'Preparar apostila, slides, leituras, exercícios e recursos complementares.',
      cards: [
        { id: 'apostila', title: 'Apostila' },
        { id: 'slides', title: 'Slides' },
        { id: 'leituras', title: 'Leituras' },
        { id: 'exercicios', title: 'Exercícios' },
        { id: 'recursos_complementares', title: 'Recursos complementares' },
      ],
    },
    {
      slug: 'curso_publicar',
      title: 'V. Publicar',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'curso_publicar_grp',
      groupLabel: 'V. Publicar',
      objective: 'Definir descrição, ementa, certificados, divulgação e versão final do curso.',
      cards: [
        { id: 'descricao_curso', title: 'Descrição do curso' },
        { id: 'ementa', title: 'Ementa' },
        { id: 'certificado', title: 'Certificado' },
        { id: 'divulgacao', title: 'Divulgação' },
        { id: 'versao_final', title: 'Versão final' },
      ],
    },
  ]),

  ...buildSections(1180, [
    {
      slug: 'serie_conceber',
      title: 'I. Conceber',
      phase: 'preparar',
      module: 'inventio',
      group: 'serie_conceber_grp',
      groupLabel: 'I. Conceber',
      objective: 'Definir tema da série, necessidade pastoral, público, objetivo e texto ou eixo bíblico.',
      cards: [
        { id: 'tema_serie', title: 'Tema da série' },
        { id: 'necessidade_pastoral', title: 'Necessidade pastoral' },
        { id: 'publico_alvo', title: 'Público-alvo' },
        { id: 'objetivo_serie', title: 'Objetivo da série' },
        { id: 'texto_eixo_biblico', title: 'Texto ou eixo bíblico' },
      ],
    },
    {
      slug: 'serie_planejar',
      title: 'II. Planejar',
      phase: 'interpretar',
      module: 'dispositio',
      group: 'serie_planejar_grp',
      groupLabel: 'II. Planejar',
      objective: 'Organizar duração, calendário, ordem das mensagens, progressão e títulos.',
      cards: [
        { id: 'duracao', title: 'Duração' },
        { id: 'calendario', title: 'Calendário' },
        { id: 'ordem_mensagens', title: 'Ordem das mensagens' },
        { id: 'progressao_serie', title: 'Progressão da série' },
        { id: 'titulos_mensagens', title: 'Títulos das mensagens' },
      ],
    },
    {
      slug: 'serie_desenvolver',
      title: 'III. Desenvolver',
      phase: 'comunicar',
      module: 'elocutio',
      group: 'serie_desenvolver_grp',
      groupLabel: 'III. Desenvolver',
      objective: 'Preparar resumo de cada mensagem, textos, grande ideia, aplicações e conexões.',
      cards: [
        { id: 'resumo_mensagem_1', title: 'Resumo da mensagem 1' },
        { id: 'resumo_mensagem_2', title: 'Resumo da mensagem 2' },
        { id: 'resumos_adicionais', title: 'Resumos adicionais' },
        { id: 'textos_biblicos', title: 'Textos bíblicos' },
        { id: 'grandes_ideias', title: 'Grandes ideias' },
        { id: 'aplicacoes', title: 'Aplicações' },
        { id: 'conexoes_entre_mensagens', title: 'Conexões entre mensagens' },
      ],
    },
    {
      slug: 'serie_comunicar',
      title: 'IV. Comunicar',
      phase: 'comunicar',
      module: 'memoria',
      group: 'serie_comunicar_grp',
      groupLabel: 'IV. Comunicar',
      objective: 'Criar identidade da série, descrição, chamadas, materiais e slides.',
      cards: [
        { id: 'identidade_serie', title: 'Identidade da série' },
        { id: 'descricao_publica', title: 'Descrição pública' },
        { id: 'chamadas', title: 'Chamadas' },
        { id: 'materiais_apoio', title: 'Materiais de apoio' },
        { id: 'slides', title: 'Slides' },
      ],
    },
    {
      slug: 'serie_publicar',
      title: 'V. Publicar',
      phase: 'comunicar',
      module: 'pronuntiatio',
      group: 'serie_publicar_grp',
      groupLabel: 'V. Publicar',
      objective: 'Preparar página da série, descrição final, calendário público e arquivo.',
      cards: [
        { id: 'pagina_serie', title: 'Página da série' },
        { id: 'descricao_final', title: 'Descrição final' },
        { id: 'calendario_publico', title: 'Calendário público' },
        { id: 'arquivo_serie', title: 'Arquivo da série' },
      ],
    },
  ]),
]
