-- Catecismo Maior de Westminster — Parte 1 (Perguntas 1–98)
-- Pré-requisito: migration 021_confessions_catechisms.sql já executada
-- Execute no Supabase SQL Editor ANTES de seed-cmw-maior-parte2.sql

DO $$
DECLARE
  v_doc_id uuid;
BEGIN
  SELECT id INTO v_doc_id
  FROM public.lampas_confessional_documents
  WHERE slug = 'catecismo-maior-westminster';

  IF v_doc_id IS NULL THEN
    RAISE EXCEPTION 'Documento catecismo-maior-westminster não encontrado. Execute a migration 021 primeiro.';
  END IF;

  INSERT INTO public.lampas_confessional_questions
    (document_id, number, number_label, question, answer, doctrine_tags, bible_references, sort_order, metadata)
  VALUES
    (v_doc_id, 1, '1', 'Qual é o fim principal e mais elevado do homem?', 'O fim principal e mais elevado do homem é glorificar a Deus e gozar d''Ele plenamente para sempre.', ARRAY['glorificação','propósito humano'], ARRAY['Romanos 11.36','1 Coríntios 10.31'], 1, '{"full_seed":true}'::jsonb),
    (v_doc_id, 2, '2', 'Como se manifesta que há um Deus?', 'A luz da natureza no homem e as obras de Deus manifestam claramente que há um Deus; mas somente a sua Palavra e Espírito revelam-no suficientemente e de modo eficaz para a salvação.', ARRAY['revelação natural','Escrituras','conhecimento de Deus'], ARRAY['Romanos 1.19-20','1 Coríntios 2.9-10'], 2, '{"full_seed":true}'::jsonb),
    (v_doc_id, 3, '3', 'O que é a Palavra de Deus?', 'As Santas Escrituras do Antigo e Novo Testamento são a Palavra de Deus, a única regra de fé e obediência.', ARRAY['Escrituras','Palavra de Deus','regra de fé'], ARRAY['2 Timóteo 3.16','Efésios 2.20'], 3, '{"full_seed":true}'::jsonb),
    (v_doc_id, 4, '4', 'De que modo se evidencia que as Escrituras são a Palavra de Deus?', 'As Escrituras manifestam-se a si mesmas como Palavra de Deus, pela sua majestade e pureza, pelo consenso de todas as suas partes, pelo seu escopo geral de dar a Deus toda a glória, pela plena descoberta que fazem do único caminho de salvação do homem, por seus muitos outros incomparáveis excelências e por sua inteira perfeição; mas a evidência mais plena e a persuasão provêm do inward work of the Holy Spirit, testificando no coração dos homens com a Palavra e pela Palavra.', ARRAY['Escrituras','testemunho interno','autopistia'], ARRAY['2 Timóteo 3.16','1 Tessalonicenses 2.13'], 4, '{"full_seed":true}'::jsonb),
    (v_doc_id, 5, '5', 'Que ensinam principalmente as Escrituras?', 'As Escrituras ensinam principalmente o que o homem deve crer acerca de Deus, e que deveres Deus requer do homem.', ARRAY['Escrituras','fé','obediência'], ARRAY['2 Timóteo 1.13'], 5, '{"full_seed":true}'::jsonb),
    (v_doc_id, 6, '6', 'O que as Escrituras fazem-nos conhecer acerca de Deus?', 'As Escrituras fazem-nos conhecer o que Deus é, as pessoas da Divindade, os seus decretos e a execução deles.', ARRAY['Deus','Trindade','decretos'], ARRAY['Hebreus 11.6','João 17.3'], 6, '{"full_seed":true}'::jsonb),
    (v_doc_id, 7, '7', 'O que é Deus?', 'Deus é um Espírito, em si mesmo e por si mesmo infinito em ser, glória, beatitude e perfeição; todo-suficiente, eterno, imutável, incompreensível, em todo lugar presente, todo-poderoso, onisciente, santíssimo, absolutamente livre, absolutamente soberano; trabalhando tudo segundo o conselho de sua própria vontade imutável e justíssima, para a sua própria glória; amantíssimo, gracioso, misericordioso, longânime, abundante em bondade e verdade, perdoando a iniquidade, a transgressão e o pecado; o remunerador dos que o procuram diligentemente; e ao mesmo tempo justíssimo e terrível em seus juízos, aborrecendo todo o pecado, e de nenhum modo inocentando o culpado.', ARRAY['atributos divinos','Deus','natureza divina'], ARRAY['Êxodo 3.14','Jó 11.7-9','Salmo 90.2'], 7, '{"full_seed":true}'::jsonb),
    (v_doc_id, 8, '8', 'Há mais de um Deus?', 'Há somente um Deus, único, único e verdadeiro.', ARRAY['monoteísmo','Deus'], ARRAY['Deuteronômio 6.4','Jeremias 10.10'], 8, '{"full_seed":true}'::jsonb),
    (v_doc_id, 9, '9', 'Quantas pessoas há na Divindade?', 'Na Divindade há três pessoas, de uma só substância, poder e eternidade — Deus o Pai, Deus o Filho e Deus o Espírito Santo; o Pai procedente de ninguém, o Filho eternamente gerado pelo Pai, e o Espírito Santo eternamente procedente do Pai e do Filho.', ARRAY['Trindade','pessoas divinas','processão'], ARRAY['1 João 5.7','Mateus 3.16-17','João 15.26'], 9, '{"full_seed":true}'::jsonb),
    (v_doc_id, 10, '10', 'O que são os decretos de Deus?', 'Os decretos de Deus são o seu propósito eterno e livre, segundo o conselho de sua vontade, pelo qual, para sua própria glória, predestinou todos os seres humanos e todas as coisas que viriam a acontecer.', ARRAY['decretos','soberania','predestinação'], ARRAY['Efésios 1.11','Romanos 11.33'], 10, '{"full_seed":true}'::jsonb),
    (v_doc_id, 11, '11', 'Como se executam os decretos de Deus?', 'Os decretos de Deus são executados nas obras da criação e da providência, segundo o seu prazer em graça e julgamento.', ARRAY['decretos','criação','providência'], ARRAY['Apocalipse 4.11','Efésios 2.7'], 11, '{"full_seed":true}'::jsonb),
    (v_doc_id, 12, '12', 'O que é a obra de criação?', 'A obra de criação é aquela pela qual Deus Pai, Filho e Espírito Santo, no princípio, pelo poder de sua Palavra, fez do nada o mundo e tudo o que nele há, em seis dias e tudo muito bom.', ARRAY['criação','Trindade','criação do nada'], ARRAY['Gênesis 1.1','João 1.2-3','Hebreus 11.3'], 12, '{"full_seed":true}'::jsonb),
    (v_doc_id, 13, '13', 'Como preserva e governa Deus as suas criaturas?', 'Deus, pelo seu poder, sabedoria e bondade, preserva e governa todos os seus seres, ações e condições desde a maior até a menor, pelo seu providência santíssima, onisapiente e onipotente, segundo a sua infalível presciência e livre e imutável conselho, para o louvor da glória de sua sabedoria, poder, justiça, bondade e misericórdia.', ARRAY['providência','soberania','governo divino'], ARRAY['Hebreus 1.3','Daniel 4.34-35'], 13, '{"full_seed":true}'::jsonb),
    (v_doc_id, 14, '14', 'Como é Deus para com os seus anjos?', 'Deus, pela sua providência, permitiu que alguns anjos pecassem e caíssem voluntariamente no pecado e na condenação, e estabeleceu os demais em santidade e felicidade; contendo e ordenando todas as suas ações para a sua glória.', ARRAY['anjos','queda dos anjos','providência'], ARRAY['Jó 38.7','Judas 6','1 Timóteo 5.21'], 14, '{"full_seed":true}'::jsonb),
    (v_doc_id, 15, '15', 'O que foi a obra especial de providência de Deus para com o homem no estado em que foi criado?', 'A obra especial da providência de Deus para com o homem no estado em que foi criado foi entrar em uma aliança de vida com ele, sob a condição de perfeita obediência, proibindo-o, sob pena de morte, de comer do fruto da árvore do conhecimento do bem e do mal.', ARRAY['aliança de obras','criação','obediência','vida'], ARRAY['Gênesis 2.16-17','Gálatas 3.12'], 15, '{"full_seed":true}'::jsonb),
    (v_doc_id, 16, '16', 'Caiu Adão de seu estado de inocência original?', 'Nossos primeiros pais, sendo seduzidos pela astúcia do diabo, transgrediram voluntariamente o mandamento de Deus ao comer o fruto proibido; e, com isso, caíram do estado de inocência em que foram criados.', ARRAY['queda','tentação','desobediência'], ARRAY['Gênesis 3.1-13','2 Coríntios 11.3'], 16, '{"full_seed":true}'::jsonb),
    (v_doc_id, 17, '17', 'Afetou a queda de Adão e Eva toda a humanidade?', 'Sendo o pacto feito com Adão não somente para ele mas para toda a sua posteridade, toda a humanidade, descendendo dele por geração ordinária, pecou nele e caiu com ele em sua primeira transgressão.', ARRAY['pecado original','aliança','Adão','imputação'], ARRAY['Atos 17.26','Romanos 5.12-21'], 17, '{"full_seed":true}'::jsonb),
    (v_doc_id, 18, '18', 'Qual é o estado de pecado em que caiu o homem?', 'O estado de pecado em que caiu o homem consiste na culpa do primeiro pecado de Adão, na falta de justiça original e na corrupção de toda a sua natureza, chamada pecado original, juntamente com todos os pecados reais que dele procedem.', ARRAY['pecado original','corrupção','culpa','depravação'], ARRAY['Romanos 5.12','Romanos 3.10-18'], 18, '{"full_seed":true}'::jsonb),
    (v_doc_id, 19, '19', 'O que é a miséria do estado em que o homem caiu?', 'Toda a humanidade, por seu pecado, perdeu a comunhão com Deus, está sob a sua ira e maldição, e assim tornada sujeita a todas as misérias desta vida, à própria morte e às penas do inferno para sempre.', ARRAY['condenação','ira de Deus','miséria','morte'], ARRAY['Gênesis 3.16-19','Romanos 3.16-17','Mateus 25.41'], 19, '{"full_seed":true}'::jsonb),
    (v_doc_id, 20, '20', 'Deixou Deus todo gênero humano perecer no estado de pecado e miséria?', 'Não tendo deixado Deus toda a humanidade perecer sob o estado de pecado e miséria no qual se encontrava pela queda, foi agradável a ele, da sua mera boa vontade e amor, eleger alguns para a vida eterna, para ser salvos pelo seu Filho, segundo o eterno e livre propósito de sua vontade.', ARRAY['eleição','graça','amor de Deus','soteriologia'], ARRAY['Efésios 1.4-5','Romanos 3.20-22'], 20, '{"full_seed":true}'::jsonb),
    (v_doc_id, 21, '21', 'Quem é o Redentor dos eleitos?', 'O único Redentor dos eleitos é o Senhor Jesus Cristo, o Filho eterno de Deus, que, sendo verdadeiro e eterno Deus, tornou-se homem, e assim foi, e continua sendo, Deus e homem, em duas naturezas distintas e em uma só pessoa para sempre.', ARRAY['Redentor','Encarnação','duas naturezas','pessoa de Cristo'], ARRAY['1 Timóteo 2.5','João 1.14'], 21, '{"full_seed":true}'::jsonb),
    (v_doc_id, 22, '22', 'Como o Filho de Deus se tornou homem?', 'O Filho de Deus se tornou homem, tomando para si um corpo verdadeiro e uma alma racional, sendo concebido pela virtude do Espírito Santo no ventre da Virgem Maria, feito de sua substância, e nascido dela, porém sem pecado.', ARRAY['Encarnação','virgem Maria','Espírito Santo','impecabilidade'], ARRAY['Lucas 1.27-35','Hebreus 2.14','Hebreus 4.15'], 22, '{"full_seed":true}'::jsonb),
    (v_doc_id, 23, '23', 'Que ofícios exerce Cristo como nosso Redentor?', 'Cristo, como nosso Redentor, exerce os ofícios de profeta, sacerdote e rei, tanto em seu estado de humilhação como no de exaltação.', ARRAY['tríplice ofício','profeta','sacerdote','rei'], ARRAY['Atos 3.21-22','Hebreus 5.5-7','Salmo 2.6'], 23, '{"full_seed":true}'::jsonb),
    (v_doc_id, 24, '24', 'Como Cristo exerce o ofício de profeta?', 'Cristo exerce o ofício de profeta, na sua humilhação e exaltação, revelando à sua Igreja, em todos os tempos e de todos os modos, a vontade integral de Deus para toda a edificação e salvação deles.', ARRAY['profeta','revelação','Palavra de Deus'], ARRAY['João 1.18','1 Pedro 1.10-12','João 15.15'], 24, '{"full_seed":true}'::jsonb),
    (v_doc_id, 25, '25', 'Como Cristo exerce o ofício de sacerdote?', 'Cristo exerce o ofício de sacerdote, em sua humilhação, tendo-se oferecido a si mesmo, único e voluntariamente, como sacrifício sem mancha a Deus, para satisfazer completamente a justiça divina, para a reconciliação e a compra de um povo eterno para Deus; e em sua exaltação, pela sua contínua intercessão por eles.', ARRAY['sacerdócio','expiação','intercessão','sacrifício'], ARRAY['Hebreus 9.14-15','Hebreus 7.25','Hebreus 2.17'], 25, '{"full_seed":true}'::jsonb),
    (v_doc_id, 26, '26', 'Como Cristo exerce o ofício de rei?', 'Cristo exerce o ofício de rei, chamando do mundo um povo para si mesmo, dando-lhes ministros, leis e censuras, pelas quais ele os governa visivelmente; tornando-os, pelo seu Espírito e pela sua Palavra, obedientes a ele; governando e defendendo todos, e sujugando e conquistando todos os seus e os inimigos deles, poderosamente arranjando tudo para a sua própria glória, e para as suas boas condições.', ARRAY['reino de Cristo','governo','Igreja','vitória'], ARRAY['Efésios 4.11-12','Isaías 33.22','1 Coríntios 15.25'], 26, '{"full_seed":true}'::jsonb),
    (v_doc_id, 27, '27', 'Em que consistia a humilhação de Cristo?', 'A humilhação de Cristo consistia em seu nascimento e condição na qual veio ao mundo, sua sujeição à lei, as misérias desta vida, a ira de Deus e a morte maldita da cruz; no estar sepultado e continuando debaixo do poder da morte por um tempo.', ARRAY['humilhação','Encarnação','morte','sujeição à lei'], ARRAY['Filipenses 2.6-8','Gálatas 4.4','Atos 13.34-37'], 27, '{"full_seed":true}'::jsonb),
    (v_doc_id, 28, '28', 'Em que consiste a exaltação de Cristo?', 'A exaltação de Cristo consiste em sua ressurreição dos mortos no terceiro dia, em sua ascensão ao céu, em seu assentar-se à destra do Pai, e em seu vir no último dia para julgar o mundo.', ARRAY['exaltação','ressurreição','ascensão','segunda vinda'], ARRAY['1 Coríntios 15.4','Efésios 1.20','Atos 1.9-11'], 28, '{"full_seed":true}'::jsonb),
    (v_doc_id, 29, '29', 'Como tornamo-nos participantes da redenção comprada por Cristo?', 'Tornamo-nos participantes da redenção comprada por Cristo pela aplicação eficaz a nós pelo seu Espírito Santo; pelo qual nos chama e atrai à comunhão com Cristo, no evangelho outwardly, e pelo seu Espírito inwardly e poderosa e eficazmente.', ARRAY['aplicação da redenção','Espírito Santo','vocação'], ARRAY['João 6.44','Efésios 1.13'], 29, '{"full_seed":true}'::jsonb),
    (v_doc_id, 30, '30', 'Quais são os meios externos pelo quais o Espírito efetua a convocação e faz o seu povo participante de Cristo e seus benefícios?', 'Os meios externos da obra do Espírito são a Palavra que deve ser pregada, o sacramento a ser administrado e a oração a ser usada; os quais são eficazes para a salvação dos eleitos somente pela bênção de Deus e pela obra de seu Espírito.', ARRAY['meios de graça','Palavra','sacramentos','oração'], ARRAY['Mateus 28.19-20','Atos 2.41-42'], 30, '{"full_seed":true}'::jsonb),
    (v_doc_id, 31, '31', 'Como a Palavra é tornada eficaz para a salvação?', 'O Espírito de Deus torna a leitura, mas especialmente a pregação da Palavra, um meio eficaz de iluminar, convencer e humilhar os pecadores, de expulsá-los de si mesmos e de fazê-los atrair para Cristo, de conformá-los à sua imagem e de sujeitá-los à sua vontade, de fortalecê-los contra as tentações e corrupções, de edificá-los em graça e de confirmá-los em santidade e consolo pela fé para a salvação.', ARRAY['Palavra','pregação','Espírito Santo','convicção'], ARRAY['Romanos 10.14-17','1 Coríntios 14.24-25'], 31, '{"full_seed":true}'::jsonb),
    (v_doc_id, 32, '32', 'Como deveriam os que ouvem a Palavra de Deus usá-la para que seja eficaz para a salvação deles?', 'Que atendam com diligência, preparação e oração para a Palavra de Deus; recebam-na pela fé e amor, la depositem em seus corações, e a pratique nas suas vidas.', ARRAY['Palavra','ouvir','fé','obediência'], ARRAY['Provérbios 8.34','1 Tessalonicenses 2.13','Tiago 1.25'], 32, '{"full_seed":true}'::jsonb),
    (v_doc_id, 33, '33', 'Como os sacramentos são tornados meios eficazes de salvação?', 'Os sacramentos tornam-se meios eficazes de salvação não por qualquer virtude neles ou em quem os administra, mas somente pela bênção de Cristo e pela operação de seu Espírito naqueles que os recebem pela fé.', ARRAY['sacramentos','Espírito Santo','fé'], ARRAY['1 Coríntios 3.7','1 Pedro 3.21'], 33, '{"full_seed":true}'::jsonb),
    (v_doc_id, 34, '34', 'O que é um sacramento?', 'Um sacramento é um santo ordinance instituído por Cristo em sua Igreja, para significar, selar, e exibir para os que estão dentro do pacto de graça, os benefícios de sua mediação; para fortalecer e aumentar sua fé, e todos os outros graças; para obrigá-los à obediência; para testificar e nutrir seu amor e comunhão entre si mesmos; e para distingui-los dos que estão fora.', ARRAY['sacramentos','aliança','fé','Igreja'], ARRAY['Gênesis 17.7','Romanos 4.11','Mateus 26.26-28'], 34, '{"full_seed":true}'::jsonb),
    (v_doc_id, 35, '35', 'Quantos sacramentos há no Novo Testamento?', 'Há dois sacramentos no Novo Testamento: o Batismo e a Ceia do Senhor.', ARRAY['sacramentos','Batismo','Ceia do Senhor'], ARRAY['Mateus 28.19','1 Coríntios 11.23-26'], 35, '{"full_seed":true}'::jsonb),
    (v_doc_id, 36, '36', 'O que é o Batismo?', 'O Batismo é um sacramento no qual a lavagem com água no nome do Pai, do Filho e do Espírito Santo significa e sela o enxertamento em Cristo, e a participação nos benefícios da aliança de graça, e o nosso compromisso de ser do Senhor.', ARRAY['Batismo','aliança','enxertamento em Cristo'], ARRAY['Mateus 28.19','Romanos 6.4','Gálatas 3.27'], 36, '{"full_seed":true}'::jsonb),
    (v_doc_id, 37, '37', 'Quem deve ser batizado?', 'Os batizados devem ser todo os aqueles que ainda não foram batizados, que fazem profissão de sua fé em Cristo e obediência a ele, juntamente com os filhos de um ou de ambos os pais que são crentes.', ARRAY['Batismo','batismo de infantes','aliança'], ARRAY['Atos 2.38-39','Gênesis 17.10-12'], 37, '{"full_seed":true}'::jsonb),
    (v_doc_id, 38, '38', 'Pode o Batismo ser administrado mais de uma vez?', 'O Batismo deve ser administrado somente uma vez, que não deve ser repetido.', ARRAY['Batismo','singularidade'], ARRAY['Efésios 4.5'], 38, '{"full_seed":true}'::jsonb),
    (v_doc_id, 39, '39', 'O que é a Ceia do Senhor?', 'A Ceia do Senhor é um sacramento no qual, pela dação e recepção de pão e vinho segundo a instituição de Cristo, sua morte é mostrada, e os que dignamente o recebem são alimentados espiritualmente, não de modo carnal e corporal, mas pela fé, de seu corpo e sangue, com todos os benefícios de sua paixão; à sua confirmação e crescimento na graça.', ARRAY['Ceia do Senhor','sacrifício de Cristo','alimentação espiritual'], ARRAY['1 Coríntios 11.23-26','1 Coríntios 10.16'], 39, '{"full_seed":true}'::jsonb),
    (v_doc_id, 40, '40', 'O que é requerido para a digna participação da Ceia do Senhor?', 'Os que desejam participar dignaente da Ceia do Senhor devem examinar-se quanto ao seu conhecimento para discernir o corpo do Senhor, sua fé em alimentar-se dele, seu arrependimento, amor e nova obediência; a fim de não vir ao ato de comer e beber indignamente e assim comer e beber o julgamento para si mesmo.', ARRAY['Ceia do Senhor','auto-exame','participação digna'], ARRAY['1 Coríntios 11.28-29'], 40, '{"full_seed":true}'::jsonb),
    (v_doc_id, 41, '41', 'Por que os que participam da Ceia do Senhor devem examinar-se antes de vir a ela?', 'Por causa do dever e da necessidade do auto-exame, os participantes devem examinar-se: se entendem a natureza e o propósito do sacramento; se trazem consigo vivos os sentimentos de culpa e pecado; e se eles têm o desejo de renovar-se, mais ainda o desejo de crescer em Cristo.', ARRAY['Ceia do Senhor','auto-exame','preparação'], ARRAY['1 Coríntios 11.28','2 Coríntios 13.5'], 41, '{"full_seed":true}'::jsonb),
    (v_doc_id, 42, '42', 'Por que o Batismo é administrado somente uma vez?', 'Porque ele é o sinal e o selo do nosso enxertamento em Cristo, que não deve ser repetido; assim como Cristo morreu e ressuscitou uma única vez.', ARRAY['Batismo','singularidade','enxertamento'], ARRAY['Romanos 6.3-4'], 42, '{"full_seed":true}'::jsonb),
    (v_doc_id, 43, '43', 'O que é a oração?', 'A oração é uma oferta dos nossos desejos a Deus, em nome de Cristo, pela assistência de seu Espírito; com confissão de nossas culpas, e reconhecimento grato de suas misericórdias.', ARRAY['oração','intercessão','Espírito Santo'], ARRAY['Filipenses 4.6','1 João 5.14'], 43, '{"full_seed":true}'::jsonb),
    (v_doc_id, 44, '44', 'O que é exigido para a oração que seja aceita por Deus?', 'É exigido para a oração aceita que: oremos ao único Deus verdadeiro; com entendimento correto de sua natureza, propriedades e ordenanças, para as quais somos chamados a orar; com graça convicta, humildade, fervor, fé, amor e perseverança; e quando em oração vocacional, com voz alta, mas em linguagem que não seja desconhecida.', ARRAY['oração','fé','humildade'], ARRAY['João 4.24','Romanos 8.26','1 Timóteo 2.8'], 44, '{"full_seed":true}'::jsonb),
    (v_doc_id, 45, '45', 'O que devemos orar?', 'Devemos orar por tudo que pode tender para a glória de Deus, para o bem de sua Igreja, para nosso próprio bem ou para o de outros; mas não por coisas ilegítimas.', ARRAY['oração','vontade de Deus','intercessão'], ARRAY['Mateus 6.9-13','1 João 5.14'], 45, '{"full_seed":true}'::jsonb),
    (v_doc_id, 46, '46', 'Por quem devemos orar?', 'Devemos orar por toda a humanidade, e por todos os tipos de homens que vivem ou viverão; mas não pelos mortos, nem por aqueles que conhecemos ter cometido o pecado que leva à morte.', ARRAY['oração','intercessão','missão'], ARRAY['1 Timóteo 2.1-2','2 Samuel 7.29'], 46, '{"full_seed":true}'::jsonb),
    (v_doc_id, 47, '47', 'Por qual regra devemos dirigir nossa oração?', 'A Palavra de Deus toda é uma regra de oração; mas a regra especial de direção é aquela forma de oração que nosso Salvador Cristo nos ensinou, comumente chamada Pai Nosso.', ARRAY['oração','Pai Nosso','Escrituras'], ARRAY['Mateus 6.9-13'], 47, '{"full_seed":true}'::jsonb),
    (v_doc_id, 48, '48', 'Como a oração do Senhor serve de regra de direção?', 'A oração do Senhor nos serve de regra de direção; não que possamos somente usá-la naquelas palavras quando oramos, mas que devemos nos direcionar, por meio desta oração, quanto ao conteúdo ao Pai, assim como podemos nos ajudar de outras partes das Escrituras enquanto oramos; e que quanto à forma, ela nos ensina que seja breve e compreensiva.', ARRAY['oração','Pai Nosso','modelo'], ARRAY['Mateus 6.9','Romanos 8.26'], 48, '{"full_seed":true}'::jsonb),
    (v_doc_id, 49, '49', 'Quais partes a oração do Senhor contém?', 'A oração do Senhor contém um prefácio, seis petições e uma conclusão.', ARRAY['Pai Nosso','estrutura','oração'], ARRAY['Mateus 6.9-13'], 49, '{"full_seed":true}'::jsonb),
    (v_doc_id, 50, '50', 'O que nos ensina o prefácio da oração do Senhor?', 'O prefácio da oração do Senhor, que é "Pai nosso que estás nos céus", nos ensina a aproximarmo-nos de Deus com plena confiança de sua paternidade e bondade, assim como filhos com um pai, com toda reverência e outros exercícios convenientes; e a orar com e por outros.', ARRAY['Pai Nosso','filiação divina','reverência','confiança'], ARRAY['Romanos 8.15','Mateus 7.11'], 50, '{"full_seed":true}'::jsonb),
    (v_doc_id, 51, '51', 'Para quê pedimos na primeira petição?', 'Na primeira petição, que é "Santificado seja o teu nome", reconhecendo a nossa completa incapacidade e indisposição para glorificar a Deus, pedimos que Deus, por sua graça, nos habilite e disponha a nós e a outros a conhecê-lo, honrá-lo e glorificá-lo em pensamento, palavra e obra; e que ele seja agradado conduzir e ordenar todas as coisas para a sua própria glória.', ARRAY['Pai Nosso','santificação do nome','glorificação'], ARRAY['Salmo 67.2-3','Romanos 11.36'], 51, '{"full_seed":true}'::jsonb),
    (v_doc_id, 52, '52', 'Para quê pedimos na segunda petição?', 'Na segunda petição, que é "Venha o teu reino", reconhecendo nós mesmos e toda a humanidade como sendo naturalmente sob o domínio do pecado e de Satanás, oramos que o reino do pecado e de Satanás possa ser destruído, e que o evangelho se propague, e que os judeus sejam chamados, e que a plenitude dos gentios possa vir ao seu reino, que o Senhor Jesús possa retornar no segundo advento, e que o reino da gloria possa ser acelerado.', ARRAY['Pai Nosso','reino de Deus','missão','escatologia'], ARRAY['Romanos 10.1','João 17.9','Apocalipse 22.20'], 52, '{"full_seed":true}'::jsonb),
    (v_doc_id, 53, '53', 'Para quê pedimos na terceira petição?', 'Na terceira petição, que é "Seja feita a tua vontade, assim na terra como no céu", reconhecendo que por natureza somos totalmente avessos a conhecer e obedecer à vontade de Deus e plenamente incapazes e indispostos a ela, assim como para realizar qualquer parte dela; oramos que Deus, por seu Espírito, remova de nós e de outros toda a ignorância, fraqueza e disposição ao mal, e pelas suas graças nos faça capaz e dispostos a saber, desejar e fazer a sua vontade em todas as coisas, como os anjos fazem no céu.', ARRAY['Pai Nosso','vontade de Deus','obediência'], ARRAY['Salmo 119.36','Atos 21.14'], 53, '{"full_seed":true}'::jsonb),
    (v_doc_id, 54, '54', 'Para quê pedimos na quarta petição?', 'Na quarta petição, que é "O pão nosso de cada dia nos dá hoje", reconhecendo que, em Adão e por nossos próprios pecados, merecemos privação de todas as bênçãos externas de Deus, que não podemos prover nossas próprias necessidades, e que a mais comum dos dons nos é do favor de Deus; pedimos a boa dádiva de Deus de uma porção conveniente de bênçãos desta vida, e que desfrutemos do favor e bênção dele nelas, e que possamos continuar em seu sustento e bênção temporal.', ARRAY['Pai Nosso','providência','necessidades','pão'], ARRAY['Provérbios 30.8-9','1 Timóteo 4.4-5'], 54, '{"full_seed":true}'::jsonb),
    (v_doc_id, 55, '55', 'Para quê pedimos na quinta petição?', 'Na quinta petição, que é "E perdoa-nos as nossas dívidas, assim como nós perdoamos os nossos devedores", reconhecendo que nos e todos os outros somos culpados tanto de pecado original como de pecado atual, e portanto nos tornamos devedores ao justo julgamento de Deus; oramos que Deus, por sua graça livre e pela justiça de Cristo nos absolva e perdoe todos os nossos pecados, e que por sua graça nos habilite e disponha a perdoar cordialmente a outros pelas ofensas deles.', ARRAY['Pai Nosso','perdão','graça','misericórdia'], ARRAY['Salmo 51.1-2','Mateus 18.35'], 55, '{"full_seed":true}'::jsonb),
    (v_doc_id, 56, '56', 'Para quê pedimos na sexta petição?', 'Na sexta petição, que é "E não nos deixes cair em tentação, mas livra-nos do mal", reconhecendo que o Deus mais sábio, mais justo e mais gracioso, por razões de sua santa soberania pode nos enviar provação; e que Satanás, o mundo e a carne nos ameaçam continuamente; pedimos que Deus preserve-nos de ser tentado ao pecado por qualquer das tentações; e que se tentados, vença-nos de todo o lado, e nos suporte em todas as tentações; que nos dê graça para resistir ao tentador e permanecer firme perante ele; e que nos livre de tudo mal, para que o conjunto de todos nossas orações seja aceito.', ARRAY['Pai Nosso','tentação','perseverança','Satanás'], ARRAY['1 Coríntios 10.13','Mateus 26.41'], 56, '{"full_seed":true}'::jsonb),
    (v_doc_id, 57, '57', 'O que a conclusão da oração do Senhor nos ensina?', 'A conclusão da oração do Senhor, que é "Porque teu é o reino, e o poder, e a glória, para sempre, Amém", nos ensina a encorajarmo-nos na oração e no nosso louvor a Deus, elevando-lhe a glória do reino, do poder e da glória, pedindo-lhe, e certificando nossa fé dele; e, para expressar nosso desejo ardente e segurança de ser ouvidos, dizemos, Amém.', ARRAY['Pai Nosso','doxologia','amém','confiança'], ARRAY['1 Crônicas 29.10-13','Apocalipse 22.20'], 57, '{"full_seed":true}'::jsonb),
    (v_doc_id, 58, '58', 'Quantas partes tem a lei de Deus?', 'A lei de Deus tem duas partes: os Dez Mandamentos e outros preceitos que os explicam.', ARRAY['lei','Dez Mandamentos'], ARRAY['Deuteronômio 4.13','Mateus 22.37-40'], 58, '{"full_seed":true}'::jsonb),
    (v_doc_id, 59, '59', 'O que é exigido ao homem pela lei de Deus?', 'É exigido ao homem pela lei de Deus que ele obedecca a ela; creia nela e com fé obedça a todos os mandamentos dela, que ame a Deus e seu próximo, e as suas vontades.', ARRAY['lei','obediência','amor'], ARRAY['Deuteronômio 6.25','Mateus 22.37-40'], 59, '{"full_seed":true}'::jsonb),
    (v_doc_id, 60, '60', 'Está a lei dos Dez Mandamentos ainda em vigor para os cristãos?', 'A lei moral obriga a todos, tanto por sua obediência a ela quanto pela maldição dela, a todos os homens em todos os tempos, sejam crentes ou incrédulos; mas não pela mesma maneira, pois os crentes, embora não estejam sob ela como uma aliança de obras para justificação ou condenação, estão, contudo, sujeitos a ela como uma regra de vida.', ARRAY['lei','Dez Mandamentos','cristãos','regra de vida'], ARRAY['Romanos 3.20','Gálatas 3.13','Romanos 13.8-10'], 60, '{"full_seed":true}'::jsonb),
    (v_doc_id, 61, '61', 'Para que serve a lei moral para os crentes?', 'A lei moral, embora os crentes não estejam sob ela como uma aliança de obras, é útil a eles, assim como a outros; de vez que como uma regra de vida, informando-os da vontade de Deus, e seu dever, ela os dirige e obriga a viver e a conformar-se com a mesma; descobrindo-lhes também a maneira pecaminosa de suas naturezas, corações e vidas, de modo a fazê-los humilhar-se ainda mais, a odiarem mais o pecado, e mais desejarem a Cristo e a perfeição de sua obediência; ele é útil para eles enquanto ameaça, tanto para revelar o que mesmo os seus pecados merecem, e as aflições que podem esperar por eles, embora libertados da maldição e rigor da mesma.', ARRAY['lei','terceiro uso da lei','santificação'], ARRAY['Romanos 7.7','Tiago 1.23-25','Gálatas 3.24'], 61, '{"full_seed":true}'::jsonb),
    (v_doc_id, 62, '62', 'Qual é o fim geral dos Dez Mandamentos?', 'O fim geral dos Dez Mandamentos é que saibamos os nossos deveres para com Deus e o nosso próximo, e mais a necessidade que temos de buscar mais santidade e conformidade com a lei de Deus em Cristo.', ARRAY['Dez Mandamentos','deveres','santidade'], ARRAY['Mateus 22.37-40','Romanos 10.4'], 62, '{"full_seed":true}'::jsonb),
    (v_doc_id, 63, '63', 'Qual é a súmula dos Dez Mandamentos?', 'A súmula dos Dez Mandamentos é: amar ao Senhor nosso Deus de todo nosso coração, de toda nossa alma, de todas as nossas forças e de todo nosso entendimento; e ao nosso próximo como a nós mesmos.', ARRAY['grande mandamento','amor a Deus','amor ao próximo'], ARRAY['Mateus 22.37-40'], 63, '{"full_seed":true}'::jsonb),
    (v_doc_id, 64, '64', 'O que é o prefácio dos Dez Mandamentos?', 'O prefácio dos Dez Mandamentos está contido nestas palavras: "Eu sou o Senhor teu Deus, que te tirei da terra do Egito, da casa da servidão." No qual Deus manifesta que ele é o Senhor, de domínio soberano e autoridade absoluta, que tem tanto o direito de estabelecer lei e obrigação de obediência como o poder de forçá-la, como sendo ele Deus universal e supremo; que ele é Deus, em concorrência a todos os deuses falsos; de relação covariada e amor, ao ser o Deus de seu povo; e que, sendo-os o redentor da escravidão, eles estão assim obrigados a lhe obedecer.', ARRAY['Dez Mandamentos','prefácio','soberania','redenção'], ARRAY['Êxodo 20.2'], 64, '{"full_seed":true}'::jsonb),
    (v_doc_id, 65, '65', 'O que é proibido no primeiro mandamento?', 'O primeiro mandamento proíbe a negação, ou o não adorar e glorificar o único Deus verdadeiro como Deus, e Senhor, e nosso Deus; e o dar culto ou adoração a qualquer outro que não seja ele.', ARRAY['1º mandamento','idolatria','ateísmo'], ARRAY['Salmo 14.1','Romanos 1.20-21'], 65, '{"full_seed":true}'::jsonb),
    (v_doc_id, 66, '66', 'O que é o dever requerido no primeiro mandamento?', 'O dever requerido no primeiro mandamento é conhecer e reconhecer a Deus como o único único e verdadeiro Deus, e o nosso Deus; e consequentemente adorá-lo, amá-lo, desejá-lo, temê-lo; crer nele, confiar nele, esperar nele, gozar dele; e com todo o coração servir, obedecer e louvar a ele; convocar o seu nome e lhe dar toda a honra e glória.', ARRAY['1º mandamento','adoração','amor a Deus','confiança'], ARRAY['1 Crônicas 28.9','Deuteronômio 26.17'], 66, '{"full_seed":true}'::jsonb),
    (v_doc_id, 67, '67', 'Que mandamento é o segundo?', 'O segundo mandamento proíbe a adoração a Deus por imagens, ou qualquer outra invenção, não prescrita em sua Palavra; e a adoração de qualquer criatura.', ARRAY['2º mandamento','imagens','adoração regulada'], ARRAY['Êxodo 20.4-6'], 67, '{"full_seed":true}'::jsonb),
    (v_doc_id, 68, '68', 'O que é o dever requerido no segundo mandamento?', 'O dever requerido no segundo mandamento é receber, observar e guardar pura e inteira toda a adoração e ordenanças religiosas que Deus estabeleceu em sua Palavra; expressamente, a oração e a ação de graças em nome de Cristo; a leitura, a pregação e o ouvir a Palavra de Deus; a administração e o recebimento dos sacramentos; o governo da Igreja; o cuidado ministerial; e o dinheiro de graças da Igreja.', ARRAY['2º mandamento','adoração','ordenanças','Igreja'], ARRAY['Deuteronômio 32.46-47','Mateus 28.20'], 68, '{"full_seed":true}'::jsonb),
    (v_doc_id, 69, '69', 'O que é proibido no terceiro mandamento?', 'O terceiro mandamento proíbe todo abuso de qualquer coisa pela qual Deus se representa, ou se manifesta a si mesmo; especialmente de seu nome, seus atributos, suas ordenanças, a Palavra, os sacramentos, a oração, os juramentos, os votos, seus elogios e o evangelho.', ARRAY['3º mandamento','nome de Deus','blasfêmia'], ARRAY['Malaquias 1.12-13','Mateus 5.33-37'], 69, '{"full_seed":true}'::jsonb),
    (v_doc_id, 70, '70', 'O que é justificação?', 'A justificação é um ato da graça livre de Deus para os pecadores, no qual ele perdoa todos os seus pecados, aceita-os e os considera justos aos seus olhos; não por qualquer coisa realizada neles, ou por eles, mas somente pela perfeita obediência e plena satisfação de Cristo, por eles imputada pelo Deus e recebida por fé somente.', ARRAY['justificação','imputação','graça','fé'], ARRAY['Romanos 3.22-25','Romanos 4.5'], 70, '{"full_seed":true}'::jsonb),
    (v_doc_id, 71, '71', 'Como a justificação é o ato livre de Deus?', 'Embora Cristo, sendo dado pelo Pai, tenha por si mesmo pago o preço completo para os justificados e haja dado plena satisfação à lei; contudo, em razão de que Deus aceitou seus filhos em lugar deles, e a obediência e satisfação de Cristo a ele, e não deles; e também que Cristo e seus méritos sendo aceitos por eles, eles não tiveram nada a dar neles: a justificação deles é a graça livre de Deus.', ARRAY['justificação','graça','mérito de Cristo','imputação'], ARRAY['Romanos 3.24','Efésios 1.7'], 71, '{"full_seed":true}'::jsonb),
    (v_doc_id, 72, '72', 'O que é fé justificadora?', 'A fé justificadora é a graça salvadora, pela qual o pecador, sendo convicto de si mesmo por que está perdido e condenado, e vendo que não há nada que ele possa fazer fora de Cristo para livrá-lo, recebe todo o Cristo como profeta, sacerdote e rei; e descansa sobre ele somente para justificação, santificação e vida eterna, pela virtude do pacto de graça.', ARRAY['fé justificadora','Cristo','aliança de graça'], ARRAY['Atos 16.31','João 1.12','Filipenses 3.9'], 72, '{"full_seed":true}'::jsonb),
    (v_doc_id, 73, '73', 'Como a fé justifica o pecador na vista de Deus?', 'A fé justifica o pecador na vista de Deus não como ele pensa na fé ou em qualquer ato da mesma; mas somente enquanto é um instrumento pelo qual ele recebe e aplica a Cristo e sua justiça.', ARRAY['fé','justificação','instrumento'], ARRAY['João 3.16','Filipenses 3.9','Gálatas 2.16'], 73, '{"full_seed":true}'::jsonb),
    (v_doc_id, 74, '74', 'O que é adoção?', 'Adoção é um ato da graça livre de Deus, na e para o benefício de seu único Filho Jesus Cristo, pelo qual todos os que são justificados são recebidos no número de seus filhos, recebem o Espírito de adoção, têm acesso ao trono de graça com ousadia, são habilitados a clamar, Aba, Pai; são piedados, protegidos, providos e disciplinados por ele como pelo Pai; nunca são lançados fora, mas selados para o dia da redenção, e herdeiros de todas as promessas como co-herdeiros com Cristo.', ARRAY['adoção','filiação divina','Espírito Santo','herança'], ARRAY['João 1.12','Romanos 8.15-17'], 74, '{"full_seed":true}'::jsonb),
    (v_doc_id, 75, '75', 'O que é santificação?', 'A santificação é uma obra da graça de Deus, pela qual aqueles que são regenerados são ainda mais renovados em toda a sua natureza, e têm a dominação do pecado destruída, e o desejo mais e mais enfraquecido e morto, e eles mais e mais enaltecidos e fortalecidos em toda graça salvadora, para a prática da verdadeira santidade, sem a qual nenhum homem verá ao Senhor.', ARRAY['santificação','renovação','mortificação','vivificação'], ARRAY['1 Tessalonicenses 5.23','2 Tessalonicenses 2.13','Hebreus 12.14'], 75, '{"full_seed":true}'::jsonb),
    (v_doc_id, 76, '76', 'O que é arrependimento para vida?', 'O arrependimento para vida é uma graça salvadora que trabalha no coração do pecador uma verdadeira percepção de seu pecado, e apreensão da misericórdia de Deus em Cristo; pelo qual, com enorme tristeza e ódio do pecado, e com uma boa esperança de perdão, ele se vira do pecado para Deus; com intenção plena e esforço de nova obediência.', ARRAY['arrependimento','graça','obediência','conversão'], ARRAY['Atos 11.18','Zacarias 12.10'], 76, '{"full_seed":true}'::jsonb),
    (v_doc_id, 77, '77', 'Em que diferem justificação e santificação?', 'Embora santificação seja inseparável da justificação; contudo eles diferem: em que Deus na justificação imputa a perfeita obediência de Cristo; na santificação seu Espírito infunde graça, e habilita ao exercício da mesma; na primeira o pecado é perdoado; na outra é subjugado: o que é igual em todos os crentes em justificação; na santificação é desigual em todos, e nessa vida não é perfeita em nenhum.', ARRAY['justificação','santificação','diferença'], ARRAY['Gálatas 2.16','Romanos 6.4','Tito 3.5'], 77, '{"full_seed":true}'::jsonb),
    (v_doc_id, 78, '78', 'De onde surgem a imperfeição e os pecados que permanecem nos regenerados?', 'A imperfeição e os pecados que permanecem nos regenerados surgem da parte dos restos do pecado que ainda habita neles, e das tentações do mundo e de Satanás.', ARRAY['imperfeição','pecado remanescente','tentação'], ARRAY['Marcos 14.66-72','Gálatas 2.11-12'], 78, '{"full_seed":true}'::jsonb),
    (v_doc_id, 79, '79', 'Podem os verdadeiros crentes ser irreversivelmente caídos da graça?', 'Os verdadeiros crentes, em virtude do amor imutável de Deus, sua aliança, sua eleição, a indwelling e intercessão do Espírito Santo, e a natureza do pacto de graça; a partir do qual o pecado não torna aqueles que uma vez verdadeiramente creram, nunca totalmente nem finalmente abandonados, mas certamente salvos para a gloria eterna.', ARRAY['perseverança','segurança','amor de Deus','eleição'], ARRAY['João 10.28-29','Romanos 8.35-39'], 79, '{"full_seed":true}'::jsonb),
    (v_doc_id, 80, '80', 'Os verdadeiros crentes podem cair em apostasia?', 'Crentes verdadeiros podem ter a asseguração de sua salvação abalada, diminuída e intermitida; tanto por suas próprias negligências e pecados, pelo qual contristam e entristam o Espírito Santo, por caírem em algum pecado especial que ferindo sua consciência e contristando o Espírito; por serem tentados e assim entrarem em nuvem escura e Deus não deles se abstenha de luz de sua face.', ARRAY['asseguração','queda temporária','Espírito Santo'], ARRAY['Efésios 4.30','Salmo 51.8-12'], 80, '{"full_seed":true}'::jsonb),
    (v_doc_id, 81, '81', 'O que são os benefícios que acompanham ou procedem da justificação, adoção e santificação?', 'Os benefícios que acompanham ou procedem da justificação, adoção e santificação são: certeza do amor de Deus, paz de consciência, alegria no Espírito Santo, aumento de graça, perseverança nela até ao fim.', ARRAY['asseguração','paz','alegria','perseverança'], ARRAY['Romanos 5.1-5','1 Pedro 1.5'], 81, '{"full_seed":true}'::jsonb),
    (v_doc_id, 82, '82', 'O que é o pacto de graça?', 'O pacto de graça é feito com os pecadores em Cristo; em que Deus livremente oferece e doa vida e salvação por Jesus Cristo; requerendo deles fé nele, para que sejam salvos, e prometendo-lhes dar o Espírito Santo a todos os seus eleitos para torná-los dispostos e capazes a crer.', ARRAY['aliança de graça','salvação','fé','eleição'], ARRAY['Gênesis 2.17','Gálatas 3.11'], 82, '{"full_seed":true}'::jsonb),
    (v_doc_id, 83, '83', 'Que são os membros do pacto de graça?', 'Os membros do pacto de graça são: todos e somente aqueles que são eleitos; pois estes somente, de todos os tempos, são feitos membros do pacto de graça pela graça de Cristo.', ARRAY['aliança de graça','eleição','membros'], ARRAY['João 10.3-4'], 83, '{"full_seed":true}'::jsonb),
    (v_doc_id, 84, '84', 'Qual é a condição do estado dos homens depois de morte?', 'Depois da morte, a alma de todos os homens é separada de seus corpos, as almas dos justos sendo aperfeiçoadas em santidade, imediatamente passam para a glória; os corpos deles, ainda sendo unidos a Cristo, repousam nas sepulturas até a ressurreição; ao passo que as almas dos maus são lançadas ao inferno, onde ficam em tormentos e trevas intensas, reservadas ao julgamento do grande dia.', ARRAY['morte','estado intermediário','alma','ressurreição'], ARRAY['Hebreus 12.23','Filipenses 1.23','Atos 1.25'], 84, '{"full_seed":true}'::jsonb),
    (v_doc_id, 85, '85', 'O que faremos com os mortos?', 'Haverá uma ressurreição geral dos mortos, tanto justos como injustos; quando os que estão no sepulcro ouvirão a voz do Filho de Deus; os que fizeram o bem sairão para a ressurreição da vida, e os que fizeram o mal para a ressurreição da condenação.', ARRAY['ressurreição geral','julgamento','escatologia'], ARRAY['João 5.28-29','1 Tessalonicenses 4.15-16'], 85, '{"full_seed":true}'::jsonb),
    (v_doc_id, 86, '86', 'O que deve esperar-se no Dia do Juízo?', 'No Dia do Juízo haverá uma revelação geral e julgamento justo de todos os anjos e de todos os seres humanos que tenham já vivido, para manifestar a glória de Deus, misericórdia e justiça, e a exaltar ele e a confundir e condenar os reprovados.', ARRAY['julgamento final','anjos','condenação','gloria de Deus'], ARRAY['Mateus 25.31-46','Romanos 14.10-12'], 86, '{"full_seed":true}'::jsonb),
    (v_doc_id, 87, '87', 'O que devemos crer acerca da ressurreição?', 'Devemos crer que haverá uma ressurreição dos corpos dos mortos, tanto dos justos como dos injustos, ao fim do mundo.', ARRAY['ressurreição','corpo','escatologia'], ARRAY['João 5.28-29','Atos 24.15'], 87, '{"full_seed":true}'::jsonb),
    (v_doc_id, 88, '88', 'Qual será o estado dos eleitos após a ressurreição e o julgamento?', 'Após a ressurreição e o julgamento, os eleitos serão abertamente absolvidos, recebidos a favor, honrados e glorificados em corpo e alma, plena e perfeitamente gozados de Deus e feitos perfeitamente bem-aventurados na plena visão de Deus; para viver e reinar com ele para sempre; que é a perfeita e plena comunhão, que o povo de Deus terá com Deus Pai, Filho e Espírito Santo na glória celestial.', ARRAY['glorificação','visão beatífica','vida eterna','comunhão com Deus'], ARRAY['1 Coríntios 13.12','1 Tessalonicenses 4.17'], 88, '{"full_seed":true}'::jsonb),
    (v_doc_id, 89, '89', 'Qual será o estado dos maus após a morte?', 'Após o dia do juízo os maus, que não conhecem a Deus e não obedecem ao evangelho de Jesus Cristo, serão lançados às trevas eternas; e serão punidos com perdição eterna do rosto do Senhor, e com a glória de seu poder.', ARRAY['condenação','inferno','perdição','castigo eterno'], ARRAY['2 Tessalonicenses 1.8-9','Mateus 25.41'], 89, '{"full_seed":true}'::jsonb),
    (v_doc_id, 90, '90', 'O que é o dever do homem para com Deus que as Escrituras revelam?', 'O dever que as Escrituras principalmente requerem do homem é a obediência à sua lei revelada.', ARRAY['dever','lei','obediência'], ARRAY['Miquéias 6.8','1 Samuel 15.22'], 90, '{"full_seed":true}'::jsonb),
    (v_doc_id, 91, '91', 'O que é a lei de Deus?', 'A lei de Deus é a vontade revelada de Deus, dando ao homem uma regra de seu dever: ela está escrita em seus corações por criação, mas também foi expressa, pelo Espírito Santo, em dez mandamentos.', ARRAY['lei','vontade de Deus','criação','Dez Mandamentos'], ARRAY['Romanos 2.14-15','Deuteronômio 4.13'], 91, '{"full_seed":true}'::jsonb),
    (v_doc_id, 92, '92', 'O que é a lei dos Dez Mandamentos?', 'A lei dos Dez Mandamentos é aquela que Deus proclamou na montanha de Sinai no fogo e em nuvens e trevas e tempestade, e que ele escreveu em duas tábuas de pedra, que aqui se resume:', ARRAY['Dez Mandamentos','Sinai','lei'], ARRAY['Êxodo 20.1-17','Deuteronômio 5.6-21'], 92, '{"full_seed":true}'::jsonb),
    (v_doc_id, 93, '93', 'Como os Dez Mandamentos estão divididos?', 'Os Dez Mandamentos estão divididos em duas tábuas: a primeira contendo nossos deveres para Deus, a segunda nossos deveres para com o homem.', ARRAY['Dez Mandamentos','duas tábuas','amor a Deus','amor ao próximo'], ARRAY['Mateus 22.37-40'], 93, '{"full_seed":true}'::jsonb),
    (v_doc_id, 94, '94', 'O que é o dever requerido no quarto mandamento?', 'O dever requerido no quarto mandamento é guardar santo para Deus aquele exato dia de sete, sendo em nossa era o primeiro dia da semana, que é o dia do Senhor, ou o sábado cristão; cessar nele de todo trabalho, exceto obras de necessidade ou misericórdia; restringir tudo o pensamento, palavras e ações mundanas.', ARRAY['4º mandamento','Dia do Senhor','sábado','descanso'], ARRAY['Êxodo 20.8-11','Levítico 23.3'], 94, '{"full_seed":true}'::jsonb),
    (v_doc_id, 95, '95', 'O que é a razão para o dever do quarto mandamento?', 'A razão do quarto mandamento está expressamente nele: primeiro, porque Deus em seis dias fez os céus e a terra, o mar e tudo que neles há, e descansou no sétimo dia: portanto, o Senhor abençoou o dia de sábado e o santificou.', ARRAY['4º mandamento','criação','descanso de Deus'], ARRAY['Êxodo 20.11'], 95, '{"full_seed":true}'::jsonb),
    (v_doc_id, 96, '96', 'O que é proibido no quarto mandamento?', 'O quarto mandamento proíbe a omissão ou negligência descuidada dos deveres requeridos; e o profanar o dia por ociosidade, por fazer aquilo que em si é pecaminoso; e por todo trabalho, palavras e pensamentos desnecessários, acerca de nossos empregos mundanos ou recreações.', ARRAY['4º mandamento','profanação','sábado'], ARRAY['Ezequiel 22.26','Amós 8.5'], 96, '{"full_seed":true}'::jsonb),
    (v_doc_id, 97, '97', 'O que é a aliança de graça?', 'O pacto de graça é feito com os pecadores em Cristo, no qual Deus livremente oferece e dá vida e salvação por Jesus Cristo, para aqueles que creem nele; requerendo deles fé nele, para que sejam salvos; e prometendo-lhes dar seu Espírito Santo a todos seus eleitos, para torná-los capazes e dispostos a crer.', ARRAY['aliança de graça','fé','eleição','salvação'], ARRAY['João 3.16','Hebreus 8.10'], 97, '{"full_seed":true}'::jsonb),
    (v_doc_id, 98, '98', 'O que foi a aliança de graça administrada no tempo da lei?', 'A aliança de graça foi administrada no tempo da lei por promessas, profecias, sacrifícios, circuncisão, o cordeiro pascal, e outras figuras e ordenanças dadas ao povo dos judeus, todas prefigurando Cristo que estava por vir; suficiente e eficaz para o propósito de instruir e edificar os eleitos naquele tempo, pela fé no Messias prometido.', ARRAY['aliança de graça','Antigo Testamento','tipos','Moisés'], ARRAY['Gálatas 3.7-9','Hebreus 9.1-10'], 98, '{"full_seed":true}'::jsonb)
  ON CONFLICT (document_id, number) DO UPDATE SET
    number_label    = EXCLUDED.number_label,
    question        = EXCLUDED.question,
    answer          = EXCLUDED.answer,
    doctrine_tags   = EXCLUDED.doctrine_tags,
    bible_references = EXCLUDED.bible_references,
    sort_order      = EXCLUDED.sort_order,
    metadata        = public.lampas_confessional_questions.metadata || EXCLUDED.metadata;

  RAISE NOTICE 'Catecismo Maior de Westminster (Parte 1 — Q1-98): inseridas/atualizadas.';
END;
$$;
