-- Catecismo Maior de Westminster — Parte 2 (Perguntas 99–196)
-- Pré-requisito: migration 021 executada e seed-cmw-maior-parte1.sql executado
-- Execute no Supabase SQL Editor

DO $$
DECLARE
  v_doc_id uuid;
BEGIN
  SELECT id INTO v_doc_id
  FROM public.lampas_confessional_documents
  WHERE slug = 'catecismo-maior-westminster';

  IF v_doc_id IS NULL THEN
    RAISE EXCEPTION 'Documento catecismo-maior-westminster não encontrado.';
  END IF;

  INSERT INTO public.lampas_confessional_questions
    (document_id, number, number_label, question, answer, doctrine_tags, bible_references, sort_order, metadata)
  VALUES
    (v_doc_id, 99, '99', 'O que é a aliança de graça administrada no tempo do evangelho?', 'A aliança de graça é administrada no tempo do evangelho, em que Cristo se manifestou, nas pregações da Palavra, e na administração do Batismo e da Ceia do Senhor; nos quais a graça e salvação são apresentadas em mais plenitude, evidência e eficácia, a todas as nações.', ARRAY['aliança de graça','Novo Testamento','sacramentos','pregação'], ARRAY['Marcos 16.15-16','1 Coríntios 11.23-26'], 99, '{"full_seed":true}'::jsonb),
    (v_doc_id, 100, '100', 'O que é o dever especial requerido do homem no quinto mandamento?', 'O dever especial requerido no quinto mandamento é preservar a honra e cumprir os deveres que temos nas relações de superior, inferior e igual.', ARRAY['5º mandamento','autoridade','honra'], ARRAY['Efésios 5.21-22','Romanos 13.1','Efésios 6.1'], 100, '{"full_seed":true}'::jsonb),
    (v_doc_id, 101, '101', 'O que é o dever de inferiores para seus superiores?', 'O dever dos inferiores para com os seus superiores é o dever de tudo ouvir, amar, honrar, ajudar e obedecer a eles com humildade e docilidade; orar por eles e graças render por eles; imitá-los naquilo que é bem; e suportar com paciência as fraquezas deles e encobrir seus defeitos, para que não sejam desonrados.', ARRAY['5º mandamento','obediência','autoridade'], ARRAY['Efésios 6.1-2','Hebreus 13.17'], 101, '{"full_seed":true}'::jsonb),
    (v_doc_id, 102, '102', 'O que é o dever dos superiores para com os seus inferiores?', 'O dever dos superiores para com os seus inferiores é amar-lhes, orar por eles, instruí-los, aconselhá-los e repreendê-los; prover para seu bem-estar, e, fazendo-o, defender e protegê-los, concedendo-lhes todas as bênçãos que estejam ao seu alcance; recompensando e honrando os que fazem o bem, e punindo os que fazem o mal.', ARRAY['5º mandamento','autoridade','cuidado','liderança'], ARRAY['Efésios 6.4','1 Tessalonicenses 2.11-12'], 102, '{"full_seed":true}'::jsonb),
    (v_doc_id, 103, '103', 'O que é o pecado proibido no quinto mandamento?', 'O pecado proibido no quinto mandamento é o de negligenciar, tratar indignamente, ou desprezar a pessoas dos nossos superiores, resistir suas ordens legítimas, ridicularizá-los, desonrá-los; e os pecados dos superiores ao descurar de seus deveres para com seus inferiores.', ARRAY['5º mandamento','desonra','rebeldia'], ARRAY['Mateus 15.4-6','Romanos 13.2'], 103, '{"full_seed":true}'::jsonb),
    (v_doc_id, 104, '104', 'O que são os deveres requeridos no sexto mandamento?', 'Os deveres requeridos no sexto mandamento são: todo o cuidado razoável e esforço legítimo para preservar a nossa própria vida e a do próximo; resistir a todos os pensamentos e propósitos, a domar todas as paixões, evitar todas as ocasiões, tentações e práticas que tendam à destruição injusta de qualquer vida.', ARRAY['6º mandamento','vida','preservação','paz'], ARRAY['Efésios 5.29','1 Reis 18.4'], 104, '{"full_seed":true}'::jsonb),
    (v_doc_id, 105, '105', 'O que é proibido no sexto mandamento?', 'O pecado proibido no sexto mandamento é o tirar a nossa própria vida ou a de nosso próximo, exceto nos casos de justiça pública, guerra legal ou necessária defesa; a negligência ou o descuido do cuidado de nossa própria vida, bem como todo o uso injusto de outros meios que tendam à destruição da vida do próximo.', ARRAY['6º mandamento','homicídio','suicídio'], ARRAY['Gênesis 9.6','Mateus 5.22'], 105, '{"full_seed":true}'::jsonb),
    (v_doc_id, 106, '106', 'O que é o dever requerido no sétimo mandamento?', 'O dever requerido no sétimo mandamento é a castidade em corpo, mente, afetos, palavras e comportamento; e a preservação disso em nós mesmos e nos outros; vigiar os olhos e demais sentidos; temperança, manutenção do matrimônio, amor conjugal; e compor uma santa conduta no casamento e fora dele, evitando tentações e companhias impuras, suprimindo pensamentos lascivos.', ARRAY['7º mandamento','castidade','matrimônio','pureza'], ARRAY['1 Coríntios 7.2-3','1 Tessalonicenses 4.3-5'], 106, '{"full_seed":true}'::jsonb),
    (v_doc_id, 107, '107', 'O que é proibido no sétimo mandamento?', 'O pecado proibido no sétimo mandamento e todos os pensamentos, palabras e atos impudicos; adultério, fornicação, estupro, incesto, sodomia e todas as práticas impuras, bem como o encorajar, tolerar, a companhia e o escovar-se delas; ociosidade, embriaguez e assuntos lascivos; conversas impuras, e todas as outras provocações ao pecado.', ARRAY['7º mandamento','adultério','impureza','fornicação'], ARRAY['Mateus 15.19','1 Coríntios 6.9-10'], 107, '{"full_seed":true}'::jsonb),
    (v_doc_id, 108, '108', 'O que são os deveres requeridos no oitavo mandamento?', 'Os deveres requeridos no oitavo mandamento são: verdade, fidelidade e justiça no trato com outros; dando a cada um o que lhe é devido, restituindo bens obtidos injustamente; empenho e parcimônia para ser ricos em boas obras; dar liberalmente para os pobres e para o sustento dos ministros de Cristo; procurando a justiça contra a fraude e a opressão.', ARRAY['8º mandamento','honestidade','justiça','generosidade'], ARRAY['Romanos 13.7','Levítico 25.35','1 Coríntios 16.2'], 108, '{"full_seed":true}'::jsonb),
    (v_doc_id, 109, '109', 'O que é proibido no oitavo mandamento?', 'O pecado proibido no oitavo mandamento é furto, roubo, sequestro, receber e ocultar bens roubados; trapaça em negócios; usura e suborno; cobrança fraudulenta; desonestidade em medidas e balancas, qualquer injustiça nas transações legais, comércio ou trabalho; ganho injusto; dissipação de nossas próprias riquezas e a delas fazer uso indevido.', ARRAY['8º mandamento','roubo','fraude','injustiça'], ARRAY['1 Coríntios 6.10','Isaías 5.8','Provérbios 11.1'], 109, '{"full_seed":true}'::jsonb),
    (v_doc_id, 110, '110', 'O que são os deveres requeridos no nono mandamento?', 'Os deveres requeridos no nono mandamento são o cuidado e o respeito para o bem do bom nome de nosso próximo, bem como de nosso próprio; dar verdade a favor da verdade quando necessário; guardar as coisas confidenciais; falar livremente e com decência; defender as inocentes das acusações.', ARRAY['9º mandamento','verdade','reputação','honestidade'], ARRAY['Efésios 4.15','Zacarias 8.16'], 110, '{"full_seed":true}'::jsonb),
    (v_doc_id, 111, '111', 'O que é proibido no nono mandamento?', 'O pecado proibido no nono mandamento é tudo que é prejudicial à verdade ou ao bom nome de nosso próximo: dar falso testemunho, subornar falsos testemunhos; aparentar uma causa má; falar o mal de quem está ausente; caluniá-lo com acusações falsas; fazer exageros; divulgar falhas e faltas desnecessariamente; fomentar cismas e partidos.', ARRAY['9º mandamento','calúnia','mentira','difamação'], ARRAY['Provérbios 19.5','Salmo 15.3'], 111, '{"full_seed":true}'::jsonb),
    (v_doc_id, 112, '112', 'O que é o dever requerido no décimo mandamento?', 'O dever requerido no décimo mandamento é tal disposição de espírito que nos satisfaça com a nossa própria condição, com alegria e caridade para com o nosso próximo e tudo o que lhe é próprio.', ARRAY['10º mandamento','contentamento','amor ao próximo'], ARRAY['Hebreus 13.5','1 Timóteo 6.6'], 112, '{"full_seed":true}'::jsonb),
    (v_doc_id, 113, '113', 'O que é proibido no décimo mandamento?', 'O pecado proibido no décimo mandamento é todo o descontentamento com a nossa própria condição; o ter inveja, ou pesar pelo bem do nosso próximo; todos os desejos e esforços indevidos depois de qualquer coisa que é do próximo.', ARRAY['10º mandamento','cobiça','inveja','descontentamento'], ARRAY['1 Coríntios 10.10','Gálatas 5.26'], 113, '{"full_seed":true}'::jsonb),
    (v_doc_id, 114, '114', 'O que são os pecados contra o primeiro mandamento?', 'Os pecados contra o primeiro mandamento são: ateísmo, em negar ou não crer na existência de Deus; idolatria, em fazer ou ter qualquer outro deus; ignorância, esquecer, desestimar, desonrar e maldizer a Deus; o temor, o amor, a delícia ou a confiança supersticiosa ou excessiva em qualquer coisa como nosso deus; divinação, encantamento e outras práticas de espíritos maus.', ARRAY['1º mandamento','ateísmo','idolatria','feitiçaria'], ARRAY['Salmo 14.1','Romanos 1.21','Êxodo 22.18'], 114, '{"full_seed":true}'::jsonb),
    (v_doc_id, 115, '115', 'O que são os pecados contra o segundo mandamento?', 'Os pecados contra o segundo mandamento são toda a adoração de Deus por imagens, de qualquer espécie; fazer qualquer representação de Deus, qualquer criatura para o propósito de adoração; todas as superstições em culto, como celebração de festas, e o uso de imagens e relíquias, e coisas semelhantes; toda a adoração contrária à Palavra.', ARRAY['2º mandamento','idolatria','superstição','imagens'], ARRAY['Êxodo 32.8','Deuteronômio 12.32'], 115, '{"full_seed":true}'::jsonb),
    (v_doc_id, 116, '116', 'O que são os pecados contra o terceiro mandamento?', 'Os pecados contra o terceiro mandamento são: o não tomar o nome do Senhor; errar sobre os atributos de Deus; impor medo por falsa doutrina e práticas que desonram o nome divino; murmúrio e impiedade contra os julgamentos de Deus; perverter, abusar ou profanar a Palavra de Deus; fazer mau uso do nome de Deus em juízo ou em discurso usual; a vã jura; prestar juramento e voto levianamente.', ARRAY['3º mandamento','blasfêmia','juramento','nome de Deus'], ARRAY['Malaquias 2.2','Êxodo 20.7'], 116, '{"full_seed":true}'::jsonb),
    (v_doc_id, 117, '117', 'O que é um juramento lícito?', 'Um juramento lícito é parte do culto religioso, em que a pessoa jurando pede a Deus, como testemunha da verdade que professa, e juiz da falsidade do que professa; chamando-o para cumprir os julgamentos por perjúrio.', ARRAY['juramento','3º mandamento','culto'], ARRAY['Deuteronômio 10.20','Hebreus 6.16'], 117, '{"full_seed":true}'::jsonb),
    (v_doc_id, 118, '118', 'O que é requerido para fazer um juramento lícito?', 'É requerido para um juramento lícito que seja feito somente no nome de Deus; com total respeito por aquele grande nome, com compreensão plena da seriedade deste ato, com verdade, julgamento e justiça.', ARRAY['juramento','3º mandamento','nome de Deus'], ARRAY['Jeremias 4.2','Êxodo 23.13'], 118, '{"full_seed":true}'::jsonb),
    (v_doc_id, 119, '119', 'O que é um voto?', 'Um voto é da mesma natureza de um juramento promissório e deve ser feito com igual religiosidade, cuidado e fidelidade.', ARRAY['voto','juramento','3º mandamento'], ARRAY['Salmo 66.13-14','Eclesiastes 5.4-6'], 119, '{"full_seed":true}'::jsonb),
    (v_doc_id, 120, '120', 'O que é requerido que tornemos os dias do Senhor santos?', 'É requerido que tornemos o dia do Senhor santo: ou seja, que o deixemos ser um santo descanso todo o dia das atividades do mundo; e que passemos o tempo, em público e em privado, nos exercícios de culto e devoção; e que seja preparado nosso coração para isso, santificando o dia todo e as partes dele para as obras de necessidade e misericórdia.', ARRAY['4º mandamento','Dia do Senhor','culto','descanso'], ARRAY['Êxodo 20.8-11','Isaías 58.13'], 120, '{"full_seed":true}'::jsonb),
    (v_doc_id, 121, '121', 'Por que a palavra "lembra-te" está no começo do quarto mandamento?', 'A palavra "lembra-te" está no começo do quarto mandamento, primeiro porque o esquecimento e a omissão dele são muito propensos nos seres humanos; segundo, porque se lembrar o ajudará no desempenho de todo o mais dever, os demais dias da semana.', ARRAY['4º mandamento','sábado','memória'], ARRAY['Êxodo 20.8','Nehemias 13.15-22'], 121, '{"full_seed":true}'::jsonb),
    (v_doc_id, 122, '122', 'O que são os pecados proibidos no quarto mandamento?', 'Os pecados proibidos no quarto mandamento são: a omissão dos deveres necessários; a negligência descuidada, o desempenho descuidado, e a profanação do dia, por ociosidade, e por fazer aquilo que em si é pecaminoso; e por palavras e pensamentos desnecessários acerca de nossas atividades e recreações mundanas.', ARRAY['4º mandamento','profanação','negligência','sábado'], ARRAY['Ezequiel 22.26','Amós 8.5'], 122, '{"full_seed":true}'::jsonb),
    (v_doc_id, 123, '123', 'Que mandamentos são os outros mandamentos?', 'Os outros mandamentos são desde o quinto até o décimo e contêm nossos deveres para com os outros.', ARRAY['Dez Mandamentos','segunda tábua','próximo'], ARRAY['Mateus 22.39'], 123, '{"full_seed":true}'::jsonb),
    (v_doc_id, 124, '124', 'A quem chama "pai e mãe" no quinto mandamento?', 'Por "pai e mãe" no quinto mandamento são entendidos não somente os pais naturais, mas também todos os superiores em idade e dom; e especialmente os que por institução de Deus estão sobre nós, seja nas famílias, igrejas ou Estado.', ARRAY['5º mandamento','autoridade','família','Estado'], ARRAY['Provérbios 23.22','Efésios 6.1-2','Romanos 13.1'], 124, '{"full_seed":true}'::jsonb),
    (v_doc_id, 125, '125', 'Por que os pais e outros superiores são especialmente colocados em honra?', 'Os pais e outros superiores são especialmente colocados em honra, porque assim Deus, no quinto mandamento, designou-os seus representantes sobre nós e lhes foi delegado para nosso bem.', ARRAY['5º mandamento','autoridade','representação divina'], ARRAY['Romanos 13.1-2'], 125, '{"full_seed":true}'::jsonb),
    (v_doc_id, 126, '126', 'O que é a razão do quinto mandamento?', 'A razão do quinto mandamento é uma promessa de longa vida e prosperidade, o tanto que seja para a glória de Deus e o bem dos que assim cumprem este mandamento.', ARRAY['5º mandamento','promessa','bênção','vida longa'], ARRAY['Efésios 6.2-3','Deuteronômio 5.16'], 126, '{"full_seed":true}'::jsonb),
    (v_doc_id, 127, '127', 'Qual é a honra que os inferiores devem a seus superiores?', 'A honra que os inferiores devem a seus superiores é: respeito interior, em seus corações; com reverência exterior em sua conversa e comportamento; obediência às leis e mandamentos lícitos deles; submissão às suas repreensões e correções; fidelidade a, defensores de, e ora por eles, graças a Deus por eles e pela autoridade sobre eles.', ARRAY['5º mandamento','honra','obediência'], ARRAY['Efésios 6.1-2','Romanos 13.1'], 127, '{"full_seed":true}'::jsonb),
    (v_doc_id, 128, '128', 'O que são os pecados de inferiores contra seus superiores?', 'Os pecados de inferiores contra seus superiores são: desonra a seus superiores, ou encorajamento dos que os desonram; negligência dos deveres que se devem a eles; contrariedade ao seu poder lícito e correção; amaldiçoar ou zombar deles; caluniar ou difamá-los.', ARRAY['5º mandamento','desonra','rebeldia'], ARRAY['Mateus 15.4-6','Romanos 13.2'], 128, '{"full_seed":true}'::jsonb),
    (v_doc_id, 129, '129', 'O que é requerido dos superiores para com os inferiores?', 'É requerido dos superiores para com os inferiores: amar-lhes, orar por eles e abençoá-los; instrução deles; aconselhamento, exortação e advertência deles; assegurar, proteger e prover para eles, e tudo a bem e benefício deles.', ARRAY['5º mandamento','autoridade','cuidado','responsabilidade'], ARRAY['1 Tessalonicenses 2.7-8','Efésios 6.4'], 129, '{"full_seed":true}'::jsonb),
    (v_doc_id, 130, '130', 'O que são os pecados dos superiores?', 'Os pecados dos superiores são: negligência dos deveres requeridos deles; exercer comando injusto; indiferença ao bem de seus inferiores; desonrar-lhes; destituí-los de seus direitos legítimos; encorajamento e favorecimento dos que os desonram.', ARRAY['5º mandamento','negligência','liderança','abuso de autoridade'], ARRAY['Ezequiel 34.2-4'], 130, '{"full_seed":true}'::jsonb),
    (v_doc_id, 131, '131', 'O que são os deveres dos iguais para com os iguais?', 'Os deveres dos iguais para com os iguais são: dar preferência uns aos outros; em honrar uns aos outros sem orgulho; em bondade, humildade, paz; em ser pacientes, pacificadores e perdoadores de ofensas; em aceitar e dar conselhos bons; em encorajar uns aos outros às suas obrigações.', ARRAY['5º mandamento','igualdade','humildade','comunhão'], ARRAY['Romanos 12.10','Efésios 4.2-3'], 131, '{"full_seed":true}'::jsonb),
    (v_doc_id, 132, '132', 'O que são os pecados dos iguais?', 'Os pecados dos iguais são: subestimar as habilidades, as dádivas e os serviços de outros; inveja, orgulho e contrariedade; usurpar preeminência sobre seus iguais; erros na opinião de outros e de si mesmo.', ARRAY['5º mandamento','inveja','orgulho','rivalidade'], ARRAY['Romanos 12.16','Filipenses 2.3'], 132, '{"full_seed":true}'::jsonb),
    (v_doc_id, 133, '133', 'O que é o dever requerido no sexto mandamento?', 'O dever requerido no sexto mandamento é todo cuidado razoável e esforço lícito para preservar nossa própria vida e a de nosso próximo, por resistência de todos os pensamentos e propósitos, trazendo todas as paixões, evitando todas as ocasiões, tentações e práticas, que tendam à destruição injusta de qualquer vida.', ARRAY['6º mandamento','preservação da vida','paz'], ARRAY['Efésios 5.29','Salmo 82.3-4'], 133, '{"full_seed":true}'::jsonb),
    (v_doc_id, 134, '134', 'O que são os pecados proibidos no sexto mandamento?', 'Os pecados proibidos no sexto mandamento são: tirar nossa própria vida ou a de nosso próximo; deixar de se cuidar da própria vida; negligência ao guardar a vida dos outros; todo uso injusto de medidas que possam destruir a vida do próximo; tomar crueldade e desejo de matar; todos os meios que tendam à destruição injusta da vida de qualquer um.', ARRAY['6º mandamento','homicídio','crueldade','violência'], ARRAY['Gênesis 9.6','Mateus 5.22'], 134, '{"full_seed":true}'::jsonb),
    (v_doc_id, 135, '135', 'O que são os deveres requeridos no sétimo mandamento?', 'Os deveres requeridos no sétimo mandamento são a castidade em corpo, mente, afetos, palavras e comportamento; e a preservação de nossa própria castidade e de nosso próximo; observar os olhos e os outros sentidos; temperança, manutenção da honra do matrimônio, amor e coabitação; trabalho diligente; evitar toda circunstância de ociosidade, lascívia, companhia impura.', ARRAY['7º mandamento','castidade','matrimônio','temperança'], ARRAY['1 Tessalonicenses 4.4-5','1 Coríntios 7.2'], 135, '{"full_seed":true}'::jsonb),
    (v_doc_id, 136, '136', 'O que são os pecados proibidos no sétimo mandamento?', 'Os pecados proibidos no sétimo mandamento são todos os pecados imundos, em pensamento, palavras, ações; adultério, fornicação, estupro, incesto, sodomia e todas as outras práticas impuras; e todo o facilitar, tolerar e manter essas práticas.', ARRAY['7º mandamento','adultério','fornicação','impureza'], ARRAY['Mateus 15.19','Efésios 5.3-4'], 136, '{"full_seed":true}'::jsonb),
    (v_doc_id, 137, '137', 'O que são os deveres requeridos no oitavo mandamento?', 'Os deveres requeridos no oitavo mandamento são: verdade, fidelidade e justiça em transações, dando a todos o que é devido, restituindo ilegitimamente os bens obtidos, dar e emprestar livremente segundo nossas capacidades e a necessidade dos outros, moderação dos nossos julgamentos, vontades e afetos para as riquezas mundanas; ser trabalhador e poupador.', ARRAY['8º mandamento','justiça','honestidade','mordomia'], ARRAY['Romanos 13.7','Levítico 25.35-37'], 137, '{"full_seed":true}'::jsonb),
    (v_doc_id, 138, '138', 'O que são os pecados proibidos no oitavo mandamento?', 'Os pecados proibidos no oitavo mandamento são: furto, roubo, sequestro, fraude em contratos, peso e medida desonesta, remoção de limites de terra, injustiça em contratos; corrupção; extorsão; compra e venda com desonestidade; avareza; expropriação desnecessária da propriedade alheia; não pagar as dívidas.', ARRAY['8º mandamento','roubo','fraude','avareza'], ARRAY['Provérbios 11.1','Ezequiel 22.12','1 Coríntios 6.10'], 138, '{"full_seed":true}'::jsonb),
    (v_doc_id, 139, '139', 'O que são os deveres requeridos no nono mandamento?', 'Os deveres requeridos no nono mandamento são: cuidado e preservação do bom nome de nosso próximo, assim como o nosso; afirmar verdadeira justiça quando isso é necessário; manter confidências; falar bem de todos, como merecem; defender as calúnias dos inocentes; uma boa vontade de aceitar uma boa interpretação das palavras e ações dos outros.', ARRAY['9º mandamento','verdade','reputação'], ARRAY['Efésios 4.15','Provérbios 31.8-9'], 139, '{"full_seed":true}'::jsonb),
    (v_doc_id, 140, '140', 'O que são os pecados proibidos no nono mandamento?', 'Os pecados proibidos no nono mandamento são: dar falso testemunho, subornar; trair a verdade, ignorar o sentido das palavras de outros na interpretação; mentir, falso relato; divulgar culpas e faltas desnecessárias; o que é contrário à equidade, a falsidade em expressão ou impressão; amplificação e deturpação de fatos; calúnia e maledicência; difamação e zombaria.', ARRAY['9º mandamento','mentira','calúnia','perjúrio'], ARRAY['Provérbios 6.16-19','Salmo 15.3'], 140, '{"full_seed":true}'::jsonb),
    (v_doc_id, 141, '141', 'O que é o dever requerido no décimo mandamento?', 'O dever requerido no décimo mandamento é tal plena disposição de espírito para a nossa própria condição, com uma caridosa disposição para com o próximo e tudo o que lhe pertence.', ARRAY['10º mandamento','contentamento','caridade'], ARRAY['Hebreus 13.5','1 Timóteo 6.6'], 141, '{"full_seed":true}'::jsonb),
    (v_doc_id, 142, '142', 'O que são os pecados proibidos no décimo mandamento?', 'Os pecados proibidos no décimo mandamento são: todo descontentamento com a nossa própria condição; ter inveja ou prazer no mal do nosso próximo; todos os desejos inapropriados depois de qualquer coisa que é do próximo.', ARRAY['10º mandamento','cobiça','inveja','descontentamento'], ARRAY['1 Coríntios 10.10','Gálatas 5.26'], 142, '{"full_seed":true}'::jsonb),
    (v_doc_id, 143, '143', 'Qual é a importância de entender a lei de Deus?', 'A lei de Deus é santa, justa e boa; e sendo espiritual, descobre os pecados mais íntimos do coração; mas é incapaz de dar conhecimento para salvar, ou poder para obedecer.', ARRAY['lei','espiritualidade','conhecimento do pecado'], ARRAY['Romanos 7.12','Romanos 7.14','Romanos 8.3'], 143, '{"full_seed":true}'::jsonb),
    (v_doc_id, 144, '144', 'O que é pecado?', 'Pecado é qualquer falta de conformidade à lei de Deus, ou transgressão da mesma, que venha de qualquer parte da pessoa.', ARRAY['pecado','lei','transgressão'], ARRAY['1 João 3.4','Romanos 3.23'], 144, '{"full_seed":true}'::jsonb),
    (v_doc_id, 145, '145', 'Que é o pecado mais grave?', 'Alguns pecados em si mesmos e pelas suas circunstâncias são mais graves que outros; assim são: os que são cometidos contra uma maior luz e conhecimento; os que são em si muito odiosos; os que são cometidos contra os princípios da natureza, contra grandes dons de Deus; os que são flagrantes ou especialmente ofensivos contra Deus.', ARRAY['pecado','gradação','gravidade'], ARRAY['João 19.11','Mateus 11.22-24'], 145, '{"full_seed":true}'::jsonb),
    (v_doc_id, 146, '146', 'Qual é a condenação que todos os pecados merecem?', 'Todo pecado, sendo uma transgressão da lei de Deus, e contrário à sua natureza, merece a ira e a maldição de Deus, tanto temporal, espiritual como eternamente.', ARRAY['pecado','condenação','ira de Deus','maldição'], ARRAY['Efésios 5.6','Gálatas 3.10'], 146, '{"full_seed":true}'::jsonb),
    (v_doc_id, 147, '147', 'O que Deus requer de nós para escapar de sua ira e maldição?', 'Para escapar da ira e maldição de Deus merecida pelo nosso pecado, Deus requer de nós fé em Jesus Cristo, arrependimento para vida, com o uso diligente de todos os meios externos pelos quais Cristo nos comunica os benefícios da mediação.', ARRAY['salvação','fé','arrependimento','meios de graça'], ARRAY['Atos 20.21','Atos 16.30-31'], 147, '{"full_seed":true}'::jsonb),
    (v_doc_id, 148, '148', 'O que é a fé em Jesus Cristo?', 'A fé em Jesus Cristo é uma graça salvadora pela qual reconhecemos a verdade das coisas reveladas na Palavra por causa da autoridade divina de Deus em dar-nos o testemunho; e assim cremos pela verdade de tudo que a Palavra nos afirma; mas principalmente aproveitamo-nos da misericórdia de Deus e de Jesus Cristo para com os pecadores; aceitando, recebendo e descansando em Cristo e em sua justiça somente para justificação, santificação e vida eterna, mediante a aliança de graça.', ARRAY['fé','Cristo','justificação','aliança de graça'], ARRAY['Atos 16.31','João 1.12','Filipenses 3.9'], 148, '{"full_seed":true}'::jsonb),
    (v_doc_id, 149, '149', 'A fé está em alguém por natureza?', 'A fé, sendo obra sobrenatural, não está em ninguém por natureza; mas é dom de Deus, trazido pelo Espírito Santo ao coração dos escolhidos por Deus.', ARRAY['fé','graça','Espírito Santo','dom'], ARRAY['Efésios 2.8','2 Tessalonicenses 3.2'], 149, '{"full_seed":true}'::jsonb),
    (v_doc_id, 150, '150', 'Qual é a força da fé?', 'A força da fé crescendo da medida de fé dada; por Cristo; pelo ministério da Palavra, pelos sacramentos, pela oração e pelo Espírito Santo; sendo apoiado em nossas tentações.', ARRAY['fé','crescimento','meios de graça'], ARRAY['Romanos 4.19-20','2 Pedro 1.5-7','Lucas 17.5'], 150, '{"full_seed":true}'::jsonb),
    (v_doc_id, 151, '151', 'O que é arrependimento para vida?', 'O arrependimento para vida é uma graça salvadora trabalhada no coração do pecador pelo Espírito de Deus; pelo qual, com verdadeiro arrependimento dos seus pecados, e compreensão da misericórdia de Deus em Cristo, ele se enluta e abomina os seus pecados, e se volta deles para Deus com pleno propósito e esforço de nova obediência.', ARRAY['arrependimento','Espírito Santo','obediência'], ARRAY['Zacarias 12.10','2 Coríntios 7.11'], 151, '{"full_seed":true}'::jsonb),
    (v_doc_id, 152, '152', 'Para que serve a lei para os regenerados?', 'A lei serve para os regenerados para mostrar-lhes mais claramente o que suas naturezas corrompidas exigem; que confessem sua culpa e fraqueza; e ajudá-los a humilharem-se diante de Deus, para levá-los mais a Cristo e para inclinar sua vontade mais à lei.', ARRAY['lei','regeneração','terceiro uso da lei','humildade'], ARRAY['Romanos 7.22-24','Salmo 51.4'], 152, '{"full_seed":true}'::jsonb),
    (v_doc_id, 153, '153', 'O que é a Palavra de Deus?', 'A Palavra de Deus são as Escrituras do Antigo e Novo Testamento, que são a única regra suficiente, certa e infalível para o nosso conhecimento, fé e obediência salvadores.', ARRAY['Escrituras','regra de fé','Palavra de Deus'], ARRAY['2 Timóteo 3.16-17','Efésios 2.20'], 153, '{"full_seed":true}'::jsonb),
    (v_doc_id, 154, '154', 'O que são os sacramentos do Novo Testamento?', 'Os sacramentos do Novo Testamento são o Batismo e a Ceia do Senhor, instituídos por Jesus Cristo para ser administrados, até que ele venha outra vez; como sinais e selos do pacto de graça, para representar Cristo e seus benefícios, e para confirmar a nossa participação nele; assim como também para fazer uma visível diferença entre os que pertencem à Igreja e o restante do mundo, e solenemente para nos vincular à obediência e serviço a Deus em Cristo, segundo sua Palavra.', ARRAY['sacramentos','aliança de graça','Batismo','Ceia do Senhor'], ARRAY['Mateus 28.19','1 Coríntios 11.23-26'], 154, '{"full_seed":true}'::jsonb),
    (v_doc_id, 155, '155', 'Como deve ser a Palavra pregada?', 'A Palavra de Deus deve ser pregada somente por pregadores de dons convenientes e aqueles que são regularmente chamados e que, aprovados por seus princípios e métodos de pregação, devem pregar fielmente o conselho todo de Deus; com sabedoria e aplicação; com fervor e sinceridade; com o desejo de beneficiar seus ouvintes.', ARRAY['pregação','ministério','Palavra'], ARRAY['2 Timóteo 4.2','Atos 20.27','1 Coríntios 9.16'], 155, '{"full_seed":true}'::jsonb),
    (v_doc_id, 156, '156', 'É a Palavra de Deus para ser lida por todos?', 'Embora todos não possam ser chamados para pregação pública da Palavra, contudo todos têm que ler as Escrituras em particular; como também ensinar ou exortar na família, assim como em reuniões.', ARRAY['Escrituras','leitura','família'], ARRAY['Deuteronômio 17.19','Atos 8.28-30'], 156, '{"full_seed":true}'::jsonb),
    (v_doc_id, 157, '157', 'Como as Escrituras devem ser lidas?', 'As Escrituras devem ser lidas com um espírito reverente; com grande atenção e reverência; com convicção de que a Palavra de Deus é a única sabedoria e verdade; com meditação, comparando escritura com escritura; examinando a nós mesmos à sua luz; recebendo com fé, amor e docilidade toda doutrina; exercendo em obediência sua vocação.', ARRAY['Escrituras','leitura','meditação','obediência'], ARRAY['Salmo 1.2','Provérbios 8.34'], 157, '{"full_seed":true}'::jsonb),
    (v_doc_id, 158, '158', 'Como deve o ouvinte da Palavra se dispor a ouvi-la?', 'Para ouvir a Palavra pregada, é requerido: que venha com devida preparação; em oração; com expectativa de aprender a vontade de Deus; com fé e amor; com atenção, docilidade, meditação; recebendo a doutrina da Palavra pregada com toda prontidão de espírito, provando os espíritos.', ARRAY['pregação','ouvir','fé','preparação'], ARRAY['Provérbios 8.34','1 Tessalonicenses 2.13','Atos 17.11'], 158, '{"full_seed":true}'::jsonb),
    (v_doc_id, 159, '159', 'Como deve ser administrado o Batismo?', 'O Batismo deve ser administrado pelo ministério do evangelho, somente àqueles para quem a Palavra e o sacramento forem designados por Cristo; sendo somente por lavagem com água no nome do Pai, do Filho e do Espírito Santo.', ARRAY['Batismo','administração','Trindade'], ARRAY['Mateus 28.19','Atos 2.38'], 159, '{"full_seed":true}'::jsonb),
    (v_doc_id, 160, '160', 'Para quem o Batismo deve ser administrado?', 'O Batismo deve ser administrado àqueles que fazem profissão de sua fé em Cristo e de sua obediência a ele; e a seus filhos, os quais devem ser batizados.', ARRAY['Batismo','batismo de infantes','aliança','profissão de fé'], ARRAY['Atos 2.38-39','Gênesis 17.10-12'], 160, '{"full_seed":true}'::jsonb),
    (v_doc_id, 161, '161', 'Como se tornam os sacramentos meios eficazes de salvação?', 'Os sacramentos se tornam meios eficazes de graça e salvação, não de qualquer virtude que há neles ou em qualquer virtude do que os administra; mas somente por bênção de Cristo e operação de seu Espírito naqueles que os recebem pela fé.', ARRAY['sacramentos','Espírito Santo','fé','eficácia'], ARRAY['1 Pedro 3.21','1 Coríntios 3.7'], 161, '{"full_seed":true}'::jsonb),
    (v_doc_id, 162, '162', 'O que é a Ceia do Senhor?', 'A Ceia do Senhor é um sacramento do Novo Testamento em que Cristo é representado em seu corpo e sangue, como o sustento espiritual de todos os crentes; pela dação e recepção do pão e do vinho segundo sua própria instituição; sendo feita para memória de Cristo e proclamação de sua morte até que ele venha.', ARRAY['Ceia do Senhor','morte de Cristo','memória','sacramento'], ARRAY['1 Coríntios 11.23-26'], 162, '{"full_seed":true}'::jsonb),
    (v_doc_id, 163, '163', 'O que é requerido para a digna recepção da Ceia do Senhor?', 'É requerido para a digna recepção da Ceia do Senhor: examinar a nós mesmos acerca do nosso conhecimento para discernir o corpo do Senhor, nosso amor a Cristo, nossa fé nele, e a penitência, o amor e nova obediência ao próximo; não comer ou beber indigno, a fim de não comermos nosso próprio julgamento.', ARRAY['Ceia do Senhor','auto-exame','dignidade','preparação'], ARRAY['1 Coríntios 11.28-29','2 Coríntios 13.5'], 163, '{"full_seed":true}'::jsonb),
    (v_doc_id, 164, '164', 'O que é a oração?', 'A oração é uma oferta dos nossos desejos a Deus, em nome de Cristo, pela assistência do Espírito Santo; com confissão dos nossos pecados, e reconhecimento grato de suas misericórdias.', ARRAY['oração','confissão','gratidão','Espírito Santo'], ARRAY['Filipenses 4.6','João 14.13-14'], 164, '{"full_seed":true}'::jsonb),
    (v_doc_id, 165, '165', 'Como a oração deve ser feita?', 'A oração deve ser feita: com reverência e humildade; com entendimento, fé, sinceridade e fervor; com amor, perseverança e com submissão à vontade de Deus.', ARRAY['oração','reverência','fé','humildade'], ARRAY['Tiago 5.16','1 João 5.14'], 165, '{"full_seed":true}'::jsonb),
    (v_doc_id, 166, '166', 'Para que oramos?', 'Devemos orar por toda a humanidade; especialmente pelos eleitos de Deus; pelos que estão em autoridade; por nossa família; por nós mesmos; por nossos inimigos; e pela Igreja de Cristo em geral e especialmente pelos pobres.', ARRAY['oração','intercessão','eleitos','autoridade'], ARRAY['1 Timóteo 2.1-2','Romanos 15.30'], 166, '{"full_seed":true}'::jsonb),
    (v_doc_id, 167, '167', 'Por que o jejum é recomendado nas Escrituras?', 'O jejum privado ou público religioso é um dever que pode ser recomendado com humildade de espírito; com oração; como preparação diante de Deus para receber suas misericórdias; como uma forma de lamúria por pecados pessoais ou da nação; e em certos e solenes dias de ação de graças.', ARRAY['jejum','oração','humildade','luto'], ARRAY['Joel 1.14','Atos 13.3'], 167, '{"full_seed":true}'::jsonb),
    (v_doc_id, 168, '168', 'O que é o jejum religioso?', 'O jejum religioso requer a abstenção de comida por um determinado período, para obter o favor de Deus, com meditação em sua Palavra, oração e louvor, pelo bem do povo e em preparação para outras responsabilidades.', ARRAY['jejum','meios de graça','oração'], ARRAY['Mateus 6.16-18','Nehemias 9.1-3'], 168, '{"full_seed":true}'::jsonb),
    (v_doc_id, 169, '169', 'O que é a ação de graças?', 'A ação de graças é uma obrigação de louvar a Deus por seus dons e bênçãos dadas a nós; como parte da adoração religiosa em reconhecimento de todos os seus benefícios.', ARRAY['ação de graças','louvor','gratidão'], ARRAY['Filipenses 4.6','Colossenses 4.2'], 169, '{"full_seed":true}'::jsonb),
    (v_doc_id, 170, '170', 'Como o nome de Cristo deve ser santificado?', 'O nome de Cristo deve ser santificado por nós: invocando-o em oração, confissão, juramento e voto; nas nossas palavras e conversa; em louvor e ação de graças; e especialmente na administração e uso dos sacramentos da Igreja.', ARRAY['nome de Cristo','santificação','adoração'], ARRAY['Salmo 50.14-15','Mateus 5.34-37'], 170, '{"full_seed":true}'::jsonb),
    (v_doc_id, 171, '171', 'Devem os regenerados temer o julgamento que vem?', 'Os regenerados não devem temer a morte ou o julgamento, uma vez que Cristo os absolveu de todo pecado e morte na cruz; e que eles podem esperar sua glorificação com confiança na justiça de Cristo que os cobre.', ARRAY['julgamento','segurança','cristãos','asseguração'], ARRAY['João 5.24','Romanos 8.1','1 Coríntios 15.54-57'], 171, '{"full_seed":true}'::jsonb),
    (v_doc_id, 172, '172', 'O que pode dar ao crente certeza de que está em estado de graça?', 'Embora a hipocrisas e outras pessoas não regeneradas possam se iludir com esperanças falsas e presunções de estar na misericórdia de Deus e no estado de salvação; o que será depois de si próprio destruído: contudo, os que verdadeiramente creem em Jesus Cristo, e amam a ele em sinceridade; esforçam-se para andar em toda boa consciência diante dele, podem nesta vida ter certeza de que estão em estado de graça.', ARRAY['asseguração','graça','fé','consciência'], ARRAY['1 João 2.3','2 Pedro 1.5-10'], 172, '{"full_seed":true}'::jsonb),
    (v_doc_id, 173, '173', 'Pode esta certeza ser abalada?', 'Esta certeza pode ser abalada, diminuída e intermitida; por várias razões: a negligência em conservá-la; ao cair em algum pecado especial, que fere a consciência e contristam o Espírito; por alguma tentação repentina ou violenta; pela retirada da luz do rosto de Deus, ao deixar até mesmo os que temem a ele para andar em escuridão.', ARRAY['asseguração','queda','Espírito Santo','sofrimento'], ARRAY['Efésios 4.30','Salmo 51.8-12'], 173, '{"full_seed":true}'::jsonb),
    (v_doc_id, 174, '174', 'Como os crentes devem se comportar na Ceia do Senhor?', 'Os crentes devem na Ceia do Senhor se comportar com reverência e exame cuidadoso de si mesmos; com especial reflexão sobre a morte de Cristo; com auto-exame de fé; com humilhação em vistas de sua indignidade; com gratidão pelo amor de Cristo; com desejo de crescimento em graça.', ARRAY['Ceia do Senhor','reverência','gratidão','auto-exame'], ARRAY['1 Coríntios 11.28','Salmo 22.26'], 174, '{"full_seed":true}'::jsonb),
    (v_doc_id, 175, '175', 'O que é o dever do crente depois de participar da Ceia do Senhor?', 'O dever do crente após participar da Ceia do Senhor é: observar seriamente como ele foi tratado com misericórdia de Deus nesta participação; examinar-se quanto ao que ele ganhou ou não na participação; agradecendo a Deus por sua graça; renunciando mais ao pecado; aderindo mais fortemente a Cristo e sua aliança; se encorajando mais em graça e amor.', ARRAY['Ceia do Senhor','reflexão','gratidão','crescimento'], ARRAY['Salmo 22.26','1 Coríntios 11.25-26'], 175, '{"full_seed":true}'::jsonb),
    (v_doc_id, 176, '176', 'Quem deve participar da Ceia do Senhor?', 'Aqueles que já são membros visíveis da Igreja, que foram suficientemente examinados pelos ministros, e que admitiram que têm fé em Cristo e arrependimento, que devem ser admitidos à Ceia.', ARRAY['Ceia do Senhor','membros da Igreja','disciplina'], ARRAY['1 Coríntios 11.28','Atos 2.41-42'], 176, '{"full_seed":true}'::jsonb),
    (v_doc_id, 177, '177', 'Em que diferem o Batismo e a Ceia do Senhor?', 'O Batismo e a Ceia do Senhor concordam em ser ambos instituídos por Deus; em Cristo Jesus ser o fundamento de ambos; em ter o Espírito Santo como agente que os torna eficazes; em seu modo de comunicar a aliança de graça; em pertencerem à Igreja. Mas diferem: em que o Batismo é administrado somente uma vez, e significa nascimento e enxertamento em Cristo; a Ceia do Senhor é administrada repetidamente e significa o alimento e crescimento em Cristo.', ARRAY['Batismo','Ceia do Senhor','sacramentos','diferença'], ARRAY['Mateus 28.19','1 Coríntios 11.23-26'], 177, '{"full_seed":true}'::jsonb),
    (v_doc_id, 178, '178', 'O que é a oração particular e familiar?', 'É necessário que se reze em particular, assim como em família, tão frequente quanto as ocasiões necessitarem; com fervor e perseverança; e com ação de graças.', ARRAY['oração','família','perseverança'], ARRAY['Mateus 6.6','Colossenses 4.2','Atos 10.2'], 178, '{"full_seed":true}'::jsonb),
    (v_doc_id, 179, '179', 'O que são as orações apropriadíssimas à adoração pública?', 'A adoração pública deve conter: a leitura da Palavra de Deus; a pregação e audição da Palavra; o ensino e a admoestação uns aos outros; a salmódia; a administração dos sacramentos; a oração e ação de graças para si e por outros.', ARRAY['adoração','culto público','pregação','sacramentos'], ARRAY['Atos 2.42','1 Timóteo 2.1-2'], 179, '{"full_seed":true}'::jsonb),
    (v_doc_id, 180, '180', 'O que é necessário para que a Palavra seja bem pregada?', 'Para que a Palavra seja bem pregada é necessário: pregar livremente o conselho todo de Deus; com fidelidade e prudência; com exortação, consolação e reprovação, conforme as necessidades; com fervor e sinceridade; com o propósito de glorificar a Deus e edificar os ouvintes.', ARRAY['pregação','fidelidade','ministério'], ARRAY['2 Timóteo 4.2','Atos 20.20-21','1 Coríntios 9.22'], 180, '{"full_seed":true}'::jsonb),
    (v_doc_id, 181, '181', 'Como devemos ouvir a Palavra pregada?', 'Para que a Palavra seja eficaz, é necessário que os ouvintes a atendam com diligência e oração; com fé e reverência; recebendo-a com amor como Palavra de Deus; meditando nela; guardando-a em seus corações; praticando-a na vida.', ARRAY['Palavra','ouvir','meditação','obediência'], ARRAY['1 Tessalonicenses 2.13','Tiago 1.21-22'], 181, '{"full_seed":true}'::jsonb),
    (v_doc_id, 182, '182', 'Como a oração deve ser feita para Deus?', 'A oração deve ser feita somente a Deus; como sendo o único que sabe o coração e que é capaz de ouvir e responder; pela qual honra e glória é dado a ele.', ARRAY['oração','a quem orar','adoração'], ARRAY['Mateus 4.10','João 16.23'], 182, '{"full_seed":true}'::jsonb),
    (v_doc_id, 183, '183', 'Por quem devemos orar?', 'Devemos orar por nós mesmos e por outros; por todos os que a Deus ordena orarmos; particularmente a Igreja de Deus com todo o povo dela; pelos ministros do evangelho; pelos magistrados; por todos os que têm necessidades espirituais e temporais; por nossos amigos e inimigos; e por toda a classe de pecadores.', ARRAY['oração','intercessão','missão','Igreja'], ARRAY['1 Timóteo 2.1-2','Mateus 5.44'], 183, '{"full_seed":true}'::jsonb),
    (v_doc_id, 184, '184', 'Em nome de quem devemos orar?', 'Devemos orar somente no nome de Cristo; e não nos apresentar a Deus nem confiar nele a não ser pela mediação de Cristo.', ARRAY['oração','nome de Cristo','mediação'], ARRAY['João 14.13-14','Hebreus 4.14-16'], 184, '{"full_seed":true}'::jsonb),
    (v_doc_id, 185, '185', 'Como devemos orar com o Espírito?', 'Orar com o Espírito é orar com o auxílio do Espírito Santo; despertando e sustentando em nós os dons e graças requeridos para pedir a Deus o que sua vontade é, com entendimento, fervor e fé; o que é requerido de nós nas orações.', ARRAY['oração','Espírito Santo','dons'], ARRAY['Romanos 8.26-27','1 Coríntios 14.15'], 185, '{"full_seed":true}'::jsonb),
    (v_doc_id, 186, '186', 'O que é exigido de nós pela lei de Deus?', 'O que é exigido de nós pela lei de Deus é perfeita obediência à sua vontade revelada; e sendo incapazes por causa de nossa corrupção, devemos recorrer a Cristo como nosso único redentor.', ARRAY['lei','obediência perfeita','incapacidade','graça'], ARRAY['Deuteronômio 6.25','Gálatas 3.10-13'], 186, '{"full_seed":true}'::jsonb),
    (v_doc_id, 187, '187', 'O que devemos fazer pelo nosso bem eterno?', 'Devemos perseverar nos meios que Deus ordenou para o nosso crescimento em graça; meditando em sua Palavra; ouvindo a pregação; participando dos sacramentos; adorando em conjunto; praticando a oração; jejuando e dando esmolas.', ARRAY['crescimento em graça','meios de graça','perseverança'], ARRAY['2 Pedro 3.18','Atos 2.42'], 187, '{"full_seed":true}'::jsonb),
    (v_doc_id, 188, '188', 'Quais são os poderes ordinários pelos quais Cristo comunica os benefícios de sua mediação?', 'Os poderes ordinários pelos quais Cristo comunica os benefícios de sua mediação são todos os seus ordenamentos, especialmente a Palavra, os sacramentos e a oração; todos os quais são tornados eficazes para a salvação dos eleitos somente pela bênção de Cristo e pela operação de seu Espírito.', ARRAY['meios de graça','Cristo','Espírito Santo'], ARRAY['Mateus 28.19-20','Atos 2.42'], 188, '{"full_seed":true}'::jsonb),
    (v_doc_id, 189, '189', 'Por que as Escrituras são chamadas a Palavra de Deus?', 'As Escrituras são chamadas a Palavra de Deus, porque são dadas pelo sopro de Deus, sendo a revelação de sua mente e vontade, e portanto autorizadas e obrigatórias; contendo completa revelação de tudo necessário para a fé e vida cristã.', ARRAY['Escrituras','inspiração','autoridade'], ARRAY['2 Timóteo 3.16-17','2 Pedro 1.21'], 189, '{"full_seed":true}'::jsonb),
    (v_doc_id, 190, '190', 'O que é requerido para que se cumpra o dever de orar adequadamente?', 'É requerido para se orar adequadamente: que tenhamos entendimento do que pedimos; com sentimentos devidos; com fé e submissão à vontade de Deus; com humildade e reverência a Deus; com sinceridade; com fervor; com amor a Deus e ao próximo; com confissão de pecados e gratidão pelas misericórdias.', ARRAY['oração','fé','humildade','sinceridade'], ARRAY['1 João 5.14','Tiago 5.16'], 190, '{"full_seed":true}'::jsonb),
    (v_doc_id, 191, '191', 'O que pedimos na primeira petição?', 'Na primeira petição, que é "Santificado seja o teu nome", pedimos reconhecendo nossa total incapacidade para glorificar a Deus; que ele por sua graça nos habilite a nos apropriar e glorificá-lo em pensamento, palavra e ação; que disponha todas as coisas para sua própria glória.', ARRAY['Pai Nosso','glorificação','1ª petição'], ARRAY['Salmo 67.1-3'], 191, '{"full_seed":true}'::jsonb),
    (v_doc_id, 192, '192', 'O que pedimos na segunda petição?', 'Na segunda petição, que é "Venha o teu reino", pedimos que o reino de Satanás seja destruído; que o reino da graça seja avançado, e nós e outros nele sermos mantidos; e que o reino da glória se acelerado.', ARRAY['Pai Nosso','reino de Deus','2ª petição'], ARRAY['Romanos 10.1','2 Tessalonicenses 3.1'], 192, '{"full_seed":true}'::jsonb),
    (v_doc_id, 193, '193', 'O que pedimos na terceira petição?', 'Na terceira petição, que é "Seja feita a tua vontade, assim na terra como no céu", pedimos que Deus por sua graça nos torne capazes e dispostos a saber e fazer sua vontade em tudo, como os anjos o fazem no céu.', ARRAY['Pai Nosso','vontade de Deus','3ª petição'], ARRAY['Salmo 103.20-21'], 193, '{"full_seed":true}'::jsonb),
    (v_doc_id, 194, '194', 'O que pedimos na quarta petição?', 'Na quarta petição, que é "O pão nosso de cada dia nos dá hoje", pedimos receber de Deus uma porção conveniente dos bens desta vida e com ela a sua bênção.', ARRAY['Pai Nosso','providência','4ª petição'], ARRAY['Provérbios 30.8-9'], 194, '{"full_seed":true}'::jsonb),
    (v_doc_id, 195, '195', 'O que pedimos na quinta petição?', 'Na quinta petição, que é "Perdoa-nos as nossas dívidas, assim como nós perdoamos os nossos devedores", pedimos a Deus que, por causa de Cristo, perdoe todos os nossos pecados; sendo por isso animados a perdoar de coração a outros pelas ofensas deles.', ARRAY['Pai Nosso','perdão','5ª petição'], ARRAY['Salmo 51.1-2','Mateus 6.14'], 195, '{"full_seed":true}'::jsonb),
    (v_doc_id, 196, '196', 'O que pedimos na sexta petição?', 'Na sexta petição, que é "E não nos deixes cair em tentação, mas livra-nos do mal", pedimos a Deus que nos guarde de ser tentados ao pecado; e que se tentados, nos apoie e defenda; de tal modo que sejamos preservados de cair; e se caídos, que sejamos restaurados.', ARRAY['Pai Nosso','tentação','perseverança','6ª petição'], ARRAY['1 Coríntios 10.13','Salmo 19.13'], 196, '{"full_seed":true}'::jsonb)
  ON CONFLICT (document_id, number) DO UPDATE SET
    number_label    = EXCLUDED.number_label,
    question        = EXCLUDED.question,
    answer          = EXCLUDED.answer,
    doctrine_tags   = EXCLUDED.doctrine_tags,
    bible_references = EXCLUDED.bible_references,
    sort_order      = EXCLUDED.sort_order,
    metadata        = public.lampas_confessional_questions.metadata || EXCLUDED.metadata;

  RAISE NOTICE 'Catecismo Maior de Westminster (Parte 2 — Q99-196): inseridas/atualizadas.';
END;
$$;
